### ISSUE TITLE
400 with creating contact without Content-Length header

### ISSUE THREAD

**Issue by emersion** [Kozea/Radicale#1016]
When issuing a POST request with this vCard:

```
BEGIN:VCARD
VERSION:3.0
EMAIL:test@example.org
FN:This is a test
UID:urn:uuid:c40ab617-223c-4955-8254-7cfd8bbc0ec0
END:VCARD
```

The server sends a 500 ("500 Internal Server Error: A server error occurred.  Please contact the administrator."). The logs say:

```
[7ff6e9475700] ERROR: An exception occurred during PUT request on '/XXX/5931d7ce-a79c-3784-c15c-307b11a661a4/c40ab617-223c-4955-8254-7cfd8bbc0ec0.vcf': tuple index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.8/site-packages/radicale/__init__.py", line 504, in _handle_request
    status, headers, answer = function(
  File "/usr/lib/python3.8/site-packages/radicale/__init__.py", line 948, in do_PUT
    new_item = parent_item.upload(href, items[0])
IndexError: tuple index out of range
```

**Comment by emersion** [comment]
Actually, it seems like the request body is empty.

Tried with the latest commit, and the request correctly fails with a 400.

**Comment by emersion** [comment]
Scratch that. Apparently the server completely ignores the request body when no Content-Length header is provided:

https://github.com/Kozea/Radicale/blob/db7587c59335fa00580ce88d583419ce45594143/radicale/app/__init__.py#L340

**Comment by emersion** [comment]
Apparently this is a wsgi issue:

>It is necessary to know the response body size as an integer to read it from wsgi.input.

**Comment by pbiering** [comment]
old version, not our bug
