### ISSUE TITLE
radicale v3, frequent token errors: ValueError("Token not found: %r" % old_token) ?

### ISSUE THREAD

**Issue by pgnd** [Kozea/Radicale#1049]
Since upgading to radicale v3
```
 pip show radicale
 Name: Radicale
 Version: 3.0.0
 Summary: CalDAV and CardDAV Server
 Home-page: https://radicale.org/
 Author: Guillaume Ayoub
 Author-email: guillaume.ayoub@kozea.fr
 License: GNU GPL v3
 Location: /usr/local/src/pyenv/versions/3.8-dev/lib/python3.8/site-packages
 Requires: defusedxml, python-dateutil, vobject, passlib
 Required-by:
```

I'm seeing frequent token-relate errors in logs
```
May 23 07:44:10 dev.loc radicale[3826]: [2020-05-23 07:44:10 -0700] [3826/Thread-4] [DEBUG] Request content:
May 23 07:44:10 dev.loc radicale[3826]: <?xml version="1.0"?>
May 23 07:44:10 dev.loc radicale[3826]: <sync-collection xmlns="DAV:">
May 23 07:44:10 dev.loc radicale[3826]:   <sync-token>http://radicale.org/ns/sync/4023...ed1f</sync-token>
May 23 07:44:10 dev.loc radicale[3826]:   <sync-level>1</sync-level>
May 23 07:44:10 dev.loc radicale[3826]:   <prop>
May 23 07:44:10 dev.loc radicale[3826]:     <getetag />
May 23 07:44:10 dev.loc radicale[3826]:   </prop>
May 23 07:44:10 dev.loc radicale[3826]: </sync-collection>
May 23 07:44:10 dev.loc radicale[3826]: [2020-05-23 07:44:10 -0700] [3826/Thread-4] [DEBUG] Client provided sync token: 'http://radicale.org/ns/sync/4023...ed1f'
May 23 07:44:10 dev.loc radicale[3826]: [2020-05-23 07:44:10 -0700] [3826/Thread-4] [WARNING] Client provided invalid sync token 'http://radicale.org/ns/sync/4023...ed1f': Token not found: 'http://radicale.org/ns/sync/4023...ed1f'
May 23 07:44:10 dev.loc radicale[3826]: Traceback (most recent call last):
May 23 07:44:10 dev.loc radicale[3826]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/storage/multifilesystem/sync.py", line 72, in sync
May 23 07:44:10 dev.loc radicale[3826]:     with open(old_token_path, "rb") as f:
May 23 07:44:10 dev.loc radicale[3826]: FileNotFoundError: [Errno 2] No such file or directory: '/data/radicale/collections/collection-root/dev@example.com/3d75...1832/.Radicale.cache/sync-token/4023...ed1f'
May 23 07:44:10 dev.loc radicale[3826]: During handling of the above exception, another exception occurred:
May 23 07:44:10 dev.loc radicale[3826]: Traceback (most recent call last):
May 23 07:44:10 dev.loc radicale[3826]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/app/report.py", line 90, in xml_report
May 23 07:44:10 dev.loc radicale[3826]:     sync_token, names = collection.sync(old_sync_token)
May 23 07:44:10 dev.loc radicale[3826]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/storage/multifilesystem/sync.py", line 85, in sync
May 23 07:44:10 dev.loc radicale[3826]:     raise ValueError("Token not found: %r" % old_token)
May 23 07:44:10 dev.loc radicale[3826]: ValueError: Token not found: 'http://radicale.org/ns/sync/4023...ed1f'
May 23 07:44:10 dev.loc radicale[3826]: [2020-05-23 07:44:10 -0700] [3826/Thread-4] [DEBUG] Response content:
```
This^ example is during access from DavX5 client running on Android.

Deleting & re-creating the accounts on the phone doesn't seem to make any difference ... these error start reapppearing.

Also, it's unclear why there's an OFFSITE link, "http://radicale.org/ns/sync/...".  Is there an associated connection attempt?

**Comment by Unrud** [comment]
> ```
> pip show radicale
> Name: Radicale
> Version: 3.0.0
> ...
> ```

Update to version 3.0.1. See https://github.com/Kozea/Radicale/issues/825#issuecomment-632727428

> Is there an associated connection attempt?

No. Sync token must have the form of a URL.

**Comment by pgnd** [comment]
@Unrud 
upgraded
```
pip show Radicale
	Name: Radicale
	Version: 3.0.1
	Summary: CalDAV and CardDAV Server
	Home-page: https://radicale.org/
	Author: Guillaume Ayoub
	Author-email: guillaume.ayoub@kozea.fr
	License: GNU GPL v3
	Location: /usr/local/src/pyenv/versions/3.8-dev/lib/python3.8/site-packages
	Requires: passlib, python-dateutil, defusedxml, vobject
	Required-by:
```

restarted
```
systemctl restart radicale
```

re-sync'd from Android Dav5x client. still
```
May 23 09:25:45 dev.loc radicale[54106]: Traceback (most recent call last):
May 23 09:25:45 dev.loc radicale[54106]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/storage/multifilesystem/sync.py", line 72, in sync
May 23 09:25:45 dev.loc radicale[54106]:     with open(old_token_path, "rb") as f:
May 23 09:25:45 dev.loc radicale[54106]: FileNotFoundError: [Errno 2] No such file or directory: '/data/db/radicale/collections/collection-root/dev@example.com/3d75...1832/.Radicale.cache/sync-token/4023...ed1f'
May 23 09:25:45 dev.loc radicale[54106]: During handling of the above exception, another exception occurred:
May 23 09:25:45 dev.loc radicale[54106]: Traceback (most recent call last):
May 23 09:25:45 dev.loc radicale[54106]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/app/report.py", line 90, in xml_report
May 23 09:25:45 dev.loc radicale[54106]:     sync_token, names = collection.sync(old_sync_token)
May 23 09:25:45 dev.loc radicale[54106]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/storage/multifilesystem/sync.py", line 85, in sync
May 23 09:25:45 dev.loc radicale[54106]:     raise ValueError("Token not found: %r" % old_token)
May 23 09:25:45 dev.loc radicale[54106]: ValueError: Token not found: 'http://radicale.org/ns/sync/4023...ed1f'
May 23 09:25:45 dev.loc radicale[54106]: [2020-05-23 09:25:45 -0700] [54106/Thread-4] [DEBUG] Response content:
May 23 09:25:45 dev.loc radicale[54106]: <?xml version="1.0"?>
May 23 09:25:45 dev.loc radicale[54106]: <error xmlns="DAV:">
May 23 09:25:45 dev.loc radicale[54106]:   <valid-sync-token />
May 23 09:25:45 dev.loc radicale[54106]: </error>
```

Still an issue? Or need to perhaps delete cache?

**Comment by pgnd** [comment]
fyi, 

deleting the Radicale cache dirs does _not_ appear to make a difference either

errors as above continue to appear

**Comment by Unrud** [comment]
I can't get DAVx5 to issue a sync-collection report.

> Deleting & re-creating the accounts on the phone doesn't seem to make any difference

Unchecking and checking the checkboxes of all calendars and address books in DAVx5 worked for me.

**Comment by pgnd** [comment]
toggled the checkboxes as you decsribed

see this, with no error
```
May 23 10:56:40 dev.loc radicale[60463]: [2020-05-23 10:56:40 -0700] [60463/Thread-2] [DEBUG] Request content:
May 23 10:56:40 dev.loc radicale[60463]: <?xml version="1.0"?>
May 23 10:56:40 dev.loc radicale[60463]: <sync-collection xmlns="DAV:">
May 23 10:56:40 dev.loc radicale[60463]:   <sync-token />
May 23 10:56:40 dev.loc radicale[60463]:   <sync-level>1</sync-level>
May 23 10:56:40 dev.loc radicale[60463]:   <prop>
May 23 10:56:40 dev.loc radicale[60463]:     <getetag />
May 23 10:56:40 dev.loc radicale[60463]:   </prop>
May 23 10:56:40 dev.loc radicale[60463]: </sync-collection>
May 23 10:56:40 dev.loc radicale[60463]: [2020-05-23 10:56:40 -0700] [60463/Thread-2] [DEBUG] Client provided sync token: ''
May 23 10:56:40 dev.loc radicale[60463]: [2020-05-23 10:56:40 -0700] [60463/Thread-2] [DEBUG] Response content:
May 23 10:56:40 dev.loc radicale[60463]: <?xml version="1.0"?>
May 23 10:56:40 dev.loc radicale[60463]: <multistatus xmlns="DAV:">
May 23 10:56:40 dev.loc radicale[60463]:   <sync-token>http://radicale.org/ns/sync/730e...943dc</sync-token>
```

so that looks better.  i'll keep an eye out for any more of those token errors


but NOW, seeing loads of these
```
May 23 10:56:47 dev.loc radicale[60463]: [2020-05-23 10:56:47 -0700] [60463/Thread-3] [ERROR] An exception occurred during request: SSL handshake failed: [Errno 0] Error
May 23 10:56:47 dev.loc radicale[60463]: Traceback (most recent call last):
May 23 10:56:47 dev.loc radicale[60463]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/server.py", line 140, in finish_request_locked
May 23 10:56:47 dev.loc radicale[60463]:     request.do_handshake()
May 23 10:56:47 dev.loc radicale[60463]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/ssl.py", line 1309, in do_handshake
May 23 10:56:47 dev.loc radicale[60463]:     self._sslobj.do_handshake()
May 23 10:56:47 dev.loc radicale[60463]: OSError: [Errno 0] Error
May 23 10:56:47 dev.loc radicale[60463]: The above exception was the direct cause of the following exception:
May 23 10:56:47 dev.loc radicale[60463]: Traceback (most recent call last):
May 23 10:56:47 dev.loc radicale[60463]:   File "/usr/local/pyenv/versions/3.8-dev/lib/python3.8/site-packages/radicale/server.py", line 144, in finish_request_locked
May 23 10:56:47 dev.loc radicale[60463]:     raise RuntimeError("SSL handshake failed: %s" % e) from e
May 23 10:56:47 dev.loc radicale[60463]: RuntimeError: SSL handshake failed: [Errno 0] Error
```

fwiw, i've changed nothing re: certs/ssl here
