### ISSUE TITLE
[v3] Address family not supported by protocol when I have only IPv4, maybe it tries it as IPv6?

### ISSUE THREAD

**Issue by AlphaJack** [Kozea/Radicale#1050]
After updating to 3.0.1 (package in Arch Linux Arm community repo) I can't start Radicale anymore because it says:
```
Failed to start server '[127.0.0.1]:5232': [Errno 97] Address family not supported by protocol
```
In the documentation it is stated
```
# IPv4 syntax: address:port
# IPv6 syntax: [address]:port
# For example: 0.0.0.0:9999, [::]:9999
```
Given the error, is Radicale trying to interpret the only 127.0.0.1 host as IPv6 (see the square brackets) and returning the error because IPv6 is disabled?  

I have tried:
```
# default option
hosts = 127.0.0.1:5232
hosts = 127.0.0.1:5232,  [::]:9999
hosts = 0.0.0.0:5232
hosts = localhost:5232
```

Full log here: 
```
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] Loaded default config
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] Loaded config file '/etc/radicale/config'
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] Skipped missing config file '/.config/radicale/config'
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] Starting Radicale
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] auth type is 'radicale.auth.http_x_remote_user'
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] storage type is 'radicale.storage.multifilesystem'
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] rights type is 'radicale.rights.owner_only'
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] web type is 'radicale.web.internal'
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [INFO] Listening on '[127.0.0.1]:5232'
May 23 21:40:36 hostname radicale[25136]: [2020-05-23 21:40:36 +0200] [25136] [CRITICAL] An exception occurred during server startup: Failed to start server '[localhost]:5232': [Errno 97] Address family not supported by protocol
May 23 21:40:36 hostname radicale[25136]: Traceback (most recent call last):
May 23 21:40:36 hostname radicale[25136]:   File "/usr/lib/python3.8/site-packages/radicale/server.py", line 223, in serve
May 23 21:40:36 hostname radicale[25136]:     server = server_class(configuration, family, address,
May 23 21:40:36 hostname radicale[25136]:   File "/usr/lib/python3.8/site-packages/radicale/server.py", line 68, in __init__
May 23 21:40:36 hostname radicale[25136]:     super().__init__(address, RequestHandlerClass)
May 23 21:40:36 hostname radicale[25136]:   File "/usr/lib/python3.8/socketserver.py", line 448, in __init__
May 23 21:40:36 hostname radicale[25136]:     self.socket = socket.socket(self.address_family,
May 23 21:40:36 hostname radicale[25136]:   File "/usr/lib/python3.8/socket.py", line 231, in __init__
May 23 21:40:36 hostname radicale[25136]:     _socket.socket.__init__(self, family, type, proto, fileno)
May 23 21:40:36 hostname radicale[25136]: OSError: [Errno 97] Address family not supported by protocol
May 23 21:40:36 hostname radicale[25136]: The above exception was the direct cause of the following exception:
May 23 21:40:36 hostname radicale[25136]: Traceback (most recent call last):
May 23 21:40:36 hostname radicale[25136]:   File "/usr/lib/python3.8/site-packages/radicale/__main__.py", line 150, in run
May 23 21:40:36 hostname radicale[25136]:     server.serve(configuration, shutdown_socket_out)
May 23 21:40:36 hostname radicale[25136]:   File "/usr/lib/python3.8/site-packages/radicale/server.py", line 243, in serve
May 23 21:40:36 hostname radicale[25136]:     raise RuntimeError("Failed to start server %r: %s" % (
May 23 21:40:36 hostname radicale[25136]: RuntimeError: Failed to start server '[127.0.0.1]:5232': [Errno 97] Address family not supported by protocol
May 23 21:40:37 hostname systemd[1]: radicale.service: Main process exited, code=exited, status=1/FAILURE
May 23 21:40:37 hostname systemd[1]: radicale.service: Failed with result 'exit-code'.
May 23 21:40:37 hostname systemd[1]: radicale.service: Scheduled restart job, restart counter is at 2.
May 23 21:40:37 hostname systemd[1]: Stopped radicale - A simple CalDAV (calendar) and CardDAV (contact) server.
May 23 21:40:37 hostname systemd[1]: Started radicale - A simple CalDAV (calendar) and CardDAV (contact) server.
```

**Comment by Unrud** [comment]
Should be fixed in release 3.0.2
