### ISSUE TITLE
Radicale 2.1.12 error with crypt 

### ISSUE THREAD

**Issue by llevet** [Kozea/Radicale#1056]
Radicale error : 

2020-05-26 17:26:10,870 - INFO: PROPFIND request for '/llevet/' with depth '0' received from '172.31.31.80' (forwarded by 127.0.0.1) using 'iOS/13.5 (17F75) dataaccessd/1.0'
2020-05-26 17:26:10,871 - DEBUG: Request headers:
{'CONTENT_LENGTH': '819',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'fr-fr',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_BRIEF': 't',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_PREFER': 'return=minimal',
 'HTTP_USER_AGENT': 'iOS/13.5 (17F75) dataaccessd/1.0',
 'HTTP_X_FORWARDED_FOR': '172.31.31.80',
 'HTTP_X_FORWARDED_HOST': 'radicale.xxxxxxxxx.org',
 'HTTP_X_FORWARDED_SERVER': 'radicale.xxxxxxxxx.org',
 'HTTP_X_SCRIPT_NAME': '/radicale',
 'PATH_INFO': '/llevet/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'filenet.xxxxxxxxx.org',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7f24781e50d8>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2020-05-26 17:26:10,871 - DEBUG: Script name overwritten by client: '/radicale'
2020-05-26 17:26:10,871 - DEBUG: Sanitized script name: '/radicale'
2020-05-26 17:26:10,871 - DEBUG: Sanitized path: '/llevet/'
2020-05-26 17:26:10,871 - ERROR: An exception occurred during PROPFIND request on '/llevet/': unsupported operand types(s) or combination of types: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Radicale-2.1.12-py3.6.egg/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/local/lib/python3.6/site-packages/Radicale-2.1.12-py3.6.egg/radicale/__init__.py", line 461, in _handle_request
    password)
  File "/usr/local/lib/python3.6/site-packages/Radicale-2.1.12-py3.6.egg/radicale/auth.py", line 115, in is_authenticated2
    return self.is_authenticated(user, password)
  File "/usr/local/lib/python3.6/site-packages/Radicale-2.1.12-py3.6.egg/radicale/auth.py", line 255, in is_authenticated
    password_ok = self.verify(hash_value, password)
  File "/usr/local/lib/python3.6/site-packages/Radicale-2.1.12-py3.6.egg/radicale/auth.py", line 197, in _crypt
    hash_value)
TypeError: unsupported operand types(s) or combination of types: 'NoneType' and 'str'

**Comment by pbiering** [comment]
closing as related to old version, please reopen in case still happened with latest version
