### ISSUE TITLE
Radicale not create calendar in collection. An exception occurred during MKCALENDAR request

### ISSUE THREAD

**Issue by PetroGolovnya** [Kozea/Radicale#1061]
I install version 2.1.11-8 from Ubuntu 20.04 repo.

Righs file:
# Access rule to domain shared calendars
[domain-shared-calendars]
user = ^(.+)@(.+)$
collection = {1}/.+$
permission = rw

# Read/Write permission for calendar owners
[owners-access]
user = .+
collection = %(login)s(/.*)?
permission = rw

When adding event in calendar i see error:

2020-06-01 06:12:11,670 - [7fd1a240d700] INFO: MKCALENDAR request for '/user1@air6x.com/Table' received from '127.0.0.1' (forwarded by 127.0.0.1) using 'Mozilla/5.0'
2020-06-01 06:12:11,671 - [7fd1a240d700] DEBUG: Request headers:
{'CONTENT_LENGTH': '0',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': '127.0.0.1:5232',
 'HTTP_USER_AGENT': 'Mozilla/5.0',
 'HTTP_X_FORWARDED_FOR': '127.0.0.1',
 'HTTP_X_SCRIPT_NAME': '/radicale',
 'PATH_INFO': '/user1@air6x.com/Table',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'MKCALENDAR',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7fd1a257e790>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2020-06-01 06:12:11,671 - [7fd1a240d700] DEBUG: Script name overwritten by client: '/radicale'
2020-06-01 06:12:11,671 - [7fd1a240d700] DEBUG: Sanitized script name: '/radicale'
2020-06-01 06:12:11,671 - [7fd1a240d700] DEBUG: Sanitized path: '/user1@air6x.com/Table'
2020-06-01 06:12:11,672 - [7fd1a240d700] DEBUG: Rule '':'user1@air6x.com/Table' doesn't match '^(.+)@(.+)$':'{1}/.+$' from section 'domain-shared-calendars'
2020-06-01 06:12:11,673 - [7fd1a240d700] DEBUG: Rule '':'user1@air6x.com/Table' doesn't match '.+':'(/.*)?' from section 'owners-access'
2020-06-01 06:12:11,673 - [7fd1a240d700] DEBUG: Rule '':'user1@air6x.com/Table' doesn't match 'a5823208148d59966b278acafdae0e20':'user2@air6x.com/My Calendar' from section 'token-user2@air6x.com/My Calendar-access'
2020-06-01 06:12:11,673 - [7fd1a240d700] DEBUG: Rule '':'user1@air6x.com/Table' doesn't match '610abdb884da4d2f7c9d906e79184873':'user1@air6x.com/Calendar' from section 'token-user1@air6x.com/Calendar-access'
2020-06-01 06:12:11,673 - [7fd1a240d700] INFO: Rights: '':'user1@air6x.com/Table' doesn't match any section
2020-06-01 06:12:11,673 - [7fd1a240d700] INFO: Access to '/user1@air6x.com/Table' denied for anonymous user
2020-06-01 06:12:11,673 - [7fd1a240d700] DEBUG: Asking client for authentication
2020-06-01 06:12:11,674 - [7fd1a240d700] DEBUG: Response content:
Access to the requested resource forbidden.
2020-06-01 06:12:11,674 - [7fd1a240d700] INFO: MKCALENDAR response status for '/user1@air6x.com/Table' in 0.004 seconds: 401 Unauthorized
2020-06-01 06:12:11,698 - [7fd1a240d700] INFO: MKCALENDAR request for '/user1@air6x.com/Table' received from '127.0.0.1' (forwarded by 127.0.0.1) using 'Mozilla/5.0'
2020-06-01 06:12:11,699 - [7fd1a240d700] DEBUG: Request headers:
{'CONTENT_LENGTH': '0',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': '127.0.0.1:5232',
 'HTTP_USER_AGENT': 'Mozilla/5.0',
 'HTTP_X_FORWARDED_FOR': '127.0.0.1',
 'HTTP_X_SCRIPT_NAME': '/radicale',
 'PATH_INFO': '/user1@air6x.com/Table',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'MKCALENDAR',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7fd1a257e820>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2020-06-01 06:12:11,699 - [7fd1a240d700] DEBUG: Script name overwritten by client: '/radicale'
2020-06-01 06:12:11,699 - [7fd1a240d700] DEBUG: Sanitized script name: '/radicale'
2020-06-01 06:12:11,699 - [7fd1a240d700] DEBUG: Sanitized path: '/user1@air6x.com/Table'
2020-06-01 06:12:11,765 - [7fd1a240d700] INFO: Successful login: 'user1@air6x.com'
2020-06-01 06:12:11,766 - [7fd1a240d700] DEBUG: Rule 'user1@air6x.com':'user1@air6x.com' doesn't match '^(.+)@(.+)$':'{1}/.+$' from section 'domain-shared-calendars'
2020-06-01 06:12:11,766 - [7fd1a240d700] DEBUG: Rule 'user1@air6x.com':'user1@air6x.com' matches '.+':'user1@air6x\\.com(/.*)?' from section 'owners-access'
2020-06-01 06:12:11,768 - [7fd1a240d700] DEBUG: Rule 'user1@air6x.com':'user1@air6x.com/Table' doesn't match '^(.+)@(.+)$':'{1}/.+$' from section 'domain-shared-calendars'
2020-06-01 06:12:11,768 - [7fd1a240d700] DEBUG: Rule 'user1@air6x.com':'user1@air6x.com/Table' matches '.+':'user1@air6x\\.com(/.*)?' from section 'owners-access'
2020-06-01 06:12:11,770 - [7fd1a240d700] ERROR: An exception occurred during MKCALENDAR request on '/user1@air6x.com/Table': __init__() got an unexpected keyword argument 'filesystem_path'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 504, in _handle_request
    status, headers, answer = function(
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 681, in do_MKCALENDAR
    self.Collection.create_collection(path, props=props)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 985, in create_collection
    self = cls(sane_path, filesystem_path=tmp_filesystem_path)
TypeError: __init__() got an unexpected keyword argument 'filesystem_path'
2020-06-01 06:12:12,012 - [7fd1a240d700] INFO: REPORT request for '/user1@air6x.com/Table/' with depth '1' received from '127.0.0.1' (forwarded by 127.0.0.1) using 'Mozilla/5.0'

**Comment by Unrud** [comment]
Are you using an incompatible storage plugin? Please post your config file.

**Comment by PetroGolovnya** [comment]
[storage]
type = radicale_storage_by_index
filesystem_folder = /srv/radicale/collections

radicale_storage_by_index plugin is broken?

**Comment by Unrud** [comment]
> radicale_storage_by_index plugin is broken?

I don't know this plugin but from the log it looks like it's not compatible with Radicale 3.x.x.

**Comment by PetroGolovnya** [comment]
I know. And not compatible with Radicale 2.1.x.

**Comment by tonioo** [comment]
@Unrud Do you think such a plugin improves performance or not?

**Comment by pbiering** [comment]
closed as old version and incompatible storage plugin used
