### ISSUE TITLE
Double slash in python url 

### ISSUE THREAD

**Issue by holian7** [Kozea/Radicale#1070]
Masters,

 I try to move/reinstall my radicale server to a new server.
- new py installed
- radicale installed
- config file copied

When i try to run it from windows command line: py -m radicale --debug - config "C:\radicale\config" i get error because PY change the url with double slashed. ("C:\\radicale\\config") and in this way get file not found error.

Any idea how to bypass this kind of behavior of PY?

Best regards

**Comment by return42** [comment]
I guess it is the shell (cmd) dropping the first backslash. Try to add one more backslash ...

**Comment by holian7** [comment]
i tried to add one more backslash but the result is the same...

```

C:\Users\Administrator>py -m radicale --debug --config "c:\\radicale\\radicalessl\\config"
[2020-06-10 11:29:31 +0200] [7960] [CRITICAL] Invalid configuration: Failed to load config file 'c:\\radicale\\radicalessl\\config': No such file: 'c:\\radicale\\radicalessl\\config'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\radicale\config.py", line 276, in load
    raise RuntimeError("No such file: %r" % path)
RuntimeError: No such file: 'c:\\radicale\\radicalessl\\config'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\radicale\__main__.py", line 109, in run
    configuration = config.load(config.parse_compound_paths(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\radicale\config.py", line 281, in load
    raise RuntimeError(
RuntimeError: Failed to load config file 'c:\\radicale\\radicalessl\\config': No such file: 'c:\\radicale\\radicalessl\\config'

C:\Users\Administrator>
```

**Comment by holian7** [comment]
Any other ideas? I really apperitiate...

**Comment by return42** [comment]
I am sorry, not from mine .. except there is a typo in the path name?

**Comment by holian7** [comment]
I can't deal with this problem.....i pullin out my hair....
Anybody use radicale on windows server?

**Comment by pbiering** [comment]
solved now?

**Comment by pbiering** [comment]
closing as no reaction
