### ISSUE TITLE
 reverse-proxied v3.0.5 access fails with generic: "RuntimeError: SSL handshake failed: [Errno 0] Error" ?

### ISSUE THREAD

**Issue by pgnd** [Kozea/Radicale#1100]
on a new instance of
```
	grep PRETTY /etc/os-release
		PRETTY_NAME="Fedora 32 (Server Edition)"
```

with 
```
	python -V
		Python 3.8.5
	nginx -v
		nginx version: nginx/1.19.2 (local build)
```

i've installed
```
	pip install --upgrade radicale[bcrypt]
	pip install --upgrade \
	 passlib \
	 bcrypt \
	 python-dateutil \
	 defusedxml \
	 vobject
	pip show Radicale
		Name: Radicale
		Version: 3.0.5
		Summary: CalDAV and CardDAV Server
		Home-page: https://radicale.org/
		Author: Guillaume Ayoub
		Author-email: guillaume.ayoub@kozea.fr
		License: GNU GPL v3
		Location: /usr/local/lib64/python3.8/site-packages
		Requires: python-dateutil, passlib, defusedxml, vobject
		Required-by:
```

i've created a users file, with bcrypt-ed password
```	
	this_user=testuser@example.net
	this_pass='XXXXXX!@^%XXXXXX'
	this_passfile=/usr/local/etc/radicale/users

	> $this_passfile
	chmod 644 $this_passfile

	this_cost="14"
	this_hash=$( php -r "echo password_hash('$this_pass', PASSWORD_BCRYPT, ['cost' => $this_cost]) . PHP_EOL;" )
	echo "$this_user:$this_hash" >> $this_passfile
```

and verified,
```
	htpasswd -vb $this_passfile $this_user "$this_pass"
		Password for user testuser@example.net correct.
```	

with radicale config including,
```
	[auth]
	type = htpasswd
	htpasswd_filename = /usr/local/etc/radicale/users
	htpasswd_encryption = bcrypt
	realm = MYREALM - Password Required
```
I can _directly_ access & login to the radicale backend @

	https://radicale.example.com:22222

it appears/works as expected.

next,

my nginx server serves as a front-end proxy to numerous backend apps.switching for use with radicale, changing
```
-	type = htpasswd
+	type = http_x_remote_user
```

and accessing the nginx front-end proxy to radicale @
```
	https://front.example.com:11111/dav
```

where nginx f-r poxy config includes
```
	location /dav/ {

	    proxy_pass https://radicale.example.com:22222/;
	    proxy_ssl_name radicale.example.com;
	    proxy_set_header  X-Script-Name /dav;

	    proxy_ssl_verify off;
	    proxy_ssl_verify_depth 2;

	    proxy_ssl_certificate         "/srv/ssl/radicale.client.EC.crt
	    proxy_ssl_certificate_key     "/srv/ssl/radicale.client.EC.key
	    proxy_ssl_trusted_certificate "/src/ssl/myCA.crt

	    auth_basic "DAV - Password Required";
	    auth_basic_user_file /srv/sec/auth/passwd.radicale;

	    access_log  /var/log/nginx/front.access.log upstreamlog;
	    error_log   /var/log/nginx/front.error.log info;

	    include includes/nginx-reverse-proxy.inc;
	}
```

in browser I get only as far as
```
	Loading
	Please wait...
```

and in logs, I see this exception,
```
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-39] [ERROR] An exception occurred during request: SSL handshake failed: [Errno 0] Error
	Sep 10 11:12:40 srv0237 radicale[8879]: Traceback (most recent call last):
	Sep 10 11:12:40 srv0237 radicale[8879]:  File "/usr/local/lib64/python3.8/site-packages/radicale/server.py", line 140, in finish_request_locked
	Sep 10 11:12:40 srv0237 radicale[8879]:    request.do_handshake()
	Sep 10 11:12:40 srv0237 radicale[8879]:  File "/usr/lib64/python3.8/ssl.py", line 1309, in do_handshake
	Sep 10 11:12:40 srv0237 radicale[8879]:    self._sslobj.do_handshake()
	Sep 10 11:12:40 srv0237 radicale[8879]: OSError: [Errno 0] Error
	Sep 10 11:12:40 srv0237 radicale[8879]: The above exception was the direct cause of the following exception:
	Sep 10 11:12:40 srv0237 radicale[8879]: Traceback (most recent call last):
	Sep 10 11:12:40 srv0237 radicale[8879]:  File "/usr/local/lib64/python3.8/site-packages/radicale/server.py", line 144, in finish_request_locked
	Sep 10 11:12:40 srv0237 radicale[8879]:    raise RuntimeError("SSL handshake failed: %s" % e) from e
	Sep 10 11:12:40 srv0237 radicale[8879]: RuntimeError: SSL handshake failed: [Errno 0] Error
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-40] [INFO] GET request for '/.web/' received from '10.0.1.117' (forwarded by 10.0.1.100) using 'Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0'
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-40] [DEBUG] Request headers:
	Sep 10 11:12:40 srv0237 radicale[8879]: {'CONTENT_LENGTH': '',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'CONTENT_TYPE': 'application/json',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'GATEWAY_INTERFACE': 'CGI/1.1',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_ACCEPT': 'application/json',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_AUTHORIZATION': 'Basic **masked**',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_CACHE_CONTROL': 'max-age=0',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_CONNECTION': 'close',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_DNT': '1',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_HOST': 'radicale.example.com:22222',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_HTTPS': 'on',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 '
	Sep 10 11:12:40 srv0237 radicale[8879]:                    'Firefox/80.0',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_FORWARDED_FOR': '10.0.1.117',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_FORWARDED_HOST': 'front.example.com:11111',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_FORWARDED_PROTO': 'https',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_FORWARDED_SSL': 'on',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_FORWARDED_URI': '/dav/.web/',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_NGINX_PROXY': 'true',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_REAL_IP': '10.0.1.117',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_REMOTE_USER': 'testuser@example.net',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_SCRIPT_NAME': '/dav',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_SSL_ISSUER': 'emailAddress=ssl@example.com,CN=myCA_INT,OU=myCA,O=example.com,ST=NY,C=US',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'HTTP_X_SSL_SUBJECT': 'emailAddress=ssl@example.com,CN=devtop.example.com,OU=myCA,O=example.com,L=NYC,ST=NY,C=US',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'PATH_INFO': '/.web/',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'QUERY_STRING': '',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'REMOTE_ADDR': '10.0.1.100',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'REMOTE_CERTIFICATE': {'issuer': ((('countryName', 'US'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                   (('stateOrProvinceName', 'NY'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                   (('organizationName',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                     'example.com'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                   (('organizationalUnitName',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                     'myCA'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                   (('commonName',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                     'myCA_INT'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                   (('emailAddress',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                     'ssl@example.com'),)),
	Sep 10 11:12:40 srv0237 radicale[8879]:                        'notAfter': 'Jun 30 16:55:34 2029 GMT',
	Sep 10 11:12:40 srv0237 radicale[8879]:                        'notBefore': 'Jul  3 16:55:34 2019 GMT',
	Sep 10 11:12:40 srv0237 radicale[8879]:                        'serialNumber': '1072',
	Sep 10 11:12:40 srv0237 radicale[8879]:                        'subject': ((('countryName', 'US'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                    (('stateOrProvinceName', 'NY'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                    (('localityName', 'NYC'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                    (('organizationName',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                      'example.com'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                    (('organizationalUnitName',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                      'myCA'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                    (('commonName',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                      'radicale.example.com'),),
	Sep 10 11:12:40 srv0237 radicale[8879]:                                    (('emailAddress',
	Sep 10 11:12:40 srv0237 radicale[8879]:                                      'ssl@example.com'),)),
	Sep 10 11:12:40 srv0237 radicale[8879]:                        'version': 3},
	Sep 10 11:12:40 srv0237 radicale[8879]: 'REMOTE_HOST': '',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'REQUEST_METHOD': 'GET',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'SCRIPT_NAME': '',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'SERVER_NAME': 'srv0237.example.com',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'SERVER_PORT': '22222',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'SERVER_PROTOCOL': 'HTTP/1.1',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'SERVER_SOFTWARE': 'WSGIServer/0.2',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.input': <_io.BufferedReader name=8>,
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.multiprocess': False,
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.multithread': True,
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.run_once': False,
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.url_scheme': 'http',
	Sep 10 11:12:40 srv0237 radicale[8879]: 'wsgi.version': (1, 0)}
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-40] [DEBUG] Script name overwritten by client: '/dav'
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-40] [DEBUG] Sanitized script name: '/dav'
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-40] [DEBUG] Sanitized path: '/.web/'
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-40] [INFO] Successful login: 'testuser@example.net'
	Sep 10 11:12:40 srv0237 radicale[8879]: [2020-09-10 11:12:40 -0700] [8879/Thread-40] [INFO] GET response status for '/.web/' in 0.009 seconds: 200 OK
	Sep 10 11:12:45 srv0237 radicale[8879]: [2020-09-10 11:12:45 -0700] [8879/Thread-41] [ERROR] An exception occurred during request: SSL handshake failed: [Errno 0] Error
	Sep 10 11:12:45 srv0237 radicale[8879]: Traceback (most recent call last):
	Sep 10 11:12:45 srv0237 radicale[8879]:  File "/usr/local/lib64/python3.8/site-packages/radicale/server.py", line 140, in finish_request_locked
	Sep 10 11:12:45 srv0237 radicale[8879]:    request.do_handshake()
	Sep 10 11:12:45 srv0237 radicale[8879]:  File "/usr/lib64/python3.8/ssl.py", line 1309, in do_handshake
	Sep 10 11:12:45 srv0237 radicale[8879]:    self._sslobj.do_handshake()
	Sep 10 11:12:45 srv0237 radicale[8879]: OSError: [Errno 0] Error
	Sep 10 11:12:45 srv0237 radicale[8879]: The above exception was the direct cause of the following exception:
	Sep 10 11:12:45 srv0237 radicale[8879]: Traceback (most recent call last):
	Sep 10 11:12:45 srv0237 radicale[8879]:  File "/usr/local/lib64/python3.8/site-packages/radicale/server.py", line 144, in finish_request_locked
	Sep 10 11:12:45 srv0237 radicale[8879]:    raise RuntimeError("SSL handshake failed: %s" % e) from e
	Sep 10 11:12:45 srv0237 radicale[8879]: RuntimeError: SSL handshake failed: [Errno 0] Error
	Sep 10 11:12:45 srv0237 radicale[8879]: [2020-09-10 11:12:45 -0700] [8879/Thread-42] [ERROR] An exception occurred during request: SSL handshake failed: [Errno 0] Error
	Sep 10 11:12:45 srv0237 radicale[8879]: Traceback (most recent call last):
	Sep 10 11:12:45 srv0237 radicale[8879]:  File "/usr/local/lib64/python3.8/site-packages/radicale/server.py", line 140, in finish_request_locked
	Sep 10 11:12:45 srv0237 radicale[8879]:    request.do_handshake()
	Sep 10 11:12:45 srv0237 radicale[8879]:  File "/usr/lib64/python3.8/ssl.py", line 1309, in do_handshake
	Sep 10 11:12:45 srv0237 radicale[8879]:    self._sslobj.do_handshake()
	Sep 10 11:12:45 srv0237 radicale[8879]: OSError: [Errno 0] Error
	Sep 10 11:12:45 srv0237 radicale[8879]: The above exception was the direct cause of the following exception:
	Sep 10 11:12:45 srv0237 radicale[8879]: Traceback (most recent call last):
	Sep 10 11:12:45 srv0237 radicale[8879]:  File "/usr/local/lib64/python3.8/site-packages/radicale/server.py", line 144, in finish_request_locked
	Sep 10 11:12:45 srv0237 radicale[8879]:    raise RuntimeError("SSL handshake failed: %s" % e) from e
	Sep 10 11:12:45 srv0237 radicale[8879]: RuntimeError: SSL handshake failed: [Errno 0] Error
```

The error
```
RuntimeError: SSL handshake failed: [Errno 0] Error
```

is a bit generic.

Any clues as to the problem, or hints as to how/what to troubleshoot further?

**Comment by pgnd** [comment]
addittionally installing the following SSL-related pkgs

```
 python3-m2crypto
 python3-pyOpenSSL
 python3-ndg_httpsclient
 python3-service-identity
```

solves the problem.  not sure which, specifically.

didn't notice any of those as prereqs in the docs; if there, missed it.

**Comment by Unrud** [comment]
> didn't notice any of those as prereqs in the docs; if there, missed it.

This looks like a packaging problem in Fedora. We just use Python's built-in **ssl** package.
