### ISSUE TITLE
Cannot open transformed calender event after migrating from 0.10 to radical 3.1

### ISSUE THREAD

**Issue by svrnwnsch** [Kozea/Radicale#1116]
I migrated the calender as described in the documentation. With the lateste version I get now the following error when opening my calender via webrowser in: https://192.168.178.43:5232/user/user.ics/
````
[2020-10-18 05:06:14 +0200] [10399/Thread-7] [ERROR] An exception occurred during GET request on '/user/user.ics/': Failed to load item '20150416T070452Z-21121_d0ca269016d4f6d3.ics' in 'user/user.ics': Failed to serialize item None from 'user/user.ics': 'VEVENT components cannot contain more than 1 UID'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/radicale/item/__init__.py", line 337, in serialize
    self._text = self.vobject_item.serialize()
  File "/home/pi/.local/lib/python3.7/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/pi/.local/lib/python3.7/site-packages/vobject/icalendar.py", line 1001, in serialize
    cls.validate(obj, raiseException=True)
  File "/home/pi/.local/lib/python3.7/site-packages/vobject/behavior.py", line 85, in validate
    if not child.validate(raiseException, complainUnrecognized):
  File "/home/pi/.local/lib/python3.7/site-packages/vobject/base.py", line 124, in validate
    return self.behavior.validate(self, *args, **kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/vobject/icalendar.py", line 1170, in validate
    return super(VEvent, cls).validate(obj, raiseException, *args)
  File "/home/pi/.local/lib/python3.7/site-packages/vobject/behavior.py", line 98, in validate
    raise base.ValidateError(m.format(cls.name, val[1], key))
vobject.base.ValidateError: 'VEVENT components cannot contain more than 1 UID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/radicale/storage/multifilesystem/get.py", line 95, in _get
    href, temp_item, input_hash)
  File "/home/pi/.local/lib/python3.7/site-packages/radicale/storage/multifilesystem/cache.py", line 73, in _store_item_cache
    content = self._item_cache_content(item, cache_hash)
  File "/home/pi/.local/lib/python3.7/site-packages/radicale/storage/multifilesystem/cache.py", line 64, in _item_cache_content
    text = item.serialize()
  File "/home/pi/.local/lib/python3.7/site-packages/radicale/item/__init__.py", line 341, in serialize
    e)) from e
RuntimeError: Failed to serialize item None from 'user/user.ics': 'VEVENT components cannot contain more than 1 UID'
````

How can I solve this do i need to manually edit the 20150416T070452Z-21121_d0ca269016d4f6d3.ics item?

**Comment by svrnwnsch** [comment]
So the problem was that I had in my old calender entries which had calendar entries the `UID` field multiple times (all with the same value). I looked for them in my .ics file using this python script and fixing them by hand.

```python3
with open("~/calendar.ics") as f:
    i = 0
    for line in f:
        if line.startswith("BEGIN:VEVENT"):
            i += 1
        elif line.startswith("UID"):
            i -=1
        if i<0 or i>1:
            print(i, line)
            i +=1
```

And then I simply started radicale 3 and used the upload via webinterface to submit my old calendar.ics file. I found this easier then running the radical migration script.
The upload just took like 30 minutes of processing for my quiet big 600kb ics file.

Maybe you could add some checks/migration when uploading an ics file to find entries which have duplicated entries of UID fields but with the same value.
