### ISSUE TITLE
Failed to load item 'uuid.ics' in 'x.ics': unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'

### ISSUE THREAD

**Issue by allo-** [Kozea/Radicale#1120]
I get the error:

```
[2020-11-10 22:39:56 +0100] [27023/Thread-12] [ERROR] An exception occurred during PUT request on '/xxx.ics/uuid.ics': Failed to load item 'uuid.ics' in 'xxx.ics': unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
Traceback (most recent call last):
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/storage/multifilesystem/get.py", line 95, in _get
    href, temp_item, input_hash)
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/storage/multifilesystem/cache.py", line 73, in _store_item_cache
    content = self._item_cache_content(item, cache_hash)
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/storage/multifilesystem/cache.py", line 68, in _item_cache_content
    item.component_name, *item.time_range)
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/item/__init__.py", line 384, in time_range
    find_tag_and_time_range(self.vobject_item))
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/item/__init__.py", line 262, in find_tag_and_time_range
    radicale_filter.visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/item/filter.py", line 245, in visit_time_ranges
    original_duration = (dtend - dtstart).total_seconds()
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/app/__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/app/__init__.py", line 277, in _handle_request
    environ, base_prefix, path, user)
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/app/put.py", line 203, in do_PUT
    not item and parent_item.has_uid(prepared_item.uid)):
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/storage/__init__.py", line 147, in has_uid
    for item in self.get_all():
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/storage/multifilesystem/get.py", line 135, in <genexpr>
    return (self._get(href, verify_href=False) for href in self._list())
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/storage/multifilesystem/get.py", line 98, in _get
    (href, self.path, e)) from e
RuntimeError: Failed to load item 'uuid.ics' in 'xxx.ics': unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
```

with radicale 3.0.6.

Looking into the file, I suspect the problem could be the the recurrence rules like this (because of the negative sign):

```
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
```

But I am not sure. I am happy for any pointer how to debug the issue.

**Comment by allo-** [comment]
I traced it down further to

```
  File "/home/radicale/venv/lib/python3.7/site-packages/radicale/xmlutils.py", line 352, in _visit_time_ranges
    original_duration = (dtend - dtstart).total_seconds()
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
```

**Comment by allo-** [comment]
I am trying the workaround

```
 349             dtend = getattr(child, "dtend", None)
 350             if dtend is not None:
 351                 dtend = dtend.value
 352                 if not isinstance(dtstart, datetime):
 353                     dtstart = _date_to_datetime(dtstart)
 354                 if not isinstance(dtend, datetime):
 355                     dtend = _date_to_datetime(dtend)
 356                 original_duration = (dtend - dtstart).total_seconds()
 357                 dtend = _date_to_datetime(dtend)
```

I hope I won't kill my data with it. (I have backups)

**Comment by allo-** [comment]
For 3.x the same in `filter.py`

```
242             dtend = getattr(child, "dtend", None)
243             if dtend is not None:
244                 dtend = dtend.value
245                 if not isinstance(dtstart, datetime):
246                     dtstart = date_to_datetime(dtstart)
247                 if not isinstance(dtend, datetime):
248                     dtend = date_to_datetime(dtend)
249                 original_duration = (dtend - dtstart).total_seconds()
250                 dtend = date_to_datetime(dtend)
```

**Comment by pbiering** [comment]
Is this still happen with latest 3.1.x?

**Comment by pbiering** [comment]
no response, please reopen if reproducable with latest version
