### ISSUE TITLE
filtering for Categories property throws exception

### ISSUE THREAD

**Issue by lkopyt** [Kozea/Radicale#1125]
Hi,

i installed Radicale 3.0.6 to setup a calendar for maintenance events in my work environment.
querying the server for 'maintenance' events with prop-filter returns exception like this:

`[2020-12-16 17:00:27 +0100] [28940/Thread-27] [ERROR] An exception occurred during REPORT request on '/user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c/': Failed to filter item 'f33a3f80dfbbe46ce8b4ae54a1fc1ce95ba5f47b.ics' from 'user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c': 'list' object has no attribute 'lower'`

Categories property is defined in iCalendar RFC as comma-separated text.
Radicale seems to treat it as a list ? any bug or I am supposed to prepare a filter in some other way than text-match as below?

query:
```
curl -u user1 -X REPORT 'http://10.88.0.65:5232/user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c/' --data \
'<?xml version="1.0" encoding="utf-8" ?>
   <C:calendar-query xmlns:D="DAV:"
                 xmlns:C="urn:ietf:params:xml:ns:caldav">
     <D:prop>
       <D:getetag/>
       <C:calendar-data/>
     </D:prop>
     <C:filter>
       <C:comp-filter name="VCALENDAR">
         <C:comp-filter name="VEVENT">
           <C:prop-filter name="CATEGORIES">
            <C:text-match collation="i;ascii-casemap">maintenance</C:text-match>
           </C:prop-filter>
         </C:comp-filter>
       </C:comp-filter>
     </C:filter>
   </C:calendar-query>'
```

icalendar event stored in Radicale:
```
# pwd
/var/lib/radicale/collections/collection-root/user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c
# cat f33a3f80dfbbe46ce8b4ae54a1fc1ce95ba5f47b.ics
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
BEGIN:VEVENT
UID:f33a3f80dfbbe46ce8b4ae54a1fc1ce95ba5f47b
DTSTART;VALUE=DATE:20201216
DTEND;VALUE=DATE:20201217
CATEGORIES:maintenance
CLASS:PUBLIC
CREATED:20201215T160406Z
DTSTAMP:20201215T145407Z
LAST-MODIFIED:20201215T161021Z
LOCATION:doh lab
SEQUENCE:3
SUMMARY:maintenance testing
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

**Comment by lkopyt** [comment]
adding debug logs:


```
[2020-12-17 13:42:45 +0100] [27894/Thread-1] [DEBUG] Sanitized script name: ''
[2020-12-17 13:42:45 +0100] [27894/Thread-1] [DEBUG] Sanitized path: '/user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c/'
[2020-12-17 13:42:45 +0100] [27894/Thread-1] [INFO] Successful login: 'user1'
[2020-12-17 13:42:45 +0100] [27894/Thread-1] [DEBUG] Request content:
<?xml version="1.0"?>
<C:calendar-query xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <prop>
    <getetag />
    <C:calendar-data />
  </prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:prop-filter name="CATEGORIES">
          <C:text-match collation="i;ascii-casemap">maintenance</C:text-match>
        </C:prop-filter>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>

[2020-12-17 13:42:45 +0100] [27894/Thread-1] [ERROR] An exception occurred during REPORT request on '/user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c/': Failed to filter item 'f33a3f80dfbbe46ce8b4ae54a1fc1ce95ba5f47b.ics' from 'user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c': 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/report.py", line 193, in xml_report
    if not all(match(item, filter_) for filter_ in filters):
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/report.py", line 193, in <genexpr>
    if not all(match(item, filter_) for filter_ in filters):
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/report.py", line 168, in match
    return radicale_filter.comp_match(item, filter_[0])
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 100, in comp_match
    if not comp_match(item, child, level=level + 1):
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 94, in comp_match
    for comp in components):
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 94, in <genexpr>
    for comp in components):
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 129, in prop_match
    if not text_match(vobject_item, child, name, ns):
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 450, in text_match
    condition = any(match(child.value) for child in children)
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 450, in <genexpr>
    condition = any(match(child.value) for child in children)
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 433, in match
    value = value.lower()
AttributeError: 'list' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/__init__.py", line 277, in _handle_request
    environ, base_prefix, path, user)
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/report.py", line 288, in do_REPORT
    lock_stack.close)
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/report.py", line 200, in xml_report
    (item.href, collection.path, e)) from e
RuntimeError: Failed to filter item 'f33a3f80dfbbe46ce8b4ae54a1fc1ce95ba5f47b.ics' from 'user1/438b326a-ef91-09d9-3ff4-e7d6c794b12c': 'list' object has no attribute 'lower'

```

**Comment by tobixen** [comment]
I'm currently implementing support for category search in my caldav library, and I observe the same problem as above.

```
radicale: INFO: Starting Radicale
(...)
radicale: INFO: REPORT response status for '/user1/pythoncaldav-test/' with depth '1' in 0.004 seconds: 207 Multi-Status
urllib3.connectionpool: DEBUG: http://localhost:5232 "REPORT /user1/pythoncaldav-test/ HTTP/1.1" 207 460
urllib3.connectionpool: DEBUG: Resetting dropped connection: localhost
radicale: INFO: REPORT request for '/user1/pythoncaldav-test/' with depth '1' received from ::1 using 'Mozilla/5.0'
radicale: DEBUG: Request headers:
{'CONTENT_LENGTH': '386',
 'CONTENT_TYPE': 'application/xml; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml, text/calendar',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'Mozilla/5.0',
 'PATH_INFO': '/user1/pythoncaldav-test/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '::1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'REPORT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'ip6-localhost',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
radicale: DEBUG: Base prefix (from SCRIPT_NAME): ''
radicale: DEBUG: Sanitized path: '/user1/pythoncaldav-test/'
radicale: INFO: Successful login: 'user1'
radicale: DEBUG: Request content:
<?xml version="1.0"?>
<C:calendar-query xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <prop>
    <C:calendar-data />
  </prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:prop-filter name="CATEGORIES">
          <C:text-match collation="i;octet">PERSONAL</C:text-match>
        </C:prop-filter>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>

radicale: ERROR: An exception occurred during REPORT request on '/user1/pythoncaldav-test/': Failed to filter item '19970901T130000Z-123403@example.com.ics' from 'user1/pythoncaldav-test': 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/radicale/app/report.py", line 128, in xml_report
    if not all(test_filter(collection_tag, item, filter_)
  File "/usr/lib/python3.10/site-packages/radicale/app/report.py", line 128, in <genexpr>
    if not all(test_filter(collection_tag, item, filter_)
  File "/usr/lib/python3.10/site-packages/radicale/app/report.py", line 251, in test_filter
    return radicale_filter.comp_match(item, filter_[0])
  File "/usr/lib/python3.10/site-packages/radicale/item/filter.py", line 105, in comp_match
    if not comp_match(item, child, level=level + 1):
  File "/usr/lib/python3.10/site-packages/radicale/item/filter.py", line 98, in comp_match
    if not any(prop_match(comp, child, "C")
  File "/usr/lib/python3.10/site-packages/radicale/item/filter.py", line 98, in <genexpr>
    if not any(prop_match(comp, child, "C")
  File "/usr/lib/python3.10/site-packages/radicale/item/filter.py", line 135, in prop_match
    if not text_match(vobject_item, child, name, ns):
  File "/usr/lib/python3.10/site-packages/radicale/item/filter.py", line 471, in text_match
    condition = any(match(child.value) for child in children)
  File "/usr/lib/python3.10/site-packages/radicale/item/filter.py", line 471, in <genexpr>
    condition = any(match(child.value) for child in children)
  File "/usr/lib/python3.10/site-packages/radicale/item/filter.py", line 454, in match
    value = value.lower()
AttributeError: 'list' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/radicale/app/__init__.py", line 105, in __call__
    status_text, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.10/site-packages/radicale/app/__init__.py", line 287, in _handle_request
    status, headers, answer = function(
  File "/usr/lib/python3.10/site-packages/radicale/app/report.py", line 299, in do_REPORT
    status, xml_answer = xml_report(
  File "/usr/lib/python3.10/site-packages/radicale/app/report.py", line 135, in xml_report
    raise RuntimeError("Failed to filter item %r from %r: %s" %
RuntimeError: Failed to filter item '19970901T130000Z-123403@example.com.ics' from 'user1/pythoncaldav-test': 'list' object has no attribute 'lower'
urllib3.connectionpool: DEBUG: http://localhost:5232 "REPORT /user1/pythoncaldav-test/ HTTP/1.1" 500 59
radicale: INFO: Stopping Radicale
```

I haven't gotten around to test it yet, but I expect it will be the same issue with other fields supporting multiple values.

**Comment by tobixen** [comment]
Steps to reproduce:

```bash
git clone git@github.com:python-caldav/caldav.git
cd caldav
git checkout wip-search
nosetests3 tests.test_caldav:TestLocalRadicale.testSearchEvent
```

**Comment by tobixen** [comment]
This is probably a silly stupid way to solve it, but works for me:

```
diff --git a/radicale/item/filter.py b/radicale/item/filter.py
index 587dc36..8f8ef3e 100644
--- a/radicale/item/filter.py
+++ b/radicale/item/filter.py
@@ -450,7 +450,9 @@ def text_match(vobject_item: vobject.base.Component,
     if ns == "CR":
         match_type = filter_.get("match-type", match_type)
 
-    def match(value: str) -> bool:
+    def match(value) -> bool:
+        if not hasattr(value, 'lower'):
+            return any([match(x) for x in value])
         value = value.lower()
         if match_type == "equals":
             return value == text
```

**Comment by tobixen** [comment]
I did remember right, that I have reported this before.  Now I managed to duplicate it in #1280.
