### ISSUE TITLE
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by anobar** [Kozea/Radicale#1166]
Running a radicale server on Debian 10/buster for years. Since a few weeks I cannot sync cal and cards anymore to Thunderbird and Android (DAVX5, aCalendar). radicale version 2.1.11. Error message in log looks like this:

[2021-05-29 00:06:09 +0200] [11051/Thread-7] [ERROR] An exception occurred during GET request on '/NN/NN.ics/': Failed to load item 'bf872e2a-4f80-8efe-33ab-4eb49f951a77.ics' in 'NN/NN.ics': 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Reinstalled new radicale server version 3 - same issue.

Any idea how to correct or debug?

Thanks!

Appendix, longer log entry:
------------------------------------
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 505, in _handle_request
    environ, base_prefix, path, user)
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 813, in do_PROPFIND
    base_prefix, path, xml_content, read_items, write_items, user)
  File "/usr/lib/python3/dist-packages/radicale/xmlutils.py", line 812, in propfind
    allprop=allprop, propname=propname)
  File "/usr/lib/python3/dist-packages/radicale/xmlutils.py", line 1030, in _propfind_response
    element.text = item.etag
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1560, in etag
    self._etag_cache = super().etag
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 502, in etag
    for item in self.get_all():
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1464, in <genexpr>
    return (self.get(href, verify_href=False) for href in self.list())
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1282, in get
    item, metadata = self._get_with_metadata(href, verify_href=verify_href)
  File "/usr/lib/python3/dist-packages/radicale/storage.py", line 1429, in _get_with_metadata
    (href, self.path, e)) from e
RuntimeError: Failed to load item 'b6e34825-737f-677b-8bb9-eb6871576b3f.ics' in 'NN/NN.ics': 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

The respective file:
[b6e34825-737f-677b-8bb9-eb6871576b3f.ics.gz](https://github.com/Kozea/Radicale/files/6563563/b6e34825-737f-677b-8bb9-eb6871576b3f.ics.gz)

**Comment by anobar** [comment]
Well, the UTF-8 problem is solved. Removed characters not fitting the schema with sed on all single .ics files. On Bash:
find . -exec sed -i "s/.*\nBEGIN/BEGIN/g" {} \;

However, radicale and thunderbird calendar are still not synchronising. Since this description does not fit to the problem, the thread can be closed.
