### ISSUE TITLE
Can't upload calendar file: "multiple main components"

### ISSUE THREAD

**Issue by rixx** [Kozea/Radicale#1179]
I tried to upgrade from Radicale 2.x to 3.0. After Radicale didn't find my old calendar.ics, I decided to try to upload it instead. But the upload fails:

```python
[2021-08-26 17:27:31 +0200] [32840/Thread-97] [WARNING] Bad PUT request on '/rixx/05e8cddf-b821-317d-e93c-3232c830bcab/': Multiple main components
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/radicale/app/put.py", line 73, in prepare
    item.prepare()
  File "/usr/lib/python3.9/site-packages/radicale/item/__init__.py", line 394, in prepare
    self.time_range
  File "/usr/lib/python3.9/site-packages/radicale/item/__init__.py", line 384, in time_range
    find_tag_and_time_range(self.vobject_item))
  File "/usr/lib/python3.9/site-packages/radicale/item/__init__.py", line 262, in find_tag_and_time_range
    radicale_filter.visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/usr/lib/python3.9/site-packages/radicale/item/filter.py", line 230, in visit_time_ranges
    for child, is_recurrence, recurrences in get_children(
  File "/usr/lib/python3.9/site-packages/radicale/item/filter.py", line 222, in get_children
    raise ValueError("Multiple main components")
ValueError: Multiple main components
```

This calendar file was in constant use with Radicale 2.x, in case that matters.

Bisecting to find the offending items didn't show me anything out of the ordinary, to my eyes – the events I had to remove looked like this

```
BEGIN:VEVENT
CREATED:20190919T115216Z
LAST-MODIFIED:20190919T115321Z
DTSTAMP:20190919T115321Z
UID:2v8dntko-r49h-89bo-gcqd-as0v9gpwffff
SUMMARY:My Event
TRANSP:OPAQUE
CLASS:PUBLIC
DTSTART;TZID=Europe/Berlin:20191207T200000
DTEND;TZID=Europe/Berlin:20191207T220000
X-RADICALE-NAME:80d6b0e87af936fb9a88bef06decea158042497025d24d896e80e021405acaff.ics
END:VEVENT
```

**Comment by KanteTaete** [comment]
Hello @rixx,
was the "fix" finally to delete all the events which caused the issue? - So no kind of fix of radicale?

Regards

**Comment by rixx** [comment]
Yes, I fixed the problem by removing the events at fault.

**Comment by DerGuteMoritz** [comment]
Just ran into this, as well. I suggest to reopen the issue?

**Comment by rixx** [comment]
Might be better to open a new issue with a more detailed description and by somebody who is committed to see this through. As I never received a response from anybody working on Radicale, and removed the problem so that I can't reproduce it, a new issue seems like the better idea.

![2023-11-14T12:47:37+01:00](https://github.com/Kozea/Radicale/assets/2657547/992746f8-3ef6-444a-a0bc-19ba2a305e65)
