### ISSUE TITLE
HAVE_RENAMEAT2 is set on ZFS even though it's not supported

### ISSUE THREAD

**Issue by kraem** [Kozea/Radicale#1213]
Hi,

As the title says HAVE_RENAME2 is set falsely even though it might not be supported by the fs.

logs:
```
ERROR    radicale:__init__.py:107 An exception occurred during PUT request on '/calendar.ics/': [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/build/Radicale/radicale/app/__init__.py", line 105, in __call__
    status_text, headers, answers = self._handle_request(environ)
  File "/build/Radicale/radicale/app/__init__.py", line 287, in _handle_request
    status, headers, answer = function(
  File "/build/Radicale/radicale/app/put.py", line 207, in do_PUT
    etag = self._storage.create_collection(
  File "/build/Radicale/radicale/storage/multifilesystem/create_collection.py", line 67, in create_collection
    pathutils.rename_exchange(tmp_filesystem_path, filesystem_path)
  File "/build/Radicale/radicale/pathutils.py", line 184, in rename_exchange
    raise OSError(errno, os.strerror(errno))
OSError: [Errno 22] Invalid argument
=========================== short test summary info ============================
FAILED radicale/tests/test_base.py::TestBaseRequests::test_put_whole_calendar
FAILED radicale/tests/test_storage.py::TestMultiFileSystem::test_put_whole_calendar_uids_used_as_file_names
```

A naive approach to fix it might be to do something like
```
diff --git a/radicale/pathutils.py b/radicale/pathutils.py
index 5e87fa1..852d1b2 100644
--- a/radicale/pathutils.py
+++ b/radicale/pathutils.py
@@ -81,12 +81,13 @@ if sys.platform == "linux":
     except AttributeError:
         pass
     else:
-        HAVE_RENAMEAT2 = True
-        renameat2.argtypes = [
-            ctypes.c_int, ctypes.c_char_p,
-            ctypes.c_int, ctypes.c_char_p,
-            ctypes.c_uint]
-        renameat2.restype = ctypes.c_int
+        if renameat2(...) == 0:
+            HAVE_RENAMEAT2 = True
+            renameat2.argtypes = [
+                ctypes.c_int, ctypes.c_char_p,
+                ctypes.c_int, ctypes.c_char_p,
+                ctypes.c_uint]
+            renameat2.restype = ctypes.c_int


 class RwLock:

```

I'm guessing there are better ways to check this than my approach since I'm not that good with python.

I'm dropping this as a datapoint too:
https://github.com/NixOS/nixpkgs/issues/153473

**Comment by Unrud** [comment]
> I'm guessing there are better ways to check this than my approach since I'm not that good with python.

It's not quite right because `/tmp` may have another filesystem than the actual filesystem folder.
