### ISSUE TITLE
iOS can't get connected to Radicale CalDAV server

### ISSUE THREAD

**Issue by harrystuart** [Kozea/Radicale#1501]
Hey guys, I have this `docker-compose.yml`:

```
version: '3.7'

services:
  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    volumes:
      - /storage/enc/docker/radicale/data:/data
      - /storage/enc/docker/radicale/users:/etc/radicale/users
      - /storage/enc/docker/radicale/config:/config/config
    ports:
      - "5232:5232"
    restart: unless-stopped

volumes:
  data:
```

and this config file:

```
[server]
# Bind to all IP addresses
hosts = 0.0.0.0:5232

[auth]
type = htpasswd
htpasswd_filename = /etc/radicale/users
htpasswd_encryption = bcrypt

[storage]
filesystem_folder = /data
```

My server has IP `100.79.11.80` and all my devices are connected to the same Tailscale VPN. I can connect to the Radicale server fine using Thunderbird on my Windows machine. I can also see that the `/data` volume had event data written to it from Thunderbird. However, I am struggling to connect to the server from my iPhone 15 Pro (iOS 17.5.1.) 

I have tried the below iPhone CalDAV settings with no success:

**Server:** 100.79.11.80
**Username:** harry
**Password:** mypassword
**Description:** whatever
**Advanced Settings/Use SSL:** False
**Advanced Settings/Port:** 5232
**Advanced Settings/Account URL:** http://100.79.11.80:5232/

The above credentials work from Thunderbird on my Windows machine. Below is the running output of the container after pressing "Next" on my iPhone which results in the message "CalDAV account verification failed".

```
harry@harry-lab:~/code/harry-lab-docker/radicale$ docker-compose up
Creating network "radicale_default" with the default driver
Creating radicale ... done
Attaching to radicale
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] Loaded default config
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] Loaded config file '/config/config'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] Starting Radicale
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] auth type is 'radicale.auth.htpasswd'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] auth htpasswd encryption is 'radicale.auth.htpasswd_encryption.bcrypt'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] storage type is 'radicale.storage.multifilesystem'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] rights type is 'radicale.rights.owner_only'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] web type is 'radicale.web.internal'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] hook type is 'radicale.hook.none'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] permit delete of collection: True
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] Listening on '0.0.0.0:5232'
radicale    | [2024-05-29 13:14:51 +0000] [1] [INFO] Radicale server ready
radicale    | [2024-05-29 13:15:03 +0000] [1/Thread-1 (process_request_thread)] [INFO] PROPFIND request for '/.well-known/caldav' with depth '0' received from 100.81.91.109 using 'iOS/17.5.1 (21F90) accountsd/1.0'
radicale    | [2024-05-29 13:15:03 +0000] [1/Thread-1 (process_request_thread)] [INFO] PROPFIND response status for '/.well-known/caldav' with depth '0' in 0.002 seconds: 301 Moved Permanently
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-2 (process_request_thread)] [INFO] PROPFIND request for '/' with depth '0' received from 100.81.91.109 using 'iOS/17.5.1 (21F90) accountsd/1.0'
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-2 (process_request_thread)] [INFO] Access to '/' denied for anonymous user
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-2 (process_request_thread)] [INFO] PROPFIND response status for '/' with depth '0' in 0.002 seconds: 401 Unauthorized
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-3 (process_request_thread)] [INFO] PROPFIND request for '/' with depth '0' received from 100.81.91.109 using 'iOS/17.5.1 (21F90) accountsd/1.0'
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-3 (process_request_thread)] [INFO] Access to '/' denied for anonymous user
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-3 (process_request_thread)] [INFO] PROPFIND response status for '/' with depth '0' in 0.002 seconds: 401 Unauthorized
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-4 (process_request_thread)] [INFO] PROPFIND request for '/principals/' with depth '0' received from 100.81.91.109 using 'iOS/17.5.1 (21F90) accountsd/1.0'
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-4 (process_request_thread)] [INFO] Access to '/principals/' denied for anonymous user
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-4 (process_request_thread)] [INFO] PROPFIND response status for '/principals/' with depth '0' in 0.002 seconds: 401 Unauthorized
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-5 (process_request_thread)] [INFO] PROPFIND request for '/calendar/dav/harry/user/' with depth '0' received from 100.81.91.109 using 'iOS/17.5.1 (21F90) accountsd/1.0'
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-5 (process_request_thread)] [INFO] Access to '/calendar/dav/harry/user/' denied for anonymous user
radicale    | [2024-05-29 13:15:04 +0000] [1/Thread-5 (process_request_thread)] [INFO] PROPFIND response status for '/calendar/dav/harry/user/' with depth '0' in 0.002 seconds: 401 Unauthorized
```

Any assistance on getting this connection set-up would be greatly appreciated. Please let me know if any additional information is required. Thank you.

**Comment by harrystuart** [comment]
I created a self-signed certificate and did the following:

1. Installed certificate
2. Toggled the certificate "On" in "ENABLE FULL TRUST FOR ROOT CERTIFICATES"
3. Toggled "Account Settings/Use SSL" to "On"

The iOS Calendar now successfully syncs. However, the iOS Reminders are not working. Below is a log from the container:

```
harry@harry-lab:~/code/harry-lab-docker/radicale$ docker-compose up
Starting radicale ... done
Attaching to radicale
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] Loaded default config
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] Loaded config file '/config/config'
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] Starting Radicale
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] auth type is 'radicale.auth.htpasswd'
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] auth htpasswd encryption is 'radicale.auth.htpasswd_encryption.bcrypt'
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] storage type is 'radicale.storage.multifilesystem'
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] rights type is 'radicale.rights.owner_only'
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] web type is 'radicale.web.internal'
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] hook type is 'radicale.hook.none'
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] permit delete of collection: True
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] Listening on '0.0.0.0:5232' with SSL
radicale    | [2024-05-29 14:35:18 +0000] [1] [INFO] Radicale server ready
radicale    | [2024-05-29 14:35:26 +0000] [1/Thread-1 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | [2024-05-29 14:35:48 +0000] [1/Thread-2 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1006)
```

Not sure how to fix this one...

**Comment by pbiering** [comment]
```
radicale    | [2024-05-29 14:35:26 +0000] [1/Thread-1 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | [2024-05-29 14:35:48 +0000] [1/Thread-2 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1006)
```

looks like the specific client is not connecting via TLS. Can you try to `ngrep` on that specific port and check at least what cleartext is visible. Potentially "debug" log level will also show more.

**Comment by harrystuart** [comment]
Here is the `debug` output from the container. For this test, I disabled "Calendar" sync in the iOS settings for this CalDAV account because it has been proven to work, so this output pertains only to iOS "Reminders" trying to connect to the server:

```
harry@harry-lab:~/code/harry-lab-docker/radicale$ docker-compose up
Creating network "radicale_default" with the default driver
Creating radicale ... done
Attaching to radicale
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] Loaded default config
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] Loaded config file '/config/config'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] Starting Radicale
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] auth type is 'radicale.auth.htpasswd'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] auth htpasswd encryption is 'radicale.auth.htpasswd_encryption.bcrypt'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] storage type is 'radicale.storage.multifilesystem'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] rights type is 'radicale.rights.owner_only'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] web type is 'radicale.web.internal'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] hook type is 'radicale.hook.none'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] permit delete of collection: True
radicale    | [2024-05-30 01:29:16 +0000] [1] [DEBUG] getaddrinfo of '0.0.0.0:5232': [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '0.0.0.0', ('0.0.0.0', 5232))]
radicale    | [2024-05-30 01:29:16 +0000] [1] [DEBUG] try to create server socket on '0.0.0.0:5232'
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] Listening on '0.0.0.0:5232' with SSL
radicale    | [2024-05-30 01:29:16 +0000] [1] [INFO] Radicale server ready
radicale    | [2024-05-30 01:29:27 +0000] [1/Thread-1 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | Traceback (most recent call last):
radicale    |   File "/venv/lib/python3.11/site-packages/radicale/server.py", line 198, in finish_request_locked
radicale    |     request.do_handshake()
radicale    |   File "/usr/lib/python3.11/ssl.py", line 1382, in do_handshake
radicale    |     self._sslobj.do_handshake()
radicale    | ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | 
radicale    | The above exception was the direct cause of the following exception:
radicale    | 
radicale    | Traceback (most recent call last):
radicale    |   File "/venv/lib/python3.11/site-packages/radicale/server.py", line 202, in finish_request_locked
radicale    |     raise RuntimeError("SSL handshake failed: %s" % e) from e
radicale    | RuntimeError: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | [2024-05-30 01:29:30 +0000] [1/Thread-2 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | Traceback (most recent call last):
radicale    |   File "/venv/lib/python3.11/site-packages/radicale/server.py", line 198, in finish_request_locked
radicale    |     request.do_handshake()
radicale    |   File "/usr/lib/python3.11/ssl.py", line 1382, in do_handshake
radicale    |     self._sslobj.do_handshake()
radicale    | ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | 
radicale    | The above exception was the direct cause of the following exception:
radicale    | 
radicale    | Traceback (most recent call last):
radicale    |   File "/venv/lib/python3.11/site-packages/radicale/server.py", line 202, in finish_request_locked
radicale    |     raise RuntimeError("SSL handshake failed: %s" % e) from e
radicale    | RuntimeError: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | [2024-05-30 01:29:30 +0000] [1/Thread-3 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | Traceback (most recent call last):
radicale    |   File "/venv/lib/python3.11/site-packages/radicale/server.py", line 198, in finish_request_locked
radicale    |     request.do_handshake()
radicale    |   File "/usr/lib/python3.11/ssl.py", line 1382, in do_handshake
radicale    |     self._sslobj.do_handshake()
radicale    | ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
radicale    | 
radicale    | The above exception was the direct cause of the following exception:
radicale    | 
radicale    | Traceback (most recent call last):
radicale    |   File "/venv/lib/python3.11/site-packages/radicale/server.py", line 202, in finish_request_locked
radicale    |     raise RuntimeError("SSL handshake failed: %s" % e) from e
radicale    | RuntimeError: SSL handshake failed: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
```

The below snipped is the output of `ngrep` after refreshing iOS Reminders:

```
harry@harry-lab:~$ sudo ngrep -d any port 5232
interface: any
filter: ( port 5232 ) and (ip || ip6)
##########
T 100.81.91.109:64684 -> 100.79.11.80:5232 [AP] #10
  ............t..t....m..a."B....O.x..%.dK.#. .....xj$]/.+z...n......i.c..,....*jj.......,.+...0./...............5./.......................harry-lab..................................
  ....h2.http/1.1..........................................3.+.)........ i...# F..#../.8.=..m..-...1.#g,Z.-.....+...JJ...............zz...............................................
  .............................................................................................................................................................
#
T 100.81.91.109:64684 -> 192.168.16.2:5232 [AP] #11
  ............t..t....m..a."B....O.x..%.dK.#. .....xj$]/.+z...n......i.c..,....*jj.......,.+...0./...............5./.......................harry-lab..................................
  ....h2.http/1.1..........................................3.+.)........ i...# F..#../.8.=..m..-...1.#g,Z.-.....+...JJ...............zz...............................................
  .............................................................................................................................................................
#
T 100.81.91.109:64684 -> 192.168.16.2:5232 [AP] #12
  ............t..t....m..a."B....O.x..%.dK.#. .....xj$]/.+z...n......i.c..,....*jj.......,.+...0./...............5./.......................harry-lab..................................
  ....h2.http/1.1..........................................3.+.)........ i...# F..#../.8.=..m..-...1.#g,Z.-.....+...JJ...............zz...............................................
  .............................................................................................................................................................
####
T 192.168.16.2:5232 -> 100.81.91.109:64684 [AP] #16
  ....z...v...J.......$8o.w.8.4.lF..U.0T...-* .....xj$]/.+z...n......i.c..,.........+.....3.$... @-4%........ .o.CC.....,....m&..................3..a..../dk./..*.f...........  ....l.
  W}...l}.?:..>.s.q....Fg/...Z.....y.3U99.........V.M..\...g\......b.~.S..e0..-.1.mN&9eQ.......Q..-y..h.N@.M._0Cu...?p....7....BL/.X.F.dQj........?..m'.}1.2]%..f.,...%.....>.g.)...>f
  (..j>q.J..H..>....h.......&.z...b......m.o...U7..E....< J......r.GN..].."M~|yp.9<x..uT..j.....CD7.o.+DM.x....MCr..z......X....q.#..bZ..._.......O.V5.q.+6.;l..v....k.Q<M~.."\...jfD;
  `....`\....6Q.a.$.],......L....t+.q #E._.m<.......2..N.U..&....z*.H..C.z.._.....=..<%l...."..1.N*st.....bW...[.AB..~..p.A../......(..:...t.z..\.lMj....g.Y...o.,...}...[.....N{.0.-
  .....[+...).}.k....6..q6.....H....I.....Ov.mC...l..)!.B.p.a.=..x,/.;|`...uG~.U...(..../vh.S./u.f..n...-..@c.(.F...9%&.;?7.2Iw.@m..:..%....5.)7...$.......}....-U.<.{m.#v.2_..c0...3B
  v.....w.[.......?IC(...V..........................~.]...A=.2..Rh*.2.....r.=J....WpX...T2...T.l.j......=X...7..0Hx...CbB.1..5GtUP...k.R.....D....Z4`.,....G5{<...L....g....Edx.:.....
  ...b{'x:!...j/...aL.....j#0......f.T.]."W...........*;v.6.'.g[....F.....\.4.[8Fm@..p..V......8.y.|.l...?.]......G...</.E........V.....;...E....#.Z.....%......R..J.Z...0.._...e.....
  .C.........i.Lq..m[-..S...S~.n........5#..g..Y...........X.......CN......]o.g.:..e....*.6B.....Kf_X.....!...Q@.%'OTG.Fh..':g@.j{..._..H.>...-].i....d.._NT.J.5....w.. .\*..5.$.M....
   .V..K>.kkR...2...K....R.E.....K.&..|H^M....Zs{d.....E...N......"..Z.#...s...5o$o.{..J.........'.|h4.>.....&.?Bx......D*.N.
#
T 192.168.16.2:5232 -> 100.81.91.109:64684 [AP] #17
  ....z...v...J.......$8o.w.8.4.lF..U.0T...-* .....xj$]/.+z...n......i.c..,.........+.....3.$... @-4%........ .o.CC.....,....m&..................3..a..../dk./..*.f...........  ....l.
  W}...l}.?:..>.s.q....Fg/...Z.....y.3U99.........V.M..\...g\......b.~.S..e0..-.1.mN&9eQ.......Q..-y..h.N@.M._0Cu...?p....7....BL/.X.F.dQj........?..m'.}1.2]%..f.,...%.....>.g.)...>f
  (..j>q.J..H..>....h.......&.z...b......m.o...U7..E....< J......r.GN..].."M~|yp.9<x..uT..j.....CD7.o.+DM.x....MCr..z......X....q.#..bZ..._.......O.V5.q.+6.;l..v....k.Q<M~.."\...jfD;
  `....`\....6Q.a.$.],......L....t+.q #E._.m<.......2..N.U..&....z*.H..C.z.._.....=..<%l...."..1.N*st.....bW...[.AB..~..p.A../......(..:...t.z..\.lMj....g.Y...o.,...}...[.....N{.0.-
  .....[+...).}.k....6..q6.....H....I.....Ov.mC...l..)!.B.p.a.=..x,/.;|`...uG~.U...(..../vh.S./u.f..n...-..@c.(.F...9%&.;?7.2Iw.@m..:..%....5.)7...$.......}....-U.<.{m.#v.2_..c0...3B
  v.....w.[.......?IC(...V..........................~.]...A=.2..Rh*.2.....r.=J....WpX...T2...T.l.j......=X...7..0Hx...CbB.1..5GtUP...k.R.....D....Z4`.,....G5{<...L....g....Edx.:.....
  ...b{'x:!...j/...aL.....j#0......f.T.]."W...........*;v.6.'.g[....F.....\.4.[8Fm@..p..V......8.y.|.l...?.]......G...</.E........V.....;...E....#.Z.....%......R..J.Z...0.._...e.....
  .C.........i.Lq..m[-..S...S~.n........5#..g..Y...........X.......CN......]o.g.:..e....*.6B.....Kf_X.....!...Q@.%'OTG.Fh..':g@.j{..._..H.>...-].i....d.._NT.J.5....w.. .\*..5.$.M....
   .V..K>.kkR...2...K....R.E.....K.&..|H^M....Zs{d.....E...N......"..Z.#...s...5o$o.{..J.........'.|h4.>.....&.?Bx......D*.N.
#
T 100.79.11.80:5232 -> 100.81.91.109:64684 [AP] #18
  ....z...v...J.......$8o.w.8.4.lF..U.0T...-* .....xj$]/.+z...n......i.c..,.........+.....3.$... @-4%........ .o.CC.....,....m&..................3..a..../dk./..*.f...........  ....l.
  W}...l}.?:..>.s.q....Fg/...Z.....y.3U99.........V.M..\...g\......b.~.S..e0..-.1.mN&9eQ.......Q..-y..h.N@.M._0Cu...?p....7....BL/.X.F.dQj........?..m'.}1.2]%..f.,...%.....>.g.)...>f
  (..j>q.J..H..>....h.......&.z...b......m.o...U7..E....< J......r.GN..].."M~|yp.9<x..uT..j.....CD7.o.+DM.x....MCr..z......X....q.#..bZ..._.......O.V5.q.+6.;l..v....k.Q<M~.."\...jfD;
  `....`\....6Q.a.$.],......L....t+.q #E._.m<.......2..N.U..&....z*.H..C.z.._.....=..<%l...."..1.N*st.....bW...[.AB..~..p.A../......(..:...t.z..\.lMj....g.Y...o.,...}...[.....N{.0.-
  .....[+...).}.k....6..q6.....H....I.....Ov.mC...l..)!.B.p.a.=..x,/.;|`...uG~.U...(..../vh.S./u.f..n...-..@c.(.F...9%&.;?7.2Iw.@m..:..%....5.)7...$.......}....-U.<.{m.#v.2_..c0...3B
  v.....w.[.......?IC(...V..........................~.]...A=.2..Rh*.2.....r.=J....WpX...T2...T.l.j......=X...7..0Hx...CbB.1..5GtUP...k.R.....D....Z4`.,....G5{<...L....g....Edx.:.....
  ...b{'x:!...j/...aL.....j#0......f.T.]."W...........*;v.6.'.g[....F.....\.4.[8Fm@..p..V......8.y.|.l...?.]......G...</.E........V.....;...E....#.Z.....%......R..J.Z...0.._...e.....
  .C.........i.Lq..m[-..S...S~.n........5#..g..Y...........X.......CN......]o.g.:..e....*.6B.....Kf_X.....!...Q@.%'OTG.Fh..':g@.j{..._..H.>...-].i....d.._NT.J.5....w.. .\*..5.$.M....
   .V..K>.kkR...2...K....R.E.....K.&..|H^M....Zs{d.....E...N......"..Z.#...s...5o$o.{..J.........'.|h4.>.....&.?Bx......D*.N.
#######
T 192.168.16.2:5232 -> 100.81.91.109:64684 [AP] #25
  .......B..j....C1..o.=..
#
T 192.168.16.2:5232 -> 100.81.91.109:64684 [AP] #26
  .......B..j....C1..o.=..
#
T 100.79.11.80:5232 -> 100.81.91.109:64684 [AP] #27
  .......B..j....C1..o.=..
#########
```

**Comment by pbiering** [comment]
I can replay partially such package behavior by using a "curl" request....which terminates because of it does not trust the certificate. So potentially the truststore for "Reminder" is a different one than for "Calendar".

But in my case the log line shows

```
[2024-05-30 20:56:38 +0200] [25502/Thread-1] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1129)
```

But this message "TLSV1_ALERT_UNKNOWN_CA" is from the client, potentially "Reminder" simply terminates the connection.

-> retryy using a certificate matching the FQDN issued by a trusted CA, e.g. "Let's Encrypt".

**Comment by harrydabble** [comment]
Yep, I think that's it. I just setup an internal DNS and reverse proxy with a Let's Encrypt certificate. Everything - including reminders - synced straight away. To future readers, it seems like in iOS 17.5.1, Reminders will not work with self-signed certificates. Happy to close this
