### ISSUE TITLE
Calendar query exception

### ISSUE THREAD

**Issue by smurfix** [Kozea/Radicale#1591]
Radicale 3.2.3 raises an exception when python-caldav is tested against it:

``` xml
<?xml version="1.0"?>
<C:calendar-query xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <prop>
    <C:calendar-data>
      <C:expand start="19970413T220000Z" end="20150513T220000Z" />
    </C:calendar-data>
  </prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VTODO">
        <C:time-range start="19970413T220000Z" end="20150513T220000Z" />
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>

```

Traceback, from debug log:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 529, in __getattr__
    return self.contents[toVName(name)][0]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'vevent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/app/__init__.py", line 112, in __call__
    status_text, headers, answers = self._handle_request(environ)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/radicale/app/__init__.py", line 310, in _handle_request
    status, headers, answer = function(
                              ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/radicale/app/report.py", line 545, in do_REPORT
    status, xml_answer = xml_report(
                         ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/radicale/app/report.py", line 275, in xml_report
    expanded_element = _expand(
                       ^^^^^^^^
  File "/usr/lib/python3/dist-packages/radicale/app/report.py", line 301, in _expand
    if type(item.vobject_item.vevent.dtstart.value) is datetime.date:
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vobject/base.py", line 531, in __getattr__
    raise AttributeError(name)
AttributeError: vevent
[2024-10-10 22:04:45 +0200] [93321/Thread-18 (process_request_thread)] [ERROR] An exception occurred during REPORT request on '/tester/pythoncaldav-test/': vevent
```
The testcase sends these entries:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VTODO
CATEGORIES:FAMILY,FINANCE
CLASS:CONFIDENTIAL
DTSTAMP:20070313T123432Z
DUE;VALUE=DATE:20070501
STATUS:NEEDS-ACTION
SUMMARY:Submit Quebec Income Tax Return for 2006
UID:20070313T123432Z-456553@example.com
END:VTODO
END:VCALENDAR

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VTODO
CATEGORIES:FAMILY,FINANCE
CLASS:CONFIDENTIAL
DTSTAMP:19970901T130000Z
DTSTART:19970415T133000Z
DUE:19970416T045959Z
PRIORITY:2
STATUS:NEEDS-ACTION
SUMMARY:1996 Income Tax Preparation
UID:19970901T130000Z-123404@host.com
END:VTODO
END:VCALENDAR

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VTODO
CATEGORIES:FAMILY,FINANCE
CLASS:CONFIDENTIAL
DTSTAMP:19970901T130000Z
DTSTART:19970415T133000Z
DUE:19970516T045959Z
PRIORITY:1
SUMMARY:1996 Income Tax Preparation
UID:19970901T130000Z-123405@host.com
END:VTODO
END:VCALENDAR

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VTODO
CATEGORIES:FAMILY,FINANCE
CLASS:CONFIDENTIAL
DTSTAMP:19970901T130000Z
PRIORITY:1
STATUS:NEEDS-ACTION
SUMMARY:1996 Income Tax Preparation
UID:19970901T130000Z-123406@host.com
END:VTODO
END:VCALENDAR

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VTODO
CATEGORIES:FAMILY,FINANCE
CLASS:CONFIDENTIAL
DTSTAMP:19920901T130000Z
DTSTART:19920415T133000Z
DUE:19920516T045959Z
PRIORITY:1
SUMMARY:1992 Income Tax Preparation
UID:19920901T130000Z-123407@host.com
END:VTODO
END:VCALENDAR

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VTODO
CATEGORIES:FAMILY,FINANCE
CLASS:CONFIDENTIAL
DTSTAMP:19920901T130000Z
DTSTART:19920415T133000Z
DUE:19920516T045959Z
PRIORITY:1
RRULE:FREQ=YEARLY
SUMMARY:Yearly Income Tax Preparation
UID:19920901T130000Z-123408@host.com
END:VTODO
END:VCALENDAR
```

**Comment by pbiering** [comment]
@smurfix - have you confirmed that all your calendar entries passing the validator, see here for information https://github.com/Kozea/Radicale/wiki/Reporting-Issues

Beside that it should not throw an exception, will at least check this part in _radicale_.

**Comment by pbiering** [comment]
was able to replicate, the problem is caused by the query part _expand_ - will take a look why.

OK:

```
<?xml version="1.0"?>
<C:calendar-query xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <prop>
     <C:calendar-data>
    </C:calendar-data>
  </prop>
</C:calendar-query>
```

Problematic

```
<?xml version="1.0"?>
<C:calendar-query xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <prop>
     <C:calendar-data>
                  <C:expand start="19970413T220000Z" end="20150513T220000Z" />
    </C:calendar-data>
  </prop>
</C:calendar-query>
```
