### ISSUE TITLE
IOError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by paulepanter** [Kozea/Radicale#161]
With Debian and the package Radicale 0.8-2 the following error is shown on the terminal.

        # radicale --foreground -D --hosts 0.0.0.0:5232
        Traceback (most recent call last):
          File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
            self.result = application(self.environ, self.start_response)
          File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 300, in __call__
            user)
          File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 509, in propfind
            environ["PATH_INFO"], content, collections, user)
          File "/usr/lib/python2.7/dist-packages/radicale/xmlutils.py", line 226, in propfind
            response = _propfind_response(path, collection, props, user)
          File "/usr/lib/python2.7/dist-packages/radicale/xmlutils.py", line 237, in _propfind_response
            collection_props = properties
          File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
            self.gen.next()
          File "/usr/lib/python2.7/dist-packages/radicale/storage/filesystem.py", line 113, in props
            with open(self._props_path, "w") as prop_file:
          File "/usr/lib/python2.7/dist-packages/radicale/storage/filesystem.py", line 42, in open
            return codecs.open(abs_path, mode, config.get("encoding", "stock"))
          File "/usr/lib/python2.7/codecs.py", line 878, in open
            file = __builtin__.open(filename, mode, buffering)
        IOError: [Errno 20] Not a directory: '/var/lib/radicale/collections/calendars/joe/joe.ics.props'

        # ls /var/lib/radicale/collections/calendars/joe/
        ls: cannot access /var/lib/radicale/collections/calendars/joe/: Not a directory
        # ls /var/lib/radicale/collections/calendars/joe
        /var/lib/radicale/collections/calendars/joe

**Comment by liZe** [comment]
Probably fixed, now that #159 and #162 are fixed, and now that the storage module has been rewritten.
