### ISSUE TITLE
value of 'filesystem_folder' appears twice in 'abs_path'

### ISSUE THREAD

**Issue by tools400** [Kozea/Radicale#164]
On Windows 7, the value of 'filesystem_folder' appears twice in 'abs_path', using the following configuration:
```
# Folder for storing local collections, created if not present
## filesystem_folder = ~/.config/radicale/collections
filesystem_folder = .\collectionsX\
```
Radicale is startet with the following cmd file to load the configuration file:
```
set PYTHON_HOME=c:\Programme_x86\Python34
set RADICALE_CONFIG=c:\Programme_x86\Radicale\
cls
call %PYTHON_HOME%\python.exe radicale.py --config=%RADICALE_CONFIG%\config
```
Nothing else of the config file has been changed.

In order to get the values of 'FOLDER' and 'path' of filesystem.py, I added logging statements to the open() method like this:
```
# On enter
abs_path = os.path.join(FOLDER, path.replace("/", os.sep))
log.LOGGER.warning("FOLDER=" + FOLDER)
log.LOGGER.warning("path=" + path)
log.LOGGER.warning("Calendar file: " + abs_path)
```
The console output shows:
```
Anonymous has read access to collection user/Joe/
Anonymous has write access to collection user/Joe/
FOLDER=.\collectionsX\
path=.\collectionsX\user\Joe.props
Calendar file: .\collectionsX\.\collectionsX\user\Joe.props
Traceback (most recent call last):
  File "c:\Programme_x86\Python34\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "c:\Programme_x86\Radicale\radicale\__init__.py", line 298, in __call__
    user)
  File "c:\Programme_x86\Radicale\radicale\__init__.py", line 512, in propfind
    environ["PATH_INFO"], content, collections, user)
  File "c:\Programme_x86\Radicale\radicale\xmlutils.py", line 239, in propfind
    response = _propfind_response(path, collection, props, user)
  File "c:\Programme_x86\Radicale\radicale\xmlutils.py", line 346, in _propfind_
response
    not item.exists and item.resource_type):
  File "c:\Programme_x86\Radicale\radicale\ical.py", line 435, in resource_type
    if self.tag == "VADDRESSBOOK":
  File "c:\Programme_x86\Radicale\radicale\ical.py", line 422, in tag
    return props["tag"]
  File "c:\Programme_x86\Python34\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "c:\Programme_x86\Radicale\radicale\storage\filesystem.py", line 136, in
props
    with open(self._props_path, "w") as prop_file:
  File "c:\Programme_x86\Python34\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "c:\Programme_x86\Radicale\radicale\storage\filesystem.py", line 54, in o
pen
    with codecs.open(abs_path, mode, config.get("encoding", "stock")) as fd:
  File "c:\Programme_x86\Python34\lib\codecs.py", line 896, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '.\\collectionsX\\.\\col
lectionsX\\user\\Joe.props'
```
Any ideas of what I am missing?

Thomas.

**Comment by liZe** [comment]
Storing calendars in the program directory **and** making this behaviour sharable with a zip is a bit too much for me :smile:. Adding a Windows script + fixing #154 makes the trick.
