### ISSUE TITLE
"Works out-of-the-box, no complicated setup or configuration required."

### ISSUE THREAD

**Issue by trancephorm** [Kozea/Radicale#1658]
Well, installation is pretty much not straightforward I would say:

xxx@xxx:~$ python3.8 -m pip install --user --upgrade https://github.com/Kozea/Radicale/archive/master.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/.local/lib/python3.8/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/xxx/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/xxx/.local/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/xxx/.local/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/xxx/.local/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 21, in <module>
    from pip._vendor.packaging.utils import canonicalize_name
  File "/home/xxxx/.local/lib/python3.8/site-packages/pip/_vendor/packaging/utils.py", line 9, in <module>
    from .tags import Tag, parse_tag
  File "/home/xxx/.local/lib/python3.8/site-packages/pip/_vendor/packaging/tags.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils.util'

So, you should put **sudo apt install python3.8-distutils** in installation manual.

**Comment by pbiering** [comment]
That is strange, but as Python 3.8 is anyhow EoSL, have you tried Python > 3.8?

At least on Fedora F42, `distutils` is packaged with `python3-pip`, and on EL8 with Python 3.8 it's also working out-of-the-box.

Which type and version of Debian based OS are you using?

**Comment by trancephorm** [comment]
Ubuntu 24.04

**Comment by pbiering** [comment]
you are using python 3.8 on Ubunto 24.04? What happen if you are using newer Python version? Is here also `distutils` debundled from `pip` package?

**Comment by trancephorm** [comment]
I just wanted to tell python 3.8 is not installed by default on Ubuntu 24.04, as well as python3.8-distutils. So installation is actually not straighforward, was thinking you can mention those requirements in doc.

**Comment by pbiering** [comment]
Python 3.8 is EOSL and support in Radicale is only still best effort, so I would no longer add any new references, I would expect that soon even build test via GitHub will no longer work.

See also: https://github.com/Kozea/Radicale/wiki
