### ISSUE TITLE
`UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 671: ordinal not in range(128)`

### ISSUE THREAD

**Issue by paulepanter** [Kozea/Radicale#218]
With Radicale 0.9 [from Debian Sid/unstable](https://packages.debian.org/sid/radicale) and running it with Python 3.4 (Python 3.4.2rc1+), I get the error below.

```
    $ python3 /usr/bin/radicale -C /etc/radicale/config --debug --ssl
    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
        stream.write(msg)
    UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 671: ordinal not in range(128)
    Call stack:
      File "/usr/lib/python3.4/threading.py", line 889, in _bootstrap
        self._bootstrap_inner()
      File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.4/threading.py", line 869, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib/python3/dist-packages/radicale/__main__.py", line 144, in serve_forever
        server.serve_forever()
      File "/usr/lib/python3.4/socketserver.py", line 238, in serve_forever
        self._handle_request_noblock()
      File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/usr/lib/python3.4/socketserver.py", line 669, in __init__
        self.handle()
      File "/usr/lib/python3.4/wsgiref/simple_server.py", line 133, in handle
        handler.run(self.server.get_app())
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
        self.result = application(self.environ, self.start_response)
      File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 269, in __call__
        log.LOGGER.debug("Request content:\n%s" % content)
      […]
```

I am using the PostgreSQL storage backend.

**Comment by liZe** [comment]
@paulepanter This problem is probably fixed now. Could you check with the current master branch?
