### ISSUE TITLE
PUT requests are hanging

### ISSUE THREAD

**Issue by somecallmemike** [Kozea/Radicale#253]
We are trying to use Radicale with database storage in an environment with about 100 users, and after turning it up it the system seems to be hanging constantly on PUT requests.  The logs are not describing any kind of failure, rather the PUT request shows up and then no other requests seem to be able to be handled afterwards.

Here is an example log:

```
2015-01-14 08:36:25,534 - INFO: PUT request at /user@domain.net/personal.vcf/.vcf received
2015-01-14 08:36:25,535 - DEBUG: Request headers:
{'CONTENT_LENGTH': '35',
 'CONTENT_TYPE': 'text/vcard',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_AUTHORIZATION': 'Basic cGF0cml3ZWJAd29sZm5ldC5uZXQ6WkJONUpNUA==',
 'HTTP_CONNECTION': 'Close',
 'HTTP_HOST': 'dav.domain.net',
 'HTTP_USER_AGENT': 'MyRoundcube PHP/5.0',
 'PATH_INFO': '/user@domain.net/personal.vcf/.vcf',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '1.2.3.4',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'server.domain.net',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.6.6',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f14c70aa1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f14c6f55ad0>,
 'wsgi.input': <socket._fileobject object at 0x1a19ad0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-01-14 08:36:25,535 - DEBUG: Sanitized path: /user@domain.net/personal.vcf/.vcf
2015-01-14 08:36:25,535 - DEBUG: Connecting to IMAP server dav.domain.net:993.
2015-01-14 08:36:25,611 - DEBUG: Authenticated IMAP user user@domain.net via imap.domain.net.
2015-01-14 08:36:25,617 - DEBUG: Rights type 'owner_only'
2015-01-14 08:36:25,617 - DEBUG: Test if 'user@domain.net:user@domain.net/personal.vcf' matches against '.+:^user@domain.net(/.*)?$' from section 'rw'
2015-01-14 08:36:25,618 - DEBUG: Section 'rw' matches
2015-01-14 08:36:25,618 - DEBUG: user@domain.net has read access to collection user@domain.net/personal.vcf/
2015-01-14 08:36:25,618 - DEBUG: Rights type 'owner_only'
2015-01-14 08:36:25,618 - DEBUG: Test if 'user@domain.net:user@domain.net/personal.vcf' matches against '.+:^user@domain.net(/.*)?$' from section 'rw'
2015-01-14 08:36:25,618 - DEBUG: Section 'rw' matches
2015-01-14 08:36:25,618 - DEBUG: user@domain.net has write access to collection user@domain.net/personal.vcf/
2015-01-14 08:36:25,619 - DEBUG: Request content:
BEGIN:VCARD
VERSION:3.0
N:Vaughan;Barb;;;
FN:Barb Vaughan
EMAIL;TYPE=INTERNET;TYPE=OTHER:testuser@testdomain.net
UID:12661E97-F4CF8735-E0BA5479
END:VCARD
```

Here is our config:

```
# -*- mode: conf -*-
# vim:ft=cfg

# Config file for Radicale - A simple calendar server
#
# Place it into /etc/radicale/config (global)
# or ~/.config/radicale/config (user)
#
# The current values are the default ones


[server]
# CalDAV server hostnames separated by a comma
# IPv4 syntax: address:port
# IPv6 syntax: [address]:port
# For example: 0.0.0.0:9999, [::]:9999
# IPv6 adresses are configured to only allow IPv6 connections
hosts = 0.0.0.0:5232
# Daemon flag
daemon = False
# File storing the PID in daemon mode
pid =
# SSL flag, enable HTTPS protocol
ssl = True
# SSL certificate path
certificate = /usr/local/admin/ssl.crt/mdc.crt
# SSL private key
key = /usr/local/admin/ssl.key/mdc.key
#CAfile = /usr/local/admin/ssl.ca/mdc.ca
# SSL Protocol used. See python's ssl module for available values
protocol = PROTOCOL_SSLv23
# Ciphers available. See python's ssl module for available ciphers
ciphers =
# Reverse DNS to resolve client address in logs
dns_lookup = False
# Root URL of Radicale (starting and ending with a slash)
base_prefix = /
# Possibility to allow URLs cleaned by a HTTP server, without the base_prefix
can_skip_base_prefix = False
# Message displayed in the client when a password is needed
realm = Radicale - Password Required


[encoding]
# Encoding for responding requests
request = utf-8
# Encoding for storing local collections
stock = utf-8


[auth]
# Authentication method
# Value: None | htpasswd | IMAP | LDAP | mysql | PAM | courier | http | remote_user | custom
type = IMAP

# Custom authentication handler
custom_handler =

# Htpasswd filename
htpasswd_filename = /etc/radicale/users
# Htpasswd encryption method
# Value: plain | sha1 | crypt
htpasswd_encryption = crypt

# LDAP server URL, with protocol and port
ldap_url = ldap://localhost:389/
# LDAP base path
ldap_base = ou=users,dc=example,dc=com
# LDAP login attribute
ldap_attribute = uid
# LDAP filter string
# placed as X in a query of the form (&(...)X)
# example: (objectCategory=Person)(objectClass=User)(memberOf=cn=calenderusers,ou=users,dc=example,dc=org)
# leave empty if no additional filter is needed
ldap_filter =
# LDAP dn for initial login, used if LDAP server does not allow anonymous searches
# Leave empty if searches are anonymous
ldap_binddn =
# LDAP password for initial login, used with ldap_binddn
ldap_password =
# LDAP scope of the search
ldap_scope = OneLevel

# IMAP Configuration
imap_hostname = imap.domain.tld
imap_port = 993
imap_ssl = True

# PAM group user should be member of
pam_group_membership =

# Path to the Courier Authdaemon socket
courier_socket =

# HTTP authentication request URL endpoint
http_url =
# POST parameter to use for username
http_user_parameter =
# POST parameter to use for password
http_password_parameter =


[git]
# Git default options
committer = Radicale <radicale@example.com>


[rights]
# Rights backend
# Value: None | authenticated | owner_only | owner_write | from_file | custom
type = owner_only

# Custom rights handler
custom_handler =

# File for rights management from_file
file = ~/.config/radicale/rights


[storage]
# Storage backend
# Value: filesystem | multifilesystem | database | custom
type = database

# Custom storage handler
custom_handler =

# Folder for storing local collections, created if not present
filesystem_folder = ~/.config/radicale/collections

# Database URL for SQLAlchemy
# dialect+driver://user:password@host/dbname[?key=value..]
# For example: sqlite:///var/db/radicale.db, postgresql://user:password@localhost/radicale
# See http://docs.sqlalchemy.org/en/rel_0_8/core/engines.html#sqlalchemy.create_engine
database_url = mysql+mysqldb://user:pass@ip:3306/radicale


[logging]
# Logging configuration file
# If no config is given, simple information is printed on the standard output
# For more information about the syntax of the configuration file, see:
# http://docs.python.org/library/logging.config.html
config = /etc/radicale/logging
# Set the default logging level to debug
debug = False
# Store all environment variables (including those set in the shell)
full_environment = False


# Additional HTTP headers
#[headers]
#Access-Control-Allow-Origin = *
```

**Comment by liZe** [comment]
You shouldn't use the database storage for production. It's just a broken toy :). See #114.

**Comment by untitaker** [comment]
@somecallmemike Your log is probably missing stderr. There should be a traceback there because your PUT request points to an invalid filename.

**Comment by somecallmemike** [comment]
I am executing an init script with the following exec /usr/bin/radicale >> /var/log/radicale.log 2>&1.  The log I put in the issue was the debug log file that Radicale creates.  If you want to see some python errors from the log file I am generating here is one:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/wsgiref/handlers.py", line 93, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.6/site-packages/radicale/__init__.py", line 331, in __call__
    user)
  File "/usr/lib/python2.6/site-packages/radicale/__init__.py", line 545, in propfind
    environ["PATH_INFO"], content, collections, user)
  File "/usr/lib/python2.6/site-packages/radicale/xmlutils.py", line 237, in propfind
    response = _propfind_response(path, collection, props, user)
  File "/usr/lib/python2.6/site-packages/radicale/xmlutils.py", line 339, in _propfind_response
    element.text = item.etag
  File "/usr/lib/python2.6/site-packages/radicale/storage/database.py", line 189, in etag
    return '"%s"' % hash(self._modification_time)
  File "/usr/lib/python2.6/site-packages/radicale/storage/database.py", line 131, in _modification_time
    .join(DBItem).filter_by(collection_path=self.path).first()[0])
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2367, in first
    ret = list(self[0:1])
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
    return list(res)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2437, in __iter__
    self.session._autoflush()
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 479, in execute
    self.dependency_processor.process_deletes(uow, states)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/dependency.py", line 530, in process_deletes
    uowcommit, False)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/dependency.py", line 575, in _synchronize
    sync.clear(dest, self.mapper, self.prop.synchronize_pairs)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/sync.py", line 57, in clear
    (r, orm_util.state_str(dest))
AssertionError: Dependency rule tried to blank-out primary key column 'header.collection_path' on instance '<DBHeader at 0x7f0754ad5e50>'
Exception sqlalchemy.exc.InvalidRequestError: InvalidRequestError("This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Dependency rule tried to blank-out primary key column 'header.collection_path' on instance '<DBHeader at 0x7f0754ad5e50>'",) in <bound method Collection.__del__ of <radicale.storage.database.Collection object at 0x7f07547e2210>> ignored
```

**Comment by somecallmemike** [comment]
Despite this, is there any plan to make database storage a first class citizen?  We did not see anything in the documentation stating that database storage was not production ready so we went ahead and used it and now it seems we are going to need to use a different product like Baikal or Sabredav (yuck) that are much more difficult to configure.

**Comment by liZe** [comment]
@somecallmemike you can get the current calendars with GET requests, and switch to the filesystem storage (as it uses plain ics files to store the calendars)
