### ISSUE TITLE
Problems starting with Python 3.4

### ISSUE THREAD

**Issue by chris5560** [Kozea/Radicale#274]
I'm trying to build a Radicale packages for OpenWrt Project.
I build one package using Python 2.7 and one using Python 3.4.
Python compiled on XUbuntu 32bit and running OpenWrt x86 inside VirtualBox.
2.7 works fine and starts without problems
3.4 starts with the following error:
```
Traceback (most recent call last):
  File "/usr/bin/radicale", line 32, in <module>
    radicale.__main__.run()
  File "/usr/lib/python3.4/site-packages/radicale/__main__.py", line 134, in run
    server_class, RequestHandler))
  File "/usr/lib/python3.4/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.4/site-packages/radicale/__init__.py", line 80, in __init__
    self.server_bind()
  File "/usr/lib/python3.4/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.4/http/server.py", line 135, in server_bind
    self.server_name = socket.getfqdn(host)
  File "/usr/lib/python3.4/socket.py", line 463, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
```
Is this a Python or a Radicale problem ?
Thanks for support
Christian

**Comment by liZe** [comment]
That's strange, I can't reproduce even if I set a hostname with unicode characters. Is there anything strange in your vbox configuration, like uncommon characters in your hostname? Could you launch Radicale with a debugger to know what `name` is in `socket.py` (launching something like `python3 -m pdb /path/to/radicale.py`, then hitting `c<enter>` and `name<enter>`)?

(Looks like a Python bug: http://stackoverflow.com/questions/23109244/unicodedecodeerror-with-runserver)

**Comment by liZe** [comment]
@chris5560 News about this ticket?

**Comment by liZe** [comment]
No news…
