### ISSUE TITLE
Py3: do_commit() fails with TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by catdog2** [Kozea/Radicale#313]
do_commit() seems to be expecting its arguments as bytes, both path and committer are of type str. Also the paths passed to stage() should be of type bytes according to the dulwich tutorial.

```
Traceback (most recent call last):
File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
self.result = application(self.environ, self.start_response)
File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 332, in __call__
user)
File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 434, in get
collection.write()
File "/usr/lib/python3/dist-packages/radicale/ical.py", line 374, in write
text = serialize(self.tag, self.headers, self.items.values())
File "/usr/lib/python3/dist-packages/radicale/ical.py", line 403, in tag
return props["tag"]
File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
next(self.gen)
File "/usr/lib/python3/dist-packages/radicale/storage/filesystem.py", line 134, in props
json.dump(properties, prop_file)
File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
next(self.gen)
File "/usr/lib/python3/dist-packages/radicale/storage/filesystem.py", line 58, in open
GIT_REPOSITORY.do_commit(path, committer=committer)
File "/usr/lib/python3/dist-packages/dulwich/repo.py", line 597, in do_commit
c.message = self.hooks['commit-msg'].execute(message)
File "/usr/lib/python3/dist-packages/dulwich/hooks.py", line 89, in execute
args = self.pre_exec_callback(*args)
File "/usr/lib/python3/dist-packages/dulwich/hooks.py", line 137, in prepare_msg
f.write(args[0])
TypeError: 'str' does not support the buffer interface
```

**Comment by liZe** [comment]
You're right, I get the error when I launch the tests. But how can this work on Travis? https://travis-ci.org/Kozea/Radicale/jobs/81360710
