### ISSUE TITLE
Cannot start: undefined symbol: SSLv2_method

### ISSUE THREAD

**Issue by szotsaki** [Kozea/Radicale#332]
In openSUSE Leap 42.1 the default Python installation comes with the highly vulnerable SSL2 turned off. Because of that Radicale cannot start any more.

The backtrace:

```
nov 07 20:53:21 linux-suse.hu radicale[8422]: Starting radicale Traceback (most recent call last):
nov 07 20:53:21 linux-suse.hu radicale[8422]: File "/usr/bin/radicale", line 29, in <module>
nov 07 20:53:21 linux-suse.hu radicale[8422]: import radicale.__main__
nov 07 20:53:21 linux-suse.hu radicale[8422]: File "/usr/lib/python2.7/site-packages/radicale/__init__.py", line 37, in <module>
nov 07 20:53:21 linux-suse.hu radicale[8422]: import ssl
nov 07 20:53:21 linux-suse.hu radicale[8422]: File "/usr/lib64/python2.7/ssl.py", line 97, in <module>
nov 07 20:53:21 linux-suse.hu radicale[8422]: import _ssl             # if we can't import it, let the error propagate
nov 07 20:53:21 linux-suse.hu radicale[8422]: ImportError: /usr/lib64/python2.7/lib-dynload/_ssl.so: undefined symbol: SSLv2_method
nov 07 20:53:21 linux-suse.hu startproc[8428]: startproc:  exit status of parent of /usr/bin/radicale: 1
nov 07 20:53:21 linux-suse.hu radicale[8422]: ..failed
```

**Comment by cdpb** [comment]
have a look at #316
