### ISSUE TITLE
type = owner_write broken in 1.1

### ISSUE THREAD

**Issue by lemmi** [Kozea/Radicale#347]
After updating to 1.1 when creating a new Event, radicale returns 407.  I think this is the relevant part from the logs:

```
2016-01-02_00:57:42.32302 Rights type 'owner_write'
2016-01-02_00:57:42.32451 Test if 'user:user/xxx.ics' matches against '.+:.*' from section 'w'
2016-01-02_00:57:42.32492 Section 'w' matches
2016-01-02_00:57:42.32540 user has read access to collection user/xxx.ics/
2016-01-02_00:57:42.32629 Rights type 'owner_write'
2016-01-02_00:57:42.32776 Test if 'user:user/xxx.ics' matches against '.+:.*' from section 'w'
2016-01-02_00:57:42.32816 Section 'w' matches
2016-01-02_00:57:42.32864 user has NO write access to collection user/xxx.ics
```
I replaced the actual user and collection name in the listing, but i don't think it should make a difference in this case.

**Comment by storm77de** [comment]
After searching hours for a solution for this problem, I finally found this. Have the same Problem. Tried some variations in the config but nothing helps.

**Comment by liZe** [comment]
Sorry… It even crashes with Python 3. Does it fix your problem?

**Comment by storm77de** [comment]
Doesn't work for me:

Starting Radicale
Authentication type is htpasswd
registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
Base URL prefix: /
Listening to xxxxxxxxxxxx port 5232
Using SSL
Radicale server ready
PUT request at /myuser/calendar.ics/7dff1b14-9121-48a1-ae0c-605b787395e0.ics received
Request headers:
{'CONTENT_LENGTH': '920',
 'CONTENT_TYPE': 'text/calendar; charset=utf-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': 'Basic c3Rvcm03N2RlOk5pSG9OMWFKYVBhTg==',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_HOST': 'xxxxxxxxxxxxxxxxxx:5232',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_USER_AGENT': 'eM Client/6.0.24144.0',
 'PATH_INFO': '/myuser/calendar.ics/7dff1b14-9121-48a1-ae0c-605b787395e0.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.178.38',
 'REMOTE_HOST': 'xxxxxxxxxxxxxx',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'xxxxxxxxxx',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x76caf0d0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x764ab148>,
 'wsgi.input': <socket._fileobject object at 0x762a14f0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /myuser/calendar.ics/7dff1b14-9121-48a1-ae0c-605b787395e0.ics
Rights type 'owner_write'
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "build/bdist.linux-armv7l/egg/radicale/__init__.py", line 313, in __call__
    self.collect_allowed_items(items, user)
  File "build/bdist.linux-armv7l/egg/radicale/__init__.py", line 192, in collect_allowed_items
    if rights.authorized(user, item, "r"):
  File "build/bdist.linux-armv7l/egg/radicale/rights/regex.py", line 131, in authorized
    _read_from_sections(user or "", collection_url, permission))
  File "build/bdist.linux-armv7l/egg/radicale/rights/regex.py", line 92, in _read_from_sections
    regex.readfp(StringIO(DEFINED_RIGHTS[rights_type]))
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: <???>, line: 2
'        [w]\n'

**Comment by lemmi** [comment]
@storm77de you just posted your password. "HTTP_AUTHORIZATION". you probably should edit the post and change your password everywhere

**Comment by storm77de** [comment]
yeah.. -.- my bad.. to late for me..

**Comment by liZe** [comment]
Well… The fix was working with Python 3 but not Python 2, 83304c13 should work with both.

**Comment by storm77de** [comment]
Thank you Sir. Everything is fine now. :+1:
