### ISSUE TITLE
Docker rewrite alpine

### ISSUE THREAD

**Issue by cdpb** [Kozea/Radicale#361]
Hi, 

I pushed the latest Dockerfile to Radicale, based on debian jessie. 
I want to rewrite the same image based on alpine ( really small base image ).

Comparison between image size:
debian jessie -> 476.5MB
alpine             -> 230.2MB

So the problem is I am not really into python and get the following error message:

```
Logging configuration file '/etc/radicale/logging' not found, using stdout.
Starting Radicale
Authentication type is htpasswd
registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
'bcrypt' backend lacks '$2$' support
Base URL prefix: /
Listening to radicale-mdkzy port 5232
Using SSL
Radicale server ready
```

can somebody support me? 
I'll submit a pull request for the new version if everything works as expected

Dockerfile:
https://gist.github.com/cdpb/9f57735839b369197ed6

Regards

cdpb

**Comment by liZe** [comment]
As explained in [this thread](http://stackoverflow.com/questions/33702304/storing-and-validating-encrypted-password-for-login-in-pyramid), this message warns about a salt mechanism not handled by the bcrypt backend. You can probably fix this by using a different backend, as explained in [the passlib documentation](https://pythonhosted.org/passlib/lib/passlib.hash.bcrypt.html#index-0).

**Comment by liZe** [comment]
@cdpb Is your problem solved?

**Comment by cdpb** [comment]
thank you for the answer, just build a new container with `bcrytor` rather than `bcrypt` and everything works fine. I'll submit a pull request

**Comment by cdpb** [comment]
Didn't work as expected ... forget to change the config value to bcrypt. With `bcryptor` I get the following error:

```
Logging configuration file '/etc/radicale/logging' not found, using stdout.
Starting Radicale
Authentication type is htpasswd
registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
Traceback (most recent call last):
  File "/usr/bin/radicale", line 4, in <module>
    __import__('pkg_resources').run_script('Radicale==1.1.1', 'radicale')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1677, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/Radicale-1.1.1-py2.7.egg/EGG-INFO/scripts/radicale", line 32, in <module>
    
  File "build/bdist.linux-x86_64/egg/radicale/__main__.py", line 150, in run
  File "build/bdist.linux-x86_64/egg/radicale/__init__.py", line 134, in __init__
  File "build/bdist.linux-x86_64/egg/radicale/auth/__init__.py", line 43, in load
  File "build/bdist.linux-x86_64/egg/radicale/auth/htpasswd.py", line 134, in <module>
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 558, in encrypt
    self.checksum = self._calc_checksum(secret)
  File "/usr/lib/python2.7/site-packages/passlib/handlers/bcrypt.py", line 406, in _calc_checksum
    self.get_backend()
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 1365, in get_backend
    cls.set_backend()
  File "/usr/lib/python2.7/site-packages/passlib/handlers/bcrypt.py", line 285, in set_backend
    backend = super(bcrypt, cls).set_backend(*a, **k)
  File "/usr/lib/python2.7/site-packages/passlib/utils/handlers.py", line 1442, in set_backend
    raise exc.MissingBackendError(cls._no_backends_msg())
passlib.exc.MissingBackendError: no bcrypt backends available -- recommend you install one (e.g. 'pip install bcrypt')
Cleaning up
```

**Comment by liZe** [comment]
As explained in the link given in previous comment, PassLib tries to load different backends, including bcryptor. Are you sure that you installed bcryptor for Python 2.7? If you're sure you did, then you can ask a question to the PassLib maintainers.

**Comment by cdpb** [comment]
I assume it's Python 2.7 if it's in the associated folder

```
~ $ pip show bcryptor
---
Metadata-Version: 1.1
Name: bcryptor
Version: 1.2.2
Summary: Python wrapper for bcrypt
Home-page: http://www.bitbucket.org/ares/bcryptor/
Author: Jonas Melian
Author-email: jonas@mailup.net
License: UNKNOWN
Location: /usr/lib/python2.7/site-packages
Requires: Cython, Yamlog
```

I'll try to contact passlib maintainers

Thanks so far @liZe

**Comment by cdpb** [comment]
merged - thanks for help @liZe
