### ISSUE TITLE
Radicale stops working after some time

### ISSUE THREAD

**Issue by konmax** [Kozea/Radicale#388]
Hi,

I use the latest version of Radicale (1.1.1) on a Win 7 Prof box and it works great except that it stops working after some time. I use it in standalone mode without a real web server in front of it and I know that the python web server has some issues and stops processing requests after some time. In the past, this happened from time to time and was never a big deal for me. However, something seem the have changed and now Radicale stops working after 1 or 2 days and this is really annoying. Whenever this happens, I can see this output in the console window:

```
C:\xxx\Radicale>set RADICALE_CONFIG=c:\xxx\Radicale\config

C:\xxx\Radicale>title Radicale CalDav Server

C:\xxx\Radicale>cd c:\xxx\Radicale

C:\xxx\Radicale>set PYTHONIOENCODING=utf-8

C:\xxx\Radicale>"C:\Program Files (x86)\Python34\python.exe" radicale.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 453, in _write
    self.stdout.write(data)
  File "C:\Program Files (x86)\Python34\lib\socket.py", line 394, in write
    return self._sock.send(b)
  File "C:\Program Files (x86)\Python34\lib\ssl.py", line 684, in send
    v = self._sslobj.write(data)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
----------------------------------------
Exception happened during processing of request from ('178.26.196.8', 4813)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 453, in _write
    self.stdout.write(data)
  File "C:\Program Files (x86)\Python34\lib\socket.py", line 394, in write
    return self._sock.send(b)
  File "C:\Program Files (x86)\Python34\lib\ssl.py", line 684, in send
    v = self._sslobj.write(data)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 673, in __init__
    self.handle()
  File "C:\Program Files (x86)\Python34\lib\wsgiref\simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "C:\Program Files (x86)\Python34\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Program Files (x86)\Python34\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

Is that something unrelated (no real error) or is this the real cause for this?!

Thanks
Konrad

**Comment by liZe** [comment]
Probably a duplicate of #266.

**Comment by liZe** [comment]
Is this bug fixed with the current `master` branch? (You should try with a clean install because a lot of things have changed since 1.x)

**Comment by konmax** [comment]
Hi Guillaume,

I tried to test the latest version but I wasn't able to set it up as 
expected. Is the auth mode IMAP still supported?





Thanks
Konrad

Am 14.07.2016 um 01:58 schrieb Guillaume Ayoub:

**Comment by liZe** [comment]
@konmax No, authentication modules have been removed and will be allowed as plugins (everything is explained in #372). The storage has changed too. That's why tests are easier with a fresh new install.

**Comment by konmax** [comment]
Hi Guillaume,

Not sure if I can follow. Seems like you have removed some features in 
order to keep the "core" as clean as possible, but from an "upgrade" 
point of view, this is a very complicated situation. Is there already an 
IMAP auth plugin available? And can I migrate existing "rights" and 
calendar and contact files?

Thanks for your support!

Konrad


Am 14.07.2016 um 21:32 schrieb Guillaume Ayoub:

**Comment by liZe** [comment]
Don't panic :smile::
- The 1.x versions won't disappear. Even if no new features will be added, we'll fix small bugs, security bugs, and release minor versions of 1.1.
- The 2.0 is not out yet. Now that the core features have been added (there's only a couple of bugs to solve before), it's time to write documentation and plugins. Auth and rights plugins can be easily taken from the current code, and even if nobody wants to officially take care of a plugin, you can take it and keep it for yourself :wink:.
- We won't let our users alone to migrate their calendars and contacts from 0.x and 1x to 2.0! An easy way for many users is to GET their collections (even a browser can do that) from the old version and PUT them to the new version (your CalDAV client can probably do that). For users with many collections, it's probably easy to write a script, and that script can be included in the repository with a link in the documentation.

Of course, 2.0 will also provide a lot of new interesting features, including multiprocess that has hopefully fixed this bug!

**Comment by konmax** [comment]
Thanks!

I will then "keep an eye" on v2 (sounds really promissing) and wait for 
it to "grow"into something which can actually replace v1 with all the 
requirements we have. v1 does a good job here, so there is no need to 
upgrade for now...

Konrad

Am 15.07.2016 um 13:58 schrieb Guillaume Ayoub:

**Comment by liZe** [comment]
This issue is definitely closed in master.
