### ISSUE TITLE
radicale now gives 500 internal error whenever syncing

### ISSUE THREAD

**Issue by sudoman** [Kozea/Radicale#415]
i see in my logs two of the first error, then the second, all three occurring within the same second. now whenever i sync I get the last error without the first one.

````
Traceback (most recent call last):
File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.4/socketserver.py", line 669, in __init__
self.handle()
File "/usr/lib/python3.4/wsgiref/simple_server.py", line 118, in handle
self.raw_requestline = self.rfile.readline(65537)
File "/usr/lib/python3.4/socket.py", line 371, in readinto
return self._sock.recv_into(b)
File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
return self.read(nbytes, buffer)
File "/usr/lib/python3.4/ssl.py", line 617, in read
v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1769)
````

````
File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
self.result = application(self.environ, self.start_response)
File "/usr/local/lib/python3.4/dist-packages/radicale/__init__.py", line 332, in __call__
user)
File "/usr/local/lib/python3.4/dist-packages/radicale/__init__.py", line 588, in do_PUT
xmlutils.put(environ["PATH_INFO"], content, collection)
File "/usr/local/lib/python3.4/dist-packages/radicale/xmlutils.py", line 453, in put
collection.append(name, ical_request)
File "/usr/local/lib/python3.4/dist-packages/radicale/ical.py", line 357, in append
text, (Timezone, Event, Todo, Journal, Card), name)
File "/usr/local/lib/python3.4/dist-packages/radicale/ical.py", line 324, in _parse
lines = unfold(text)
File "/usr/local/lib/python3.4/dist-packages/radicale/ical.py", line 63, in unfold
return re.sub('\r\n( |\t)', '', text).splitlines()
File "/usr/lib/python3.4/re.py", line 175, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
````

**Comment by sudoman** [comment]
It appears this was a DAVdroid issue that was fixed by its latest update in F-Droid.
