### ISSUE TITLE
v1.1.1 - AttributeError in do_HEAD

### ISSUE THREAD

**Issue by Leryan** [Kozea/Radicale#483]
Hi,

In a fresh `radicale v1.1.1` installed, I have an `AttributeError`:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/radical/pyvenv-radicale/lib/python2.7/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/home/radical/pyvenv-radicale/lib/python2.7/site-packages/radicale/__init__.py", line 456, in do_HEAD
    status, headers, answer = self.get(
AttributeError: 'Application' object has no attribute 'get'
```

This happens when I want to delete an event. The client is the current addon `lightning` for `thunderbird`:

```
185.31.151.126 - user [18/Aug/2016:14:07:26 +0200] "DELETE /caldav/user/ HTTP/1.1" 412 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Thunderbird/45.2.0 Lightning/4.7" "-"
185.31.151.126 - user [18/Aug/2016:14:07:26 +0200] "HEAD /caldav/user/ HTTP/1.1" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Thunderbird/45.2.0 Lightning/4.7" "-"
```

The event isn't deleted at all.

**Comment by Leryan** [comment]
Woops… this was already reported: https://github.com/Kozea/Radicale/issues/394

Bad search…
