### ISSUE TITLE
encoding response

### ISSUE THREAD

**Issue by stephane-martin** [Kozea/Radicale#505]
Hello,

I tried to run radicale (HEAD) under waitress WSGI server and python 3.

I get this when the client requests .well-known:

```
GET request at /.well-known/caldav received
Exception when serving /.well-known/caldav
Traceback (most recent call last):
  File "/home/radicale/env_radicale/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/radicale/env_radicale/lib/python3.5/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/radicale/env_radicale/lib/python3.5/site-packages/waitress/task.py", line 437, in execute
    self.write(chunk)
  File "/home/radicale/env_radicale/lib/python3.5/site-packages/waitress/task.py", line 303, in write
    channel.write_soon(towrite)
  File "/home/radicale/env_radicale/lib/python3.5/site-packages/waitress/channel.py", line 320, in write_soon
    self.outbufs[-1].append(data)
  File "/home/radicale/env_radicale/lib/python3.5/site-packages/waitress/buffers.py", line 239, in append
    self.strbuf = strbuf + s
TypeError: can't concat bytes to str
```

Looking at `radicale/__init__.py`, class `Application`, method `__call__`:
- under normal circumstances, the response is encoded (`answer = answer.encode(self.encoding)` on line 369)
- but when something is wrong with the request, usually there is something like `return response(*NOT_FOUND)`

`NOT_FOUND` and the others are tuples that contain (unicode) strings. So we can a mix of bytes and unicode, and the WGSI layer cries...

Could you please encode the response in all cases ?

Thanks,
Stephane

**Comment by liZe** [comment]
It's probably caused by #501. @Unrud do you have the time to look at this?

**Comment by Unrud** [comment]
#506 should fix it.
