### ISSUE TITLE
Broken ICS file will lead to uncatched exception instead of skip and log on warn level

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#516]
While testing "master" I found during migration tests with real data that one of my calendar entries was broken, resulting in an exception and calendar entries are not sent to client:

2016-09-15 19:27:03,551 - [7f384fec5700] ERROR: An exception occurred during request:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python3.4/site-packages/radicale/**init**.py", line 379, in **call**
    status, headers, answer = function(environ, path, user)
  File "/usr/lib/python3.4/site-packages/radicale/**init**.py", line 572, in do_PROPFIND
    path, content, read_items, write_items, user)
  File "/usr/lib/python3.4/site-packages/radicale/xmlutils.py", line 525, in propfind
    path, collection, props, user, write=True)
  File "/usr/lib/python3.4/site-packages/radicale/xmlutils.py", line 658, in _propfind_response
    element.text = item.etag
  File "/usr/lib/python3.4/site-packages/radicale/storage.py", line 265, in etag
    return get_etag(self.serialize())
  File "/usr/lib/python3.4/site-packages/radicale/storage.py", line 711, in serialize
    items.append(vobject.readOne(fd.read()))
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 1129, in readOne
    allowQP))
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 1115, in readComponents
    (stack.topName())), n)
vobject.base.ParseError: At line 15: Component VEVENT was never closed

Had to extend storage.py with logging of each read file to get the broken file name

```
        if os.path.isfile(path):
            self.logger.debug("read object: %s", path)  <- new
```

Please catch the exception, log the broken object "path" on warn, skip it and continue parsing next files.

**Comment by pbiering** [comment]
patch proposed in https://github.com/Kozea/Radicale/pull/517

**Comment by liZe** [comment]
#517 is merged, thanks!
