### ISSUE TITLE
[Security] Permission denied when syncing CardDAV with Davdroid

### ISSUE THREAD

**Issue by tomsquest** [Kozea/Radicale#528]
Hello,

Radicale logs a permission denied when syncing CardDAV from Davdroid. I seems that Radicale has been sent the instruction to read `/data.props` from Davdroid.
This is maybe ok, but it seems that this path is _directly_ read by Radicale, **escaping** the configured filesystem folder ; ie. Radicale does not attempt to read `FOLDER/data.props`.   
It could be a security issue where the remote can ask Radicale to read any file on disk.

Here is the python code (tag: 1.1.1):
```python
# radicale/storage/filesystem.py
def open(path, mode="r"):
    # ...
    abs_path = os.path.join(FOLDER, path.replace("/", os.sep))
```

Or, `os.path.join` does not `join` if one of the argument is absolute, which is the case (`path=/data.props`). So `abs_path` equals `/data.props`.

```shell
$ python                                                                                                                                                              
>>> FOLDER = '/home/radicale'
>>> import os
>>> os.path.join(FOLDER, "/data.props")
'/data.props'
```

Stacktrace:
```
2016-10-12 09:15:18,475 - DEBUG: Request content:
<?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><current-user-privilege-set /><displayname /><CARD:addressbook-description /><CARD:supported-address-data /><CAL:calendar-description /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:supported-calendar-component-set /></prop></propfind>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/usr/local/lib/python3.5/site-packages/radicale/__init__.py", line 548, in do_PROPFIND
    environ["PATH_INFO"], content, collections, user)
  File "/usr/local/lib/python3.5/site-packages/radicale/xmlutils.py", line 237, in propfind
    response = _propfind_response(path, collection, props, user)
  File "/usr/local/lib/python3.5/site-packages/radicale/xmlutils.py", line 346, in _propfind_response
    element.text = item.color
  File "/usr/local/lib/python3.5/site-packages/radicale/ical.py", line 442, in color
    return props["ICAL:calendar-color"]
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/radicale/storage/filesystem.py", line 143, in props
    with open(self._props_path, "w") as prop_file:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/radicale/storage/filesystem.py", line 52, in open
    with codecs.open(abs_path, mode, config.get("encoding", "stock")) as fd:
  File "/usr/local/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/data.props'
```

**Comment by liZe** [comment]
That's not normal. Is it possible to have your config and the lines before your stacktrace please?

**Comment by tomsquest** [comment]
Config file: https://github.com/tomsquest/docker-radicale/blob/master/config/config

Debug mode enabled, full output:

```
2016-10-12 09:15:18,112 - DEBUG: Answer status: 207 Multi-Status
2016-10-12 09:15:18,473 - INFO: PROPFIND request at / received
2016-10-12 09:15:18,474 - DEBUG: Request headers:
{'CONTENT_LENGTH': '422',
 'CONTENT_TYPE': 'application/xml; charset=utf-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_ACCEPT_LANGUAGE': 'en-US, en;q=0.7, *;q=0.5',
 'HTTP_AUTHORIZATION': 'Basic '  'coucou',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': '127.0.0.1:5232',
 'HTTP_USER_AGENT': 'DAVdroid/1.3.1-ose (2016/09/21; dav4android; okhttp3) '
                    'Android/6.0.1',
 'HTTP_X_FORWARDED_FOR': '80.215.1.49',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '172.17.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '89b8c59d212e',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=5>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2016-10-12 09:15:18,474 - DEBUG: Sanitized path: /
2016-10-12 09:15:18,474 - DEBUG: tom has read access to collection /
2016-10-12 09:15:18,474 - DEBUG: tom has write access to collection /
2016-10-12 09:15:18,474 - DEBUG: tom has read access to collection tom/
2016-10-12 09:15:18,474 - DEBUG: tom has write access to collection tom/
2016-10-12 09:15:18,474 - DEBUG: tom has read access to collection d0fac376-e80f-4c39-9c41-68e67aff8741/
2016-10-12 09:15:18,474 - DEBUG: tom has write access to collection d0fac376-e80f-4c39-9c41-68e67aff8741/
2016-10-12 09:15:18,475 - DEBUG: Request content:
<?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><current-user-privilege-set /><displayname /><CARD:addressbook-description /><CARD:supported-address-data /><CAL:calendar-description /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:supported-calendar-component-set /></prop></propfind>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/usr/local/lib/python3.5/site-packages/radicale/__init__.py", line 548, in do_PROPFIND
    environ["PATH_INFO"], content, collections, user)
  File "/usr/local/lib/python3.5/site-packages/radicale/xmlutils.py", line 237, in propfind
    response = _propfind_response(path, collection, props, user)
  File "/usr/local/lib/python3.5/site-packages/radicale/xmlutils.py", line 346, in _propfind_response
    element.text = item.color
  File "/usr/local/lib/python3.5/site-packages/radicale/ical.py", line 442, in color
    return props["ICAL:calendar-color"]
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/radicale/storage/filesystem.py", line 143, in props
    with open(self._props_path, "w") as prop_file:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/radicale/storage/filesystem.py", line 52, in open
    with codecs.open(abs_path, mode, config.get("encoding", "stock")) as fd:
  File "/usr/local/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/data.props'
2016-10-12 09:15:18,672 - INFO: PROPFIND request at /tom/ received
```

**Comment by liZe** [comment]
Thanks a lot. That's not exactly a bug, and for sure not a real security problem.

DAV collections (folders, calendars) are stored on the filesystem, as folders for DAV folders, as files for CalDAV calendars. Collections' properties are stored at the same level as the collection, in a file called `<collection_filename>.props`. As the `/` DAV folder is stored in `/data` on your filesystem, its properties are stored in `/data.props`.

Storing a file outside the config's root folder is definitely not a good thing, that's why it's been fixed in the 2.x versions. But as it's not that bad, and to keep the backward compatibility, I think that it won't be fixed for the 1.1.x versions.

**Comment by tomsquest** [comment]
WIll setting the data folder within a subfolder do the trick ?
eg. `filesystem_folder = /radicale/data` (instead of just `/data`)

**Comment by liZe** [comment]
> WIll setting the data folder within a subfolder do the trick ?

Of course. The props will be stored in `/radicale/data.props`.

**Comment by tomsquest** [comment]
Problem fixed ! Thanks @liZe
