### ISSUE TITLE
Empty REPORT request results in a traceback

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#567]
Sending

`curl --compressed --data-binary '' --header 'Depth: 0' --header 'Content-Type: text/xml' --header Brief:t --request REPORT -u USER:PASS https://cdav.domain.example:18443`

results in

```
[7f8131a06700] INFO: [302afcc] REPORT request  for /USER/ with depth 0 received from **** (forwarded by 127.0.0.1) using "curl/7.51.0"
[7f8131a06700] ERROR: An exception occurred during request:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python3.4/site-packages/radicale/__init__.py", line 437, in __call__
    environ, base_prefix, path, user)
  File "/usr/lib/python3.4/site-packages/radicale/__init__.py", line 724, in do_REPORT
    answer = xmlutils.report(base_prefix, path, content, collection)
  File "/usr/lib/python3.4/site-packages/radicale/xmlutils.py", line 824, in report
    root = ET.fromstring(xml_request.encode("utf8"))
AttributeError: 'NoneType' object has no attribute 'encode'

```

There was a related fix for PROPFIND in commit 32134952450c30b1f4e474e2b2abc4cce34b57d5 but looks like forgotten for REPORT, unfortunatly, it can't be simply taken over (except "if xml_request else None", which will not proper solve it because the following "find" fails then....)

**Comment by Unrud** [comment]
I can't find REPORT requests with empty bodies in the spec. It should be the correct behavior to fail. (Technically 500 is not the correct HTTP status code but I can't imagine that any client cares.)
