### ISSUE TITLE
Uncatched exception when remote host closes connection

### ISSUE THREAD

**Issue by Ede123** [Kozea/Radicale#585]
Just saw the following in my Radicale 1.1.1 log after noticing my calendars weren't synchronized anymore:

```
Answer status: 207 Unknown
----------------------------------------
Exception happened during processing of request from ('xxx.xxx.xxx.xxx', 43831)
Traceback (most recent call last):
  File "C:\Python34\lib\socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python34\lib\socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "C:\Python34\lib\socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python34\lib\socketserver.py", line 673, in __init__
    self.handle()
  File "C:\Python34\lib\wsgiref\simple_server.py", line 118, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Python34\lib\socket.py", line 378, in readinto
    return self._sock.recv_into(b)
  File "C:\Python34\lib\ssl.py", line 748, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python34\lib\ssl.py", line 620, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remo
tehost geschlossen
----------------------------------------
```

I don't know if this is something that even can be fixed in Radicale (as the traceback does not mention any Radicale function), but obviously the client should not be able to crash Radicale by closing the connection, so if there's anything that *can* be done, it certainly *should*.

**Comment by pbiering** [comment]
closed as related to really old verison, please reopen if reproducable with current version
