### ISSUE TITLE
KeyError: rrule

### ISSUE THREAD

**Issue by lpirl** [Kozea/Radicale#628]
Because of #626 , I just tried the master branch and experienced:
<pre>
Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.5/site-packages/vobject/base.py", line 524, in __getattr__
    return self.contents[toVName(name)][0]
KeyError: 'rrule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1016, in _get_with_metadata
    vobject_item)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 586, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 280, in _visit_time_ranges
    if (";UNTIL=" not in child.rrule.value and
  File "/home/lukas/.local/lib/python3.5/site-packages/vobject/base.py", line 526, in __getattr__
    raise AttributeError(name)
AttributeError: rrule

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/__init__.py", line 300, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/__init__.py", line 462, in _handle_request
    environ, base_prefix, path, user)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/__init__.py", line 721, in do_PROPFIND
    base_prefix, path, xml_content, read_items, write_items, user)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 714, in propfind
    base_prefix, path, collection, props, user, write=True)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 895, in _propfind_response
    element.text = item.etag
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1210, in etag
    for item in self.get_all():
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1066, in <genexpr>
    return (self.get(href, verify_href=False) for href in self.list())
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 962, in get
    item, metadata = self._get_with_metadata(href, verify_href=verify_href)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1020, in _get_with_metadata
    e)) from e
RuntimeError: Failed to find tag and time range of item '562476b4-d59f-4915-88e3-36008b1e1693.ics' from 'lukas/cal': rrule
</pre>

**Comment by Unrud** [comment]
Can you provide the content of ``562476b4-d59f-4915-88e3-36008b1e1693.ics``. You can remove private data like ``SUMMARY``, ``LOCATION`` and ``DESCRIPTION``.

**Comment by lpirl** [comment]
Thanks @Unrud for taking care. Here we go:
<pre>
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
BEGIN:VTIMEZONE
TZID:Pacific/Auckland
BEGIN:STANDARD
DTSTART:19700405T030000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=4
TZNAME:NZST
TZOFFSETFROM:+1300
TZOFFSETTO:+1200
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700927T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=9
TZNAME:NZDT
TZOFFSETFROM:+1200
TZOFFSETTO:+1300
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:562476b4-d59f-4915-88e3-36008b1e1693
DTSTART;TZID=Pacific/Auckland:20151020T160000
DTEND;TZID=Pacific/Auckland:20151109T160000
CREATED:20151013T053417Z
DTSTAMP:20151019T090053Z
LAST-MODIFIED:20151019T090053Z
RDATE;VALUE=DATE-TIME:20151020T030000Z
X-MOZ-FAKED-MASTER:1
X-MOZ-GENERATION:3
END:VEVENT
BEGIN:VEVENT
UID:562476b4-d59f-4915-88e3-36008b1e1693
RECURRENCE-ID;TZID=Pacific/Auckland:20151020T160000
DTSTART;TZID=Pacific/Auckland:20151021T160000
DTEND;TZID=Pacific/Auckland:20151021T180000
CREATED:20151013T053407Z
DESCRIPTION:---removed---
DTSTAMP:20151019T090053Z
LAST-MODIFIED:20151019T090053Z
LOCATION:---removed---
SEQUENCE:5
SUMMARY:---removed---
X-MOZ-GENERATION:10
END:VEVENT
END:VCALENDAR
</pre>

**Comment by Unrud** [comment]
It should not crash anymore.

**Comment by lpirl** [comment]
Where can I find the change – the last commit I see on master is from June 7?

**Comment by lpirl** [comment]
Thanks, @Unrud, this seems to be resolved.
