### ISSUE TITLE
Radicale failing to start

### ISSUE THREAD

**Issue by yaomtc** [Kozea/Radicale#645]
I noticed Radicale is failing to start. Trying to figure out why. The system journal has been repeating this:

```
Jun 22 21:48:44 raspberrypi systemd[1]: radicale.service: main process exited, code=exited, status=1/FAILURE
Jun 22 21:48:44 raspberrypi systemd[1]: Unit radicale.service entered failed state.
Jun 22 21:48:44 raspberrypi systemd[1]: radicale.service holdoff time over, scheduling restart.
Jun 22 21:48:44 raspberrypi systemd[1]: Stopping A simple CalDAV (calendar) and CardDAV (contact) server...
Jun 22 21:48:44 raspberrypi systemd[1]: Starting A simple CalDAV (calendar) and CardDAV (contact) server...
Jun 22 21:48:44 raspberrypi systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
Jun 22 21:48:47 raspberrypi systemd[1]: radicale.service: main process exited, code=exited, status=1/FAILURE
Jun 22 21:48:47 raspberrypi systemd[1]: Unit radicale.service entered failed state.
Jun 22 21:48:47 raspberrypi systemd[1]: radicale.service holdoff time over, scheduling restart.
Jun 22 21:48:47 raspberrypi systemd[1]: Stopping A simple CalDAV (calendar) and CardDAV (contact) server...
Jun 22 21:48:47 raspberrypi systemd[1]: Starting A simple CalDAV (calendar) and CardDAV (contact) server...
Jun 22 21:48:47 raspberrypi systemd[1]: Started A simple CalDAV (calendar) and CardDAV (contact) server.
```

And the radicale log is repeating this:

```
OSError: [Errno 99] Cannot assign requested address
2017-06-22 22:06:34,760 - INFO: Starting Radicale
2017-06-22 22:06:36,652 - ERROR: An exception occurred during server startup:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/radicale/__main__.py", line 111, in run
    serve(configuration, logger)
  File "/usr/local/lib/python3.4/dist-packages/radicale/__main__.py", line 193, in serve
    address, port, application, server_class, RequestHandler)
  File "/usr/lib/python3.4/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/local/lib/python3.4/dist-packages/radicale/__init__.py", line 150, in __init__
    self.server_bind()
  File "/usr/lib/python3.4/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.4/http/server.py", line 133, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.4/socketserver.py", line 440, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address
```

The config file: 
[config.txt](https://github.com/Kozea/Radicale/files/1096310/config.txt)

Pretty sure I have something misconfigured here, but what?

**Comment by bigbig6** [comment]
Hello,

Seems that on line "hosts = 0.0.0.0:5232,[mydomain.com]:5232" , you don't need "[mydomain.com]:5232", only the first part.

Regards,

Big

**Comment by yaomtc** [comment]
That fixed it! Thanks. Though, why would the actual address be "/chris/53ca814e-6c3a-4538-8ac9-d8991e9abda5/" rather than "/chris/calendar.ics"?

**Comment by Unrud** [comment]
> Though, why would the actual address be "/chris/53ca814e-6c3a-4538-8ac9-d8991e9abda5/" rather than "/chris/calendar.ics"?

The client that creates the calendar chooses the name.

**Comment by yaomtc** [comment]
Oh, okay. Thanks for the info.
