### ISSUE TITLE
JSONDecodeError migrating 1.x storage to 2.x

### ISSUE THREAD

**Issue by kmaris** [Kozea/Radicale#669]
I'm running on ArchLinux and using the versions from the aur. I moved my 1.x radicale collections to /var/lib/radicale1 and am going to use /var/lib/radicale as the root of 2.x collections. I've changed my 1.x config to point to the /var/lib/radicale1 collections, and am trying to use radicale 1.1.4 in a virtualenv to export the old storage, the system's radicale version is 2.1.1. This command to migrate fails for me (along with trying several variations of collections locations):

```
(radup) # radicale --version
1.1.4
(radup) # radicale -C /etc/radicale/config.v1 --export-storage=/var/lib/radicale
INFO: Exporting storage for Radicale 2.0.0 to '/var/lib/radicale'
Traceback (most recent call last):
  File "/root/.virtualenvs/radup/bin/radicale", line 32, in <module>
    radicale.__main__.run()
  File "/root/.virtualenvs/radup/lib/python3.6/site-packages/radicale/__main__.py", line 162, in run
    export_storage(config, options.export_storage)
  File "/root/.virtualenvs/radup/lib/python3.6/site-packages/radicale/__main__.py", line 70, in export_storage
    with collection.props as props:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/root/.virtualenvs/radup/lib/python3.6/site-packages/radicale/storage/filesystem.py", line 137, in props
    properties.update(json.load(prop_file))
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
The presence of /var/lib/radicale/collections.props makes no difference.

EDIT: There is no extra output when using the -D option.

**Comment by Unrud** [comment]
Please test again with version 1.1.5. I've added more logging output for this case.

**Comment by kmaris** [comment]
Here ya go:

```
(radup) root@host ~ > radicale --version                                                                   
1.1.6
(radup) root@host ~ > radicale -D -C /etc/radicale/config.v1 --export-storage=/var/lib/radicale/collections
Logging configuration file '' not found, using stdout.
INFO: Exporting storage for Radicale 2.0.0 to '/var/lib/radicale/collections'
DEBUG: Exporting collection '/'
DEBUG: Exporting collection '/kmaris'
ERROR: Failed to export collection '/kmaris': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/root/.virtualenvs/radup/lib/python3.6/site-packages/radicale/__main__.py", line 92, in export_storage
    with collection.props as props:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/root/.virtualenvs/radup/lib/python3.6/site-packages/radicale/storage/filesystem.py", line 137, in props
    properties.update(json.load(prop_file))
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
If it helps my python version is 3.6.2. It didn't seem to do any different with 2.7.

**Comment by Unrud** [comment]
Can you provide the content of the file ``/kmaris.props`` from the old storage folder?

**Comment by kmaris** [comment]
/var/lib/radicale1/collections/kmaris.props is empty.

/var/lib/radicale1/collections.props contains:

`{"tag": "VCALENDAR", "ICAL:calendar-color": "#3e599"}`

**Comment by kmaris** [comment]
Got it, I needed to have the content from collections.props in kmaris.props and removed /var/lib/radicale (it complained about the destination already existing).

**Comment by kmaris** [comment]
I think to expand more (and possibly save a future headache for others) during my initial setup of radicale I used two values for the collections location: /var/lib/radicale and /var/lib/radicale/collections. There were artifacts from both settings laying around and giving me confusion.

**Comment by Unrud** [comment]
> /var/lib/radicale1/collections/kmaris.props is empty.

The file should never be empty. Radicale 1.x.x doesn't use atomic file creation, maybe the empty file was left behind after a crash.

> I needed to have the content from collections.props in kmaris.props

That works, if ``/kmaris`` is a calendar.
