### ISSUE TITLE
Upgrade failed: can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by RolandVor** [Kozea/Radicale#673]
Hi!

I wanted to upgrade to the newest version today (came from 1.1.1), but syncing fails with the following errors:

```
[-49fcdb90] ERROR: An exception occurred during PROPFIND request on '[REMOVED]': Failed to find tag and time range of item '[REMOVED].ics' from '[REMOVED]': can't subtract offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/storage.py", line 1224, in _get_with_metadata
    vobject_item)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 605, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 314, in _visit_time_ranges
    original_duration = (dtend - dtstart).total_seconds()
TypeError: can't subtract offset-naive and offset-aware datetimes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/__init__.py", line 298, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/__init__.py", line 464, in _handle_request
    environ, base_prefix, path, user)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/__init__.py", line 744, in do_PROPFIND
    base_prefix, path, xml_content, read_items, write_items, user)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 733, in propfind
    base_prefix, path, collection, props, user, write=True)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 914, in _propfind_response
    element.text = item.etag
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/storage.py", line 1360, in etag
    self._etag_cache = super().etag
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/storage.py", line 476, in etag
    for item in self.get_all():
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/storage.py", line 1275, in <genexpr>
    return (self.get(href, verify_href=False) for href in self.list())
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/storage.py", line 1164, in get
    item, metadata = self._get_with_metadata(href, verify_href=verify_href)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/storage.py", line 1228, in _get_with_metadata
    e)) from e
RuntimeError: Failed to find tag and time range of item '[REMOVED].ics' from '[REMOVED]': can't subtract offset-naive and offset-aware datetimes
```

I converted my calendar entries with the --export-storage option. Did I do something wrong or did I encounter a bug?

Thanks in advance !

EDIT: I attached the ics file which causes the error
[File.ics.txt](https://github.com/Kozea/Radicale/files/1174886/File.ics.txt)

**Comment by Unrud** [comment]
The problem is here:
```
DTSTART;TZID=Europe/London:20170126T150000
DTEND:20170126T170000
```
``DTSTART`` has time zone information and ``DTEND`` is missing them. I don't think that this allowed. You can easily fix it by adding the missing parameter:
```
DTSTART;TZID=Europe/London:20170126T150000
DTEND;TZID=Europe/London:20170126T170000
```

**Comment by RolandVor** [comment]
Thanks a lot, I will try this!
Maybe this is also the reason the file is generated to be so large (I dont know enough about the syntax, but the RDATE repetitions seem strange). The entry in the 1.1.6 version collection is just:

```
BEGIN:VEVENT
LAST-MODIFIED:20170126T090907Z
DTSTAMP:20170126T090907Z
UID:uid-caldavsyncadapter
SUMMARY:[REMOVED]
DTSTART;TZID=Europe/London:20170126T150000
DTEND:20170126T170000
CLASS:PUBLIC
X-RADICALE-NAME:uid-caldavsyncadapter.ics
SEQUENCE:2
X-MOZ-GENERATION:2
END:VEVENT
```

So I will try to fix the original collection and export again to the new storage format. I will report back!

**Comment by Unrud** [comment]
> Maybe this is also the reason the file is generated to be so large

No, the reason is how Radicale 1.x.x works. It extracts the time zones from every uploaded file and then adds them all to every file on download. The exporter does the same.

The ICS file that you provided, contains lots of unneeded time zones.

> but the RDATE repetitions seem strange

Some clients specify every recurrence date explicitly instead of using a recurrence rule (RRULE).
That's not very space efficient.

> So I will try to fix the original collection and export again to the new storage format. 

You can change the already exported files. Radicale 1.x.x doesn't really care about the content of the files. The same is true for the exporter.

**Comment by RolandVor** [comment]
Thanks again!
This problem is solved now (and I optimized the files accordingly), thank you very much!

Unfortunately, a second problem now occurs, I opened a second issue thread for this : #674
