### ISSUE TITLE
Radicale stops working

### ISSUE THREAD

**Issue by RolandVor** [Kozea/Radicale#674]
Hi!

I upgraded to radicale 2.1.2. Syncing now works (I use Thunderbird) for a few minutes / syncing cycles, but radicale seems to stop doing anything after a while:
No new connections are accepted and nothing is output anymore even in DEBUG level.

EDIT: After roughly 20 minutes, radicale continues working (until the next freeze I guess) and throws this error:
```
2017-07-26 18:45:02,842 - [-4a900b90] ERROR: An exception occurred during request: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/__init__.py", line 184, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/radicale/.local/lib/python3.5/site-packages/radicale/__init__.py", line 202, in handle
    super().handle()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 127, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python3.5/http/server.py", line 327, in parse_request
    "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python3.5/http/server.py", line 477, in send_error
    self.wfile.write(body)
  File "/usr/lib/python3.5/socket.py", line 594, in write
    return self._sock.send(b)
  File "/usr/lib/python3.5/ssl.py", line 871, in send
    return socket.send(self, data, flags)
BrokenPipeError: [Errno 32] Broken pipe

```

The last few DEBUG lines (before the freeze) written are:
```
2017-07-26 18:10:44,525 - [-4a900b90] INFO: Successful login: '[REMOVED]'
2017-07-26 18:10:44,526 - [-49f9eb90] INFO: REPORT response status for '/[REMOVED]/Calendar1/' with depth '1' in 0.096 seconds: 207 Multi-Status
2017-07-26 18:10:44,529 - [-4a900b90] DEBUG: Request content:
<?xml version="1.0"?>
<sync-collection xmlns="DAV:">
  <sync-token>http://radicale.org/ns/sync/[REMOVED]</sync-token>
  <sync-level>1</sync-level>
  <prop>
    <getcontenttype />
    <getetag />
  </prop>
</sync-collection>

2017-07-26 18:10:44,531 - [-4a900b90] DEBUG: Client provided sync token: 'http://radicale.org/ns/sync/[REMOVED]'
2017-07-26 18:10:44,594 - [-4a900b90] DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <sync-token>http://radicale.org/ns/sync/[REMOVED]</sync-token>
</multistatus>

2017-07-26 18:10:44,595 - [-4a900b90] INFO: REPORT response status for '/[REMOVED]/Calendar2/' with depth '1' in 0.085 seconds: 207 Multi-Status
```

Should I attach more logging output?

Thanks again in advance!

**Comment by Unrud** [comment]
The log shows a successful (differential) synchronization of ``/[REMOVED]/Calendar2/``.

You don't have to remove the sync-token from the log, it's just a hash of partly random data.

**Comment by RolandVor** [comment]
> You don't have to remove the sync-token from the log, it's just a hash of partly random data.
OK, didnt know this.

> The log shows a successful (differential) synchronization of /[REMOVED]/Calendar2/.
Yes, but I've edited the post, sorry! Radicale gets unstuck after a while with a "broken pipe" error. But shortly after becomes stuck again.

**Comment by Unrud** [comment]
> EDIT: After roughly 20 minutes, radicale continues working (until the next freeze I guess) and throws this error:

Looks like the request was successful, but the client disconnected in the mean time.
The first request on a big calendar / address book (e.g. after importing from 1.x.x) might take a long time, because Radicale has to warm up its internal caches. (It's also possible that the client times out.) All subsequent requests should take less than a second.

> But shortly after becomes stuck again.

This should only happen once per big calendar / address book. I need more logging output.

> No new connections are accepted and nothing is output anymore even in DEBUG level.

In the default configuration only 20 parallel connections are allowed, maybe you reached that limit. If you make lots of parallel requests during the warm-up phase on the same calendar, it might get very slow.

**Comment by RolandVor** [comment]
I have a bit more insight now:
1. Radicale gets stuck, if my phone tries to sync. It uses aCalDAV Sync Adapter. (Worked fine with previous 1.1.1 version and apache module)
2. If I take the phone offline, all works fine. Only Thunderbird syncs and it works just fine.

I report again if I find more / get some useful logging output.

**Comment by RolandVor** [comment]
If you can and want: maybe you can recreate the problem by installing aCalDAV on android (https://play.google.com/store/apps/details?id=de.we.acaldav&hl=de).

The problem occurs already when trying to set up the sync account, even with a fresh user in radicale.

Here is my config file:
```
[server]
max_connections = 30
# 1 Megabyte
max_content_length = 10000000
# 10 seconds
timeout = 10

ssl = True
certificate = /home/radicale/cert.crt
key = /home/radicale/key.key
#ciphers=HIGH:!aNULL:!eNULL

[storage]
filesystem_folder = /home/radicale/collections
hook = git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s)

[auth]
type = htpasswd
htpasswd_filename = /home/radicale/.config/radicale/userauth
# encryption method used in the htpasswd file
htpasswd_encryption = bcrypt

delay = 1


[rights]
type = owner_only
```

**Comment by RolandVor** [comment]
Thank you very much for the fast patch! Seems to work perfectly :)
