### ISSUE TITLE
Error when syncing events for Outlook CalDAV synchronizer

### ISSUE THREAD

**Issue by ayevee** [Kozea/Radicale#701]
When I try to sync event from Outlook using CalDAV synchornizer plugin I get the error clint-side and following warning in debug log:

```
2017-09-11 15:02:00,574 - [49184460] INFO: Successful login: 'ivan'
2017-09-11 15:02:00,578 - [49184460] DEBUG: Request content:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ddaysoftware.com//NONSGML DDay.iCal 1.0//EN
BEGIN:VTIMEZONE
TZID:Russian Standard Time
BEGIN:STANDARD
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;UNTIL=20101231T210000Z;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0;BYM
 ONTH=10
TZNAME:Russia TZ 2 Standard Time
TZOFFSETFROM:+0400
TZOFFSETTO:+0300
END:STANDARD
BEGIN:STANDARD
DTSTART;VALUE=DATE:20110101
RRULE:FREQ=YEARLY;UNTIL=20111231T210000Z;BYDAY=1SA;BYHOUR=0;BYMINUTE=0;BYMO
 NTH=1
TZNAME:Russia TZ 2 Standard Time
TZOFFSETFROM:+0400
TZOFFSETTO:+0300
END:STANDARD
BEGIN:STANDARD
DTSTART;VALUE=DATE:20120102
RRULE:FREQ=YEARLY;UNTIL=20121231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMO
 NTHDAY=1
TZNAME:Russia TZ 2 Standard Time
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:STANDARD
BEGIN:STANDARD
DTSTART;VALUE=DATE:20130102
RRULE:FREQ=YEARLY;UNTIL=20131231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMO
 NTHDAY=1
TZNAME:Russia TZ 2 Standard Time
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:STANDARD
BEGIN:STANDARD
DTSTART:20141026T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=10
TZNAME:Russia TZ 2 Standard Time
TZOFFSETFROM:+0400
TZOFFSETTO:+0300
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;UNTIL=20101231T210000Z;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYM
 ONTH=3
TZNAME:Russia TZ 2 Summer Time
TZOFFSETFROM:+0300
TZOFFSETTO:+0400
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:20110327T020000
RRULE:FREQ=YEARLY;UNTIL=20111231T210000Z;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYM
 ONTH=3
TZNAME:Russia TZ 2 Summer Time
TZOFFSETFROM:+0300
TZOFFSETTO:+0400
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART;VALUE=DATE:20120101
RRULE:FREQ=YEARLY;UNTIL=20121231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMO
 NTHDAY=1
TZNAME:Russia TZ 2 Summer Time
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART;VALUE=DATE:20130101
RRULE:FREQ=YEARLY;UNTIL=20131231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMO
 NTHDAY=1
TZNAME:Russia TZ 2 Summer Time
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART;VALUE=DATE:20140101
RRULE:FREQ=YEARLY;UNTIL=20141231T210000Z;BYDAY=1WE;BYHOUR=0;BYMINUTE=0;BYMO
 NTH=1
TZNAME:Russia TZ 2 Summer Time
TZOFFSETFROM:+0300
TZOFFSETTO:+0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:Гарантийная книжка \nСТС \nСкидочная карта \n
DTEND;TZID=Russian Standard Time:20130330T160000
DTSTAMP:20170911T120201Z
DTSTART;TZID=Russian Standard Time:20130330T130000
LOCATION:Субару-центр Химки
PRIORITY:5
SEQUENCE:0
SUMMARY:ТО
TRANSP:TRANSPARENT
UID:43d71f30-42ff-49ac-b953-f59ddd73a4a1
X-MICROSOFT-CDO-BUSYSTATUS:FREE
END:VEVENT
END:VCALENDAR

2017-09-11 15:02:00,682 - [49184460] WARNING: Bad PUT request on '/ivan/7fafff2d-dc29-0723-d801-0dff332dd32c/43d71f30-42ff-49ac-b953-f59ddd73a4a1.ics': "In transformToNative, unhandled exception on line None: <class 'ValueError'>: unsupported DTSTART parm: VALUE=DATE (<VTIMEZONE| [<TZID{}Russian Standard Time>, <STANDARD| [<DTSTART{}19701025T030000>, <RRULE{}FREQ=YEARLY;UNTIL=20101231T210000Z;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0;BYMONTH=10>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0400>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{'VALUE': ['DATE']}20110101>, <RRULE{}FREQ=YEARLY;UNTIL=20111231T210000Z;BYDAY=1SA;BYHOUR=0;BYMINUTE=0;BYMONTH=1>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0400>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{'VALUE': ['DATE']}20120102>, <RRULE{}FREQ=YEARLY;UNTIL=20121231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{'VALUE': ['DATE']}20130102>, <RRULE{}FREQ=YEARLY;UNTIL=20131231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{}20141026T020000>, <RRULE{}FREQ=YEARLY;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=10>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0400>, <TZOFFSETTO{}+0300>]>, <DAYLIGHT| [<DTSTART{}19700329T020000>, <RRULE{}FREQ=YEARLY;UNTIL=20101231T210000Z;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0400>]>, <DAYLIGHT| [<DTSTART{}20110327T020000>, <RRULE{}FREQ=YEARLY;UNTIL=20111231T210000Z;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0400>]>, <DAYLIGHT| [<DTSTART{'VALUE': ['DATE']}20120101>, <RRULE{}FREQ=YEARLY;UNTIL=20121231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <DAYLIGHT| [<DTSTART{'VALUE': ['DATE']}20130101>, <RRULE{}FREQ=YEARLY;UNTIL=20131231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <DAYLIGHT| [<DTSTART{'VALUE': ['DATE']}20140101>, <RRULE{}FREQ=YEARLY;UNTIL=20141231T210000Z;BYDAY=1WE;BYHOUR=0;BYMINUTE=0;BYMONTH=1>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0400>]>]>)"
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/vobject/base.py", line 185, in transformToNative
    return self.behavior.transformToNative(self)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/vobject/icalendar.py", line 1017, in transformToNative
    obj.registerTzinfo(obj.tzinfo)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/vobject/icalendar.py", line 155, in gettzinfo
    return tz.tzical(buffer).get()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/dateutil/tz/tz.py", line 1154, in __init__
    self._parse_rfc(fobj.read())
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/dateutil/tz/tz.py", line 1275, in _parse_rfc
    cache=True)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/dateutil/rrule.py", line 1605, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/dateutil/rrule.py", line 1564, in _parse_rfc
    raise ValueError("unsupported DTSTART parm: "+parm)
ValueError: unsupported DTSTART parm: VALUE=DATE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/radicale/__init__.py", line 853, in do_PUT
    items = tuple(vobject.readComponents(content or ""))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/vobject/base.py", line 1125, in readComponents
    component.transformChildrenToNative()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/vobject/base.py", line 673, in transformChildrenToNative
    child = child.transformToNative()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/vobject/base.py", line 198, in transformToNative
    raise ParseError(msg, lineNumber)
vobject.base.ParseError: "In transformToNative, unhandled exception on line None: <class 'ValueError'>: unsupported DTSTART parm: VALUE=DATE (<VTIMEZONE| [<TZID{}Russian Standard Time>, <STANDARD| [<DTSTART{}19701025T030000>, <RRULE{}FREQ=YEARLY;UNTIL=20101231T210000Z;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0;BYMONTH=10>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0400>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{'VALUE': ['DATE']}20110101>, <RRULE{}FREQ=YEARLY;UNTIL=20111231T210000Z;BYDAY=1SA;BYHOUR=0;BYMINUTE=0;BYMONTH=1>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0400>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{'VALUE': ['DATE']}20120102>, <RRULE{}FREQ=YEARLY;UNTIL=20121231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{'VALUE': ['DATE']}20130102>, <RRULE{}FREQ=YEARLY;UNTIL=20131231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <STANDARD| [<DTSTART{}20141026T020000>, <RRULE{}FREQ=YEARLY;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=10>, <TZNAME{}Russia TZ 2 Standard Time>, <TZOFFSETFROM{}+0400>, <TZOFFSETTO{}+0300>]>, <DAYLIGHT| [<DTSTART{}19700329T020000>, <RRULE{}FREQ=YEARLY;UNTIL=20101231T210000Z;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0400>]>, <DAYLIGHT| [<DTSTART{}20110327T020000>, <RRULE{}FREQ=YEARLY;UNTIL=20111231T210000Z;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0400>]>, <DAYLIGHT| [<DTSTART{'VALUE': ['DATE']}20120101>, <RRULE{}FREQ=YEARLY;UNTIL=20121231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <DAYLIGHT| [<DTSTART{'VALUE': ['DATE']}20130101>, <RRULE{}FREQ=YEARLY;UNTIL=20131231T210000Z;BYHOUR=0;BYMINUTE=0;BYMONTH=1;BYMONTHDAY=1>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0300>]>, <DAYLIGHT| [<DTSTART{'VALUE': ['DATE']}20140101>, <RRULE{}FREQ=YEARLY;UNTIL=20141231T210000Z;BYDAY=1WE;BYHOUR=0;BYMINUTE=0;BYMONTH=1>, <TZNAME{}Russia TZ 2 Summer Time>, <TZOFFSETFROM{}+0300>, <TZOFFSETTO{}+0400>]>]>)"
2017-09-11 15:02:00,819 - [49184460] DEBUG: Running hook
2017-09-11 15:02:00,855 - [49184460] DEBUG: Response content:
Bad Request
```

**Comment by Unrud** [comment]
>
```
BEGIN:VTIMEZONE
...
BEGIN:STANDARD
DTSTART;VALUE=DATE:20110101
```

The file is invalid. ``VALUE=DATE`` is not allowed here. ``DTSTART`` must be a date with local time value.

[rfc5545-3.6.5](https://tools.ietf.org/html/rfc5545#section-3.6.5):

```
      The mandatory "DTSTART" property gives the effective onset date
      and local time for the time zone sub-component definition.
      "DTSTART" in this usage MUST be specified as a date with a local
      time value.
```

**Comment by ayevee** [comment]
@Unrud it means that this is a client bug, right?

P.S. what about

> Even if it tries it best to follow the RFCs, Radicale does not and will not blindly implements the CalDAV and CardDAV standards. It is mainly designed to support the CalDAV and CardDAV implementations of different clients.

😃

**Comment by Unrud** [comment]
> @Unrud it means that this is a client bug, right?

I haven't checked historic versions of the RFCs, maybe it was even allowed at some point.
If you need a workaround, you have ask at [dateutil](https://github.com/dateutil/dateutil). It's used by [VObject](https://github.com/eventable/vobject) to parse the time zones.

> P.S. what about

Outlook with the CalDAV synchronizer plugin is not listed as a supported client on the website.
Unfortunately the RFCs are pretty extensive. Incomplete implementations and errors are common.

**Comment by ayevee** [comment]
@Unrud, thanks, I've reported this issue client-side (aluxnimm/outlookcaldavsynchronizer#210)
