### ISSUE TITLE
SSL handshake failed when using letsencrypt-generated certificate

### ISSUE THREAD

**Issue by mikaelmoutakis** [Kozea/Radicale#702]
I generated certificates with letsencrypt's certbot. I'm using Radicale 2.1.5 on FreeBSD 11 using python 3.6. My conf-file is:

```
ssl = True
certificate = /home/radicale/cert.pem
key = /home/radicale/privkey.pem
```

The definition of cert.pem and privkey.pem are found [here](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins)

I get the following error:

```
[801f79800] ERROR: An exception occurred during request: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:749)
Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.6/site-packages/radicale/__init__.py", line 182, in process_request_thread
    request.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:749)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.6/site-packages/radicale/__init__.py", line 186, in process_request_thread
    raise RuntimeError("SSL handshake failed: %s" % e) from e
RuntimeError: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:749)
[801f7a200] ERROR: An exception occurred during request: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:749)
Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.6/site-packages/radicale/__init__.py", line 182, in process_request_thread
    request.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:749)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.6/site-packages/radicale/__init__.py", line 186, in process_request_thread
    raise RuntimeError("SSL handshake failed: %s" % e) from e
RuntimeError: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:749)
```

**Comment by Unrud** [comment]
You can choose the SSL protocol version in the configuration:

```
[server]
protocol = PROTOCOL_TLSv1_2
```

Try to set it to ``PROTOCOL_TLS``.

**Comment by mikaelmoutakis** [comment]
I set it to "protocol = PROTOCOL_TLS". The server starts but when I try to access the web interface I get the following stderr output (server set to debug mode):

[801e16000] INFO: Starting Radicale
[801e16000] INFO: Authentication type is 'htpasswd'
[801e16000] INFO: Storage type is 'multifilesystem'
[801e16000] INFO: Rights type is 'owner_only'
[801e16000] INFO: Web type is 'internal'
[801e16000] INFO: Listening to 'freebsd-512mb-fra1-01' on port 5232 using SSL
[801e16000] INFO: Radicale server ready
[801f79800] ERROR: An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:749)
Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.6/site-packages/radicale/__init__.py", line 182, in process_request_thread
    request.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:749)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radicale/.local/lib/python3.6/site-packages/radicale/__init__.py", line 186, in process_request_thread
    raise RuntimeError("SSL handshake failed: %s" % e) from e
RuntimeError: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:749)

**Comment by Unrud** [comment]
Radicale just uses the ``ssl`` module from Python's standard library. I don't know why the certificate doesn't work.

**Comment by Tntdruid** [comment]
I use Let’s Encrypt cert whit no problems on CentOS 7

**Comment by mikaelmoutakis** [comment]
I found the reason for the "RuntimeError: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:749)". Radicale throws that error when you try to access the server without SSL (ie http://) when it is set to serve with SSL. But Radicale does not crash, so I suppose it is working as it should. But it would have been better if Radicale logged e.g. "INFO: Radicale refused unencrypted http connection on port 5232" instead of throwing a RuntimeError. So it is your bug after all! ;-)

**Comment by mikaelmoutakis** [comment]
But big thanks for the help! :-)
