### ISSUE TITLE
Error creating new contact

### ISSUE THREAD

**Issue by orencio** [Kozea/Radicale#720]
Hi, I get this error when I try to create a new contact:

```
root@asw:~# su - radicale -c  "radicale -fSD"
2017-10-04 12:28:15,182 - INFO: Starting Radicale
2017-10-04 12:28:15,183 - DEBUG: Authentication type is htpasswd
2017-10-04 12:28:15,236 - DEBUG: registered 'apr_md5_crypt' handler: <class 'passlib.handlers.md5_crypt.apr_md5_crypt'>
2017-10-04 12:28:15,244 - DEBUG: Base URL prefix: /
2017-10-04 12:28:15,244 - DEBUG: Listening to asw.local port 5232
2017-10-04 12:28:15,246 - DEBUG: Radicale server ready
2017-10-04 12:28:24,402 - INFO: PUT request at /qqw/contactos.vcf/f5d3aeac3fe4dbb6a4e8ff56694c32833182c51a.vcf received
2017-10-04 12:28:24,415 - DEBUG: Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/vcard; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_LANGUAGE': 'es-es, es;q=0.9',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'xxxxxxx.srv:5232',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_TRANSFER_ENCODING': 'chunked',
 'HTTP_USER_AGENT': 'Evolution/3.26.0',
 'PATH_INFO': '/qqw/contactos.vcf/f5d3aeac3fe4dbb6a4e8ff56694c32833182c51a.vcf',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': 'localhost',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'asw.local',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.13',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f34cb02a1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7f34c910fae0>,
 'wsgi.input': <socket._fileobject object at 0x7f34c9074e50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2017-10-04 12:28:24,416 - DEBUG: Sanitized path: /qqw/contactos.vcf/f5d3aeac3fe4dbb6a4e8ff56694c32833182c51a.vcf
2017-10-04 12:28:25,881 - DEBUG: Anonymous has read access to collection qqw/contactos.vcf/
2017-10-04 12:28:25,883 - DEBUG: Anonymous has write access to collection qqw/contactos.vcf/
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 591, in do_PUT
    xmlutils.put(environ["PATH_INFO"], content, collection)
  File "/usr/lib/python2.7/dist-packages/radicale/xmlutils.py", line 453, in put
    collection.append(name, ical_request)
  File "/usr/lib/python2.7/dist-packages/radicale/ical.py", line 357, in append
    text, (Timezone, Event, Todo, Journal, Card), name)
  File "/usr/lib/python2.7/dist-packages/radicale/ical.py", line 324, in _parse
    lines = unfold(text)
  File "/usr/lib/python2.7/dist-packages/radicale/ical.py", line 63, in unfold
    return re.sub('\r\n( |\t)', '', text).splitlines()
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
^C
Sesión finalizada, parando la consola ...2017-10-04 12:28:42,629 - INFO: Stopping Radicale
2017-10-04 12:28:42,629 - DEBUG: Closing server listening to asw.local port 5232
2017-10-04 12:28:43,119 - DEBUG: Cleaning up
 ... parada.
```

My radicale version is:

```
root@asw:~# dpkg -l "radicale*"
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre            Versión       Arquitectura  Descripción
+++-=================-=============-=============-========================================
ii  radicale          1.1.1+2016011 all           simple calendar and addressbook server -
```

How can I solve it?

Regards.

**Comment by Tntdruid** [comment]
Upgrade to 2.x.x?

**Comment by orencio** [comment]
I've upgraded to 2.1.5-1:

```
# dpkg -l "radicale"
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                                 Versión                  Arquitectura             Descripción
+++-======================================-========================-========================-==================================================================================
ii  radicale                               2.1.5-1                  all                      simple calendar and addressbook server - daemon
```

I've migrated store (<http://radicale.org/1to2/>) and I can access to the content but I can't create new contacts yet. I get this error:

```
root@asw:~# su - radicale -c "radicale -f -S -D -C /etc/radicale/config"
2017-10-05 13:36:43,412 - INFO: Starting Radicale
2017-10-05 13:36:43,413 - INFO: Authentication type is 'htpasswd'
2017-10-05 13:36:43,459 - DEBUG: registered 'apr_md5_crypt' handler: <class 'passlib.handlers.md5_crypt.apr_md5_crypt'>
2017-10-05 13:36:43,459 - INFO: Storage type is 'multifilesystem'
2017-10-05 13:36:43,460 - INFO: Rights type is 'owner_only'
2017-10-05 13:36:43,460 - INFO: Web type is 'internal'
2017-10-05 13:36:43,464 - INFO: Listening to 'localhost' on port 5232
2017-10-05 13:36:43,465 - INFO: Radicale server ready
2017-10-05 13:36:48,791 - INFO: PUT request for '/qqw/contactos.vcf/8050567579f3dc27a7554361d8621187d9c047c3.vcf' received from 127.0.0.1 using 'Evolution/3.26.0'
2017-10-05 13:36:48,802 - DEBUG: Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/vcard; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_LANGUAGE': 'es-es, es;q=0.9',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'xxxxxxx.srv:5232',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_TRANSFER_ENCODING': 'chunked',
 'HTTP_USER_AGENT': 'Evolution/3.26.0',
 'PATH_INFO': '/qqw/contactos.vcf/8050567579f3dc27a7554361d8621187d9c047c3.vcf',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7fc27378a558>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2017-10-05 13:36:48,803 - DEBUG: Sanitized script name: ''
2017-10-05 13:36:48,803 - DEBUG: Sanitized path: '/qqw/contactos.vcf/8050567579f3dc27a7554361d8621187d9c047c3.vcf'
2017-10-05 13:36:48,808 - INFO: Successful login: 'qqw'
2017-10-05 13:36:48,816 - DEBUG: Request content:

2017-10-05 13:36:48,910 - WARNING: Bad PUT request on '/qqw/contactos.vcf/8050567579f3dc27a7554361d8621187d9c047c3.vcf': Item contains 0 components
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 856, in do_PUT
    "Item contains %d components" % len(items))
RuntimeError: Item contains 0 components
2017-10-05 13:36:48,914 - DEBUG: Response content:
Bad Request
2017-10-05 13:36:48,915 - INFO: PUT response status for '/qqw/contactos.vcf/8050567579f3dc27a7554361d8621187d9c047c3.vcf' in 0.124 seconds: 400 Bad Request
```

The `radicale` user have all grants in `/var/lib/radicale` directory.

What occurs?

**Comment by Unrud** [comment]
Sounds like this is a duplicate of #709. The problem got fixed in Evolution: https://bugzilla.gnome.org/show_bug.cgi?id=787656

**Comment by orencio** [comment]
Ok, thank you.

**Comment by orencio** [comment]
It is confirmed. With evolution 3.26.1 the problem is solved.
