### ISSUE TITLE
caldav-sync errors

### ISSUE THREAD

**Issue by potuz** [Kozea/Radicale#782]
I am experiencing some trouble running radicale 2.0.0 and connecting from an Android running the free version of Caldav-Sync Free Beta. I am not sure if this is related to #695 frankly because that report seems to be about unrelated issues. 

Radicale hangs on the server sporadically, I have to kill it -9 and restart it and then Android syncs well for a while. Some errors pop up in radicale's log as follows:

```
2018-02-17 18:07:52,898 - [75bb7470] INFO: PROPFIND answer status for /potuz/ with depth 1 in 18.766 seconds: 207 Multi-Status
2018-02-17 18:07:52,913 - [75bb7470] ERROR: An exception occurred during request:
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 280, in write
    self._flush()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 466, in _flush
    self.stdout.flush()
  File "/usr/lib/python3.5/socket.py", line 594, in write
    return self._sock.send(b)
  File "/usr/lib/python3.5/ssl.py", line 869, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 594, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 138, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 36, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'

Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/site-packages/radicale/__init__.py", line 175, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/site-packages/radicale/__init__.py", line 190, in handle
    super().handle()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 140, in handle
    stdout.detach()
  File "/usr/lib/python3.5/socket.py", line 594, in write
    return self._sock.send(b)
  File "/usr/lib/python3.5/ssl.py", line 869, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 594, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by potuz** [comment]
I think this may be a duplicate of #748

**Comment by pbiering** [comment]
closed as old version, please reopen if reproducable with current one
