### ISSUE TITLE
default wsgi config file generates a permission denied error

### ISSUE THREAD

**Issue by oupala** [Kozea/Radicale#788]
I'm using radicale on a default debian stretch, so this is radicale 1.1.1. I use it with apache and is it configured to use wsgi.

When I use a configuration file in apache www default directory, it works.

```bash
>namei -l /var/www/example.org/dav/radicale.wsgi 
f: /var/www/example.org/dav/radicale.wsgi
drwxr-xr-x root root /
drwxr-xr-x root root var
drwxr-xr-x root root www
drwxr-xr-x root root example.org
drwxr-xr-x root root dav
-rw-r--r-- root root radicale.wsgi
```

But when I try to use the default file that is from the official debian radicale package:

```bash
>namei -l /usr/share/radicale/radicale.wsgi 
f: /usr/share/radicale/radicale.wsgi
drwxr-xr-x root root /
drwxr-xr-x root root usr
drwxr-xr-x root root share
drwxr-xr-x root root radicale
-rw-r--r-- root root radicale.wsgi
```

It doesn't work any more and the error is:

```log
[Fri Mar 02 00:52:08.403642 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856] mod_wsgi (pid=24257): Target WSGI script '/usr/share/radicale/radicale.wsgi' cannot be loaded as Python module.
[Fri Mar 02 00:52:08.409504 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856] mod_wsgi (pid=24257): Exception occurred processing WSGI script '/usr/share/radicale/radicale.wsgi'.
[Fri Mar 02 00:52:08.412077 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856] Traceback (most recent call last):
[Fri Mar 02 00:52:08.413941 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]   File "/usr/share/radicale/radicale.wsgi", line 28, in <module>
[Fri Mar 02 00:52:08.416824 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]     radicale.log.start()
[Fri Mar 02 00:52:08.418560 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]   File "/usr/lib/python2.7/dist-packages/radicale/log.py", line 54, in start
[Fri Mar 02 00:52:08.421665 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]     configure_from_file(filename, debug)
[Fri Mar 02 00:52:08.423100 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]   File "/usr/lib/python2.7/dist-packages/radicale/log.py", line 40, in configure_from_file
[Fri Mar 02 00:52:08.425319 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]     logging.config.fileConfig(filename)
[Fri Mar 02 00:52:08.427048 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]   File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
[Fri Mar 02 00:52:08.433181 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]     handlers = _install_handlers(cp, formatters)
[Fri Mar 02 00:52:08.435054 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]   File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
[Fri Mar 02 00:52:08.437009 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]     h = klass(*args)
[Fri Mar 02 00:52:08.438413 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]   File "/usr/lib/python2.7/logging/__init__.py", line 911, in __init__
[Fri Mar 02 00:52:08.447653 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]     StreamHandler.__init__(self, self._open())
[Fri Mar 02 00:52:08.449153 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]   File "/usr/lib/python2.7/logging/__init__.py", line 936, in _open
[Fri Mar 02 00:52:08.451492 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856]     stream = open(self.baseFilename, self.mode)
[Fri Mar 02 00:52:08.453474 2018] [wsgi:error] [pid 24257] [client 192.168.1.13:49856] IOError: [Errno 13] Permission denied: '/var/log/radicale/radicale.log'
```

Where does this `permission denied` error come from? Is there a difference between the 2 files, or the way radicale is launched?

```bash
>namei -l /var/log/radicale/radicale.log
f: /var/log/radicale/radicale.log
drwxr-xr-x root     root     /
drwxr-xr-x root     root     var
drwxr-xr-x root     root     log
drwxr-x--- radicale radicale radicale
-rw-r--r-- radicale radicale radicale.log
```

When testing, I obviously changed the `WSGIScriptAlias` directive in my apache vhost config so that I use one wsgi file or another.

```bash
WSGIDaemonProcess radicale user=radicale group=radicale threads=1
WSGIScriptAlias /dav /usr/share/radicale/radicale.wsgi
```

**Comment by oupala** [comment]
I still have the same *permission denied* error even if I change the permissions:

```bash
>namei -l /var/log/radicale/radicale.log
f: /var/log/radicale/radicale.log
drwxr-xr-x root     root     /
drwxr-xr-x root     root     var
drwxr-xr-x root     root     log
drwxrwxrwx radicale radicale radicale
-rwxrwxrwx radicale radicale radicale.log
```

**Comment by oupala** [comment]
I fixed the problem, but I can't remember how.
