### ISSUE TITLE
Error uploading ics file

### ISSUE THREAD

**Issue by G10h4ck** [Kozea/Radicale#806]
Importing a some calendars via curl to radicale I obtain this error

`curl --insecure -u 'user:password' -X PUT https://localhost:5232/Matakrostes --data-binary @Matakrostes`

```
[7f57c9dd7700] WARNING: Bad PUT request on '/Matakrostes': Failed to store item 'f4a304d5-b40f-0b7e-62c8-54f31c248786.ics' in temporary collection 'Matakrostes': can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/radicale/storage.py", line 1018, in _upload_all_nonatomic
    cache_content = self._item_cache_content(href, vobject_item)
  File "/usr/lib64/python3.5/site-packages/radicale/storage.py", line 1271, in _item_cache_content
    tag, start, end = xmlutils.find_tag_and_time_range(vobject_item)
  File "/usr/lib64/python3.5/site-packages/radicale/xmlutils.py", line 687, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/usr/lib64/python3.5/site-packages/radicale/xmlutils.py", line 358, in _visit_time_ranges
    for dtstart in dtstarts:
  File "/usr/lib64/python3.5/site-packages/dateutil/rrule.py", line 1375, in _iter
    while exlist and exlist[0] < ritem:
  File "/usr/lib64/python3.5/site-packages/dateutil/rrule.py", line 1312, in __lt__
    return self.dt < other.dt
TypeError: can't compare offset-naive and offset-aware datetimes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/radicale/__init__.py", line 897, in do_PUT
    path, items, props)
  File "/usr/lib64/python3.5/site-packages/radicale/storage.py", line 979, in create_collection
    self._upload_all_nonatomic(vobject_items)
  File "/usr/lib64/python3.5/site-packages/radicale/storage.py", line 1023, in _upload_all_nonatomic
    (href, self.path, e)) from e
ValueError: Failed to store item 'f4a304d5-b40f-0b7e-62c8-54f31c248786.ics' in temporary collection 'Matakrostes': can't compare offset-naive and offset-aware datetimes
[7f57c9dd7700] DEBUG: Response content:
Bad Request
[7f57c9dd7700] INFO: PUT response status for '/Matakrostes' in 5.608 seconds: 400 Bad Request
```

Same techinique worked with other ics files, some suggestion on how to fix this error i am using radicale 2.1.8?

**Comment by Unrud** [comment]
It's a bug in VObject, in combination with a new version of python-dateutil. It got fixed in version 2.1.9 by specifying the exact versions for VObject and python-dateutil.
