### ISSUE TITLE
Apple iCal error "offset must be a timedelta representing a whole number of minutes"

### ISSUE THREAD

**Issue by 776166** [Kozea/Radicale#810]
When add time start/stop event time

![2018-04-20 23 04 32](https://user-images.githubusercontent.com/6876209/39071321-49c03d04-44ef-11e8-8cb7-0672a9f29af6.png)
--debug log:

```
[7f261da26700] INFO: PUT request for '/madget/7b647bb6-ada2-edc5-8484-fa8bbaccd4c9/E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551.ics' received from 195.91.244.98 using 'Mac+OS+X/10.13.4 (17E199) CalendarAgent/399.2.2'
[7f261da26700] DEBUG: Request headers:
{'CONTENT_LENGTH': '744',
 'CONTENT_TYPE': 'text/calendar',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'ru',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': 'radicale.webdav.dev.madget.net:64510',
 'HTTP_IF_MATCH': '"28dc97f37fe3f22e55dfd736c0f9a8c5"',
 'HTTP_USER_AGENT': 'Mac+OS+X/10.13.4 (17E199) CalendarAgent/399.2.2',
 'PATH_INFO': '/madget/7b647bb6-ada2-edc5-8484-fa8bbaccd4c9/E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '195.91.244.98',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'h195-91-244-98.ln.rinet.ru',
 'SERVER_PORT': '64510',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7f261f2fb5e8>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7f261da26700] DEBUG: Sanitized script name: ''
[7f261da26700] DEBUG: Sanitized path: '/madget/7b647bb6-ada2-edc5-8484-fa8bbaccd4c9/E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551.ics'
[7f261da26700] INFO: Successful login: 'madget'
[7f261da26700] DEBUG: Request content:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.13.4//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Moscow
BEGIN:STANDARD
TZOFFSETFROM:+023017
DTSTART:20010101T000000
TZNAME:GMT+3
TZOFFSETTO:+023017
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20180420T193555Z
UID:E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551
DTEND;TZID=Europe/Moscow:20180420T130000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:ня — 2
DTSTART;TZID=Europe/Moscow:20180420T120000
DTSTAMP:20180420T200353Z
SEQUENCE:0
BEGIN:VALARM
X-WR-ALARMUID:06071073-A112-40CA-83AA-C05F54736B36
UID:06071073-A112-40CA-83AA-C05F54736B36
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
ACTION:NONE
END:VALARM
END:VEVENT
END:VCALENDAR

[7f261da26700] WARNING: Bad PUT request on '/madget/7b647bb6-ada2-edc5-8484-fa8bbaccd4c9/E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551.ics': Failed to store item 'E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551.ics' in collection 'madget/7b647bb6-ada2-edc5-8484-fa8bbaccd4c9': offset must be a timedelta representing a whole number of minutes
Traceback (most recent call last):
  File "/home/madget/webdav/env3/lib/python3.4/site-packages/radicale/storage.py", line 1452, in upload
    self._store_item_cache(href, vobject_item)
  File "/home/madget/webdav/env3/lib/python3.4/site-packages/radicale/storage.py", line 1277, in _store_item_cache
    content = self._item_cache_content(href, vobject_item, cache_hash)
  File "/home/madget/webdav/env3/lib/python3.4/site-packages/radicale/storage.py", line 1271, in _item_cache_content
    tag, start, end = xmlutils.find_tag_and_time_range(vobject_item)
  File "/home/madget/webdav/env3/lib/python3.4/site-packages/radicale/xmlutils.py", line 692, in find_tag_and_time_range
    return tag, math.floor(start.timestamp()), math.ceil(end.timestamp())
ValueError: offset must be a timedelta representing a whole number of minutes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/madget/webdav/env3/lib/python3.4/site-packages/radicale/__init__.py", line 910, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "/home/madget/webdav/env3/lib/python3.4/site-packages/radicale/storage.py", line 1455, in upload
    (href, self.path, e)) from e
ValueError: Failed to store item 'E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551.ics' in collection 'madget/7b647bb6-ada2-edc5-8484-fa8bbaccd4c9': offset must be a timedelta representing a whole number of minutes
[7f261da26700] DEBUG: Response content:
Bad Request
[7f261da26700] INFO: PUT response status for '/madget/7b647bb6-ada2-edc5-8484-fa8bbaccd4c9/E96B9F38-8F70-4F1D-AAAC-2CD0BAC40551.ics' in 0.019 seconds: 400 Bad Request
```

**Comment by Unrud** [comment]
It only works with Python>=3.6. Try to update your version of Python.

I've added a test for this in 70e7363be6b3c0dd317e048f348ffc8c77c35618.

**Comment by 776166** [comment]
Fixed.
Thank you.
May be you will change python3.3 to 3.6 @ http://radicale.org/tutorial/ ? Or note about iCal?

**Comment by Unrud** [comment]
The tutorial now recommends Python >= 3.6 and the error message says that the feature is unsupported in Python < 3.6.
