### ISSUE TITLE
Log to file: "Invalid section" error in config

### ISSUE THREAD

**Issue by 776166** [Kozea/Radicale#811]
All under 'madget' user.
FULL Config:
```
[auth]
type = htpasswd
htpasswd_filename = /home/madget/webdav/etc/users
htpasswd_encryption = bcrypt
delay = 1

[server]
hosts = 0.0.0.0:64510
max_connections = 20
max_content_length = 10000000
timeout = 10

[loggers]
keys = root
[handlers]
keys = file

[formatters]
keys = full

[logger_root]
level = DEBUG
handlers = file

[handler_file]
class = FileHandler
args = ('/home/madget/webdav/log',)
formatter = full

[formatter_full]
format = %(asctime)s - [%(thread)x] %(levelname)s: %(message)s

[storage]
filesystem_folder = /home/madget/webdav/radicale/
```

Error on start:
```
ERROR: Invalid configuration: Invalid section 'loggers' in config
Traceback (most recent call last):
  File "/home/madget/webdav/env3.6/bin/radicale", line 31, in <module>
    radicale.__main__.run()
  File "/home/madget/webdav/env3.6/lib/python3.6/site-packages/radicale/__main__.py", line 93, in run
    ignore_missing_paths=ignore_missing_paths)
  File "/home/madget/webdav/env3.6/lib/python3.6/site-packages/radicale/config.py", line 237, in load
    raise RuntimeError("Invalid section %r in config" % section)
RuntimeError: Invalid section 'loggers' in config
```

**Comment by Unrud** [comment]
You have to put this in a separate file:
```ini
[loggers]
keys = root
[handlers]
keys = file

[formatters]
keys = full

[logger_root]
level = DEBUG
handlers = file

[handler_file]
class = FileHandler
args = ('/home/madget/webdav/log',)
formatter = full

[formatter_full]
format = %(asctime)s - [%(thread)x] %(levelname)s: %(message)s
```

In Radicale's config file you can reference it with:
```ini
[logging]
config = /path/to/logging.cfg
```

**Comment by 776166** [comment]
Yes. Thank you.

**Comment by Anachron** [comment]
I get this now:

log.cfg
```
[loggers]
keys = root

[handlers]
keys = file

[formatters]
keys = full

[logger_root]
# Change this to DEBUG or INFO for higher verbosity.
level = WARNING
handlers = file

[handler_file]
class = FileHandler
# Specify the output file here.
args = (/var/log/radicale/log,)
formatter = full

[formatter_full]
format = %(asctime)s - [%(thread)x] %(levelname)s: %(message)s
```

ERROR: Failed to start logger: Failed to load logging configuration file '/etc/radicale/log.cfg': invalid syntax (<string>, line 1)

Why is that?

**Comment by rngtng** [comment]
I ran into same issue, just by editing default config: https://github.com/Kozea/Radicale/blob/master/config#L118-L120

does this mean those lines are wrong and need to be updated? Pls confirm and I'll shoot a PR

**Comment by rngtng** [comment]
ah nvm I used latest release (2.1.11) which is missing this change: https://github.com/Kozea/Radicale/commit/54b9995e22c7d30d3cd5c99ecd98a5f3ba103b2b so by using `master` the cfg aligns!?
