### ISSUE TITLE
Not a valid bcrypt hash

### ISSUE THREAD

**Issue by odinis** [Kozea/Radicale#821]
Using FreeBSD iocage jail for this. Installed everything according to the manual.
Used htpasswd -b -c /radicale/users user password 
Can see hashed password in file if opened with editor, but after launching with --debug it gives an error:

```
[80624ec00] DEBUG: Sanitized script name: ''
[80624ec00] DEBUG: Sanitized path: '/'
[80624ec00] ERROR: An exception occurred during GET request on '/': Invalid htpasswd file '/radicale/users': not a valid bcrypt hash
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/radicale/auth.py", line 255, in is_authenticated
    password_ok = self.verify(hash_value, password)
  File "/usr/local/lib/python3.6/site-packages/radicale/auth.py", line 227, in _bcrypt
    return bcrypt.verify(password, hash_value)
  File "/usr/local/lib/python3.6/site-packages/passlib/utils/handlers.py", line 757, in verify
    self = cls.from_string(hash, **context)
  File "/usr/local/lib/python3.6/site-packages/passlib/handlers/bcrypt.py", line 162, in from_string
    ident, tail = cls._parse_ident(hash)
  File "/usr/local/lib/python3.6/site-packages/passlib/utils/handlers.py", line 1173, in _parse_ident
    raise exc.InvalidHashError(cls)
ValueError: not a valid bcrypt hash
```

Any idea what I'm doing wrong?
Installed pip install bcrypt htpasswd passlib.

**Comment by odinis** [comment]
FreeBSD doesn't have correct port and package to use htpasswd with -B option (for bcrypt). A solution would be generate users file with online tools like http://aspirine.org/htpasswd_en.html
