### ISSUE TITLE
OSx Calendar and iOS Calendar  database storages on PROPFIND

### ISSUE THREAD

**Issue by cdwilhelm** [Kozea/Radicale#83]
I am using latest radicale with storage = database (postgres).  I'm using the latest schema.sql.   With Mozilla lightning I can sync events but with OSX (10.8.5) and iOS (7.0.1) there is an exception from the first propfind request.

I also removed the primary key from the header table but that didn't help.

```
[Mon Nov 18 16:49:38 2013] [error] PROPFIND request at /curt@curt.com/calendar.ics/ received
[Mon Nov 18 16:49:38 2013] [error] Request headers:
[Mon Nov 18 16:49:38 2013] [error] {'CONTENT_LENGTH': '2097',
[Mon Nov 18 16:49:38 2013] [error]  'CONTENT_TYPE': 'text/xml',
[Mon Nov 18 16:49:38 2013] [error]  'DOCUMENT_ROOT': '/var/www/html',
[Mon Nov 18 16:49:38 2013] [error]  'GATEWAY_INTERFACE': 'CGI/1.1',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_ACCEPT': '*/*',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_ACCEPT_LANGUAGE': 'en-us',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_BRIEF': 't',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_CONNECTION': 'keep-alive',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_DEPTH': '1',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_HOST': '192.168.0.33',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_PREFER': 'return-minimal',
[Mon Nov 18 16:49:38 2013] [error]  'HTTP_USER_AGENT': 'iOS/7.0.2 (11A501) dataaccessd/1.0',
[Mon Nov 18 16:49:38 2013] [error]  'PATH_INFO': '/curt@curt.com/calendar.ics/',
[Mon Nov 18 16:49:38 2013] [error]  'PATH_TRANSLATED': '/var/www/radicale.wsgi/curt@curt.com/calendar.ics/',
[Mon Nov 18 16:49:38 2013] [error]  'QUERY_STRING': '',
[Mon Nov 18 16:49:38 2013] [error]  'REMOTE_ADDR': '192.168.0.3',
[Mon Nov 18 16:49:38 2013] [error]  'REMOTE_PORT': '54891',
[Mon Nov 18 16:49:38 2013] [error]  'REQUEST_METHOD': 'PROPFIND',
[Mon Nov 18 16:49:38 2013] [error]  'REQUEST_URI': '/curt%40curt.com/calendar.ics/',
[Mon Nov 18 16:49:38 2013] [error]  'SCRIPT_FILENAME': '/var/www/radicale.wsgi',
[Mon Nov 18 16:49:38 2013] [error]  'SCRIPT_NAME': '',
[Mon Nov 18 16:49:38 2013] [error]  'SERVER_ADDR': '192.168.0.33',
[Mon Nov 18 16:49:38 2013] [error]  'SERVER_ADMIN': 'root@localhost',
[Mon Nov 18 16:49:38 2013] [error]  'SERVER_NAME': '192.168.0.33',
[Mon Nov 18 16:49:38 2013] [error]  'SERVER_PORT': '80',
[Mon Nov 18 16:49:38 2013] [error]  'SERVER_PROTOCOL': 'HTTP/1.1',
[Mon Nov 18 16:49:38 2013] [error]  'SERVER_SIGNATURE': '<address>Apache/2.2.15 (CentOS) Server at 192.168.0.33 Port 80</address>\\n',
[Mon Nov 18 16:49:38 2013] [error]  'SERVER_SOFTWARE': 'Apache/2.2.15 (CentOS)',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.application_group': '',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.callable_object': 'application',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.handler_script': '',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.input_chunked': '0',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.listener_host': '',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.listener_port': '80',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.process_group': 'radicale',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.request_handler': 'wsgi-script',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.script_reloading': '1',
[Mon Nov 18 16:49:38 2013] [error]  'mod_wsgi.version': (3, 2),
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.errors': <mod_wsgi.Log object at 0x7f63b8c5d3b0>,
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f63cb7953f0>,
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.input': <mod_wsgi.Input object at 0x7f63b8c340f0>,
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.multiprocess': False,
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.multithread': False,
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.run_once': False,
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.url_scheme': 'http',
[Mon Nov 18 16:49:38 2013] [error]  'wsgi.version': (1, 1)}
[Mon Nov 18 16:49:38 2013] [error] Sanitized path: /curt@curt.com/calendar.ics/
[Mon Nov 18 16:49:38 2013] [error] Request content:
[Mon Nov 18 16:49:38 2013] [error] <?xml version="1.0" encoding="UTF-8"?>
[Mon Nov 18 16:49:38 2013] [error] <A:propfind xmlns:A="DAV:">
[Mon Nov 18 16:49:38 2013] [error]   <A:prop>
[Mon Nov 18 16:49:38 2013] [error]     <A:add-member/>
[Mon Nov 18 16:49:38 2013] [error]     <C:allowed-sharing-modes xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <H:autoprovisioned xmlns:H="http://apple.com/ns/ical/"/>
[Mon Nov 18 16:49:38 2013] [error]     <E:bulk-requests xmlns:E="http://me.com/_namespace/"/>
[Mon Nov 18 16:49:38 2013] [error]     <H:calendar-color xmlns:H="http://apple.com/ns/ical/"/>
[Mon Nov 18 16:49:38 2013] [error]     <B:calendar-description xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <B:calendar-free-busy-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <H:calendar-order xmlns:H="http://apple.com/ns/ical/"/>
[Mon Nov 18 16:49:38 2013] [error]     <B:calendar-timezone xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <A:current-user-privilege-set/>
[Mon Nov 18 16:49:38 2013] [error]     <B:default-alarm-vevent-date xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <B:default-alarm-vevent-datetime xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <A:displayname/>
[Mon Nov 18 16:49:38 2013] [error]     <C:getctag xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <H:language-code xmlns:H="http://apple.com/ns/ical/"/>
[Mon Nov 18 16:49:38 2013] [error]     <H:location-code xmlns:H="http://apple.com/ns/ical/"/>
[Mon Nov 18 16:49:38 2013] [error]     <A:owner/>
[Mon Nov 18 16:49:38 2013] [error]     <C:pre-publish-url xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <C:publish-url xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <C:push-transports xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <C:pushkey xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <A:quota-available-bytes/>
[Mon Nov 18 16:49:38 2013] [error]     <A:quota-used-bytes/>
[Mon Nov 18 16:49:38 2013] [error]     <H:refreshrate xmlns:H="http://apple.com/ns/ical/"/>
[Mon Nov 18 16:49:38 2013] [error]     <A:resource-id/>
[Mon Nov 18 16:49:38 2013] [error]     <A:resourcetype/>
[Mon Nov 18 16:49:38 2013] [error]     <B:schedule-calendar-transp xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <B:schedule-default-calendar-URL xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <C:source xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <C:subscribed-strip-alarms xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <C:subscribed-strip-attachments xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <C:subscribed-strip-todos xmlns:C="http://calendarserver.org/ns/"/>
[Mon Nov 18 16:49:38 2013] [error]     <B:supported-calendar-component-set xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <B:supported-calendar-component-sets xmlns:B="urn:ietf:params:xml:ns:caldav"/>
[Mon Nov 18 16:49:38 2013] [error]     <A:supported-report-set/>
[Mon Nov 18 16:49:38 2013] [error]     <A:sync-token/>
[Mon Nov 18 16:49:38 2013] [error]   </A:prop>
[Mon Nov 18 16:49:38 2013] [error] </A:propfind>
[Mon Nov 18 16:49:38 2013] [error] 
[Mon Nov 18 16:49:38 2013] [error] Anonymous has read access to collection curt@curt.com/calendar.ics/
[Mon Nov 18 16:49:38 2013] [error] Anonymous has write access to collection curt@curt.com/calendar.ics/
[Mon Nov 18 16:49:38 2013] [error] Anonymous has read access to item 06797930-34dd-0131-ccf7-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has write access to item 06797930-34dd-0131-ccf7-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has read access to item 105deeb9-b05e-e745-9a15-85c2bbd85012.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has write access to item 105deeb9-b05e-e745-9a15-85c2bbd85012.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has read access to item 52ff1080-34dd-0131-ccf8-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has write access to item 52ff1080-34dd-0131-ccf8-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has read access to item 56948f90-34de-0131-ccfc-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has write access to item 56948f90-34de-0131-ccfc-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has read access to item 7f2b9c90-34dd-0131-ccf9-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has write access to item 7f2b9c90-34dd-0131-ccf9-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has read access to item 900796a0-34dd-0131-ccfa-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] Anonymous has write access to item 900796a0-34dd-0131-ccfa-002500cf9534.ics
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3] mod_wsgi (pid=4648): Exception occurred processing WSGI script '/var/www/radicale.wsgi'.
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3] Traceback (most recent call last):
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/radicale/__init__.py", line 289, in __call__
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     user)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/radicale/__init__.py", line 502, in propfind
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     environ["PATH_INFO"], content, collections, user)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/radicale/xmlutils.py", line 237, in propfind
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     response = _propfind_response(path, collection, props, user)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/radicale/xmlutils.py", line 342, in _propfind_response
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     item.tag, item.headers, item.timezones)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/radicale/ical.py", line 408, in tag
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     with self.props as props:
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     return self.gen.next()
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/radicale/storage/database.py", line 239, in props
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     .filter_by(collection_path=self.path).all())
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2241, in all
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     return list(self)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2352, in __iter__
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     self.session._autoflush()
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1139, in _autoflush
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     self.flush()
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1818, in flush
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     self._flush(objects)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1936, in _flush
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     transaction.rollback(_capture_exception=True)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/util/langhelpers.py", line 58, in __exit__
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     compat.reraise(exc_type, exc_value, exc_tb)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1900, in _flush
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     flush_context.execute()
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     rec.execute(self)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 479, in execute
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     self.dependency_processor.process_deletes(uow, states)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/dependency.py", line 524, in process_deletes
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     uowcommit, False)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/dependency.py", line 569, in _synchronize
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     sync.clear(dest, self.mapper, self.prop.synchronize_pairs)
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]   File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/sync.py", line 53, in clear
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3]     (r, orm_util.state_str(dest))
[Mon Nov 18 16:49:38 2013] [error] [client 192.168.0.3] AssertionError: Dependency rule tried to blank-out primary key column 'header.collection_path' on instance '<DBHeader at 0x7f63b82b7e10>'
[Mon Nov 18 16:49:38 2013] [error] Exception sqlalchemy.exc.InvalidRequestError: InvalidRequestError("This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Dependency rule tried to blank-out primary key column 'header.collection_path' on instance '<DBHeader at 0x7f63b82b7e10>'",) in <bound method Collection.__del__ of <radicale.storage.database.Collection object at 0x7f63b82c2690>> ignored
```

**Comment by liZe** [comment]
As it's defined in #372, the storage modules have been removed from Radicale and will be available thanks to external "plugins". Would you be interested in developing a database plugin and/or maintaining it? You can add your comments in #391.
