### ISSUE TITLE
WARNING: Bad PUT request: dtstart

### ISSUE THREAD

**Issue by sphh** [Kozea/Radicale#863]
I use the Thunderbird add-on [Reply Monitor](https://github.com/hanlindev/ReplyMonitor). I changed the calendar used by Reply Monitor to a Radicale calendar (how to do it, see this [issue](https://github.com/hanlindev/ReplyMonitor/issues/15)).

When I create a reminder, I get a `WARNING: Bad PUT request on '<ID>.ics': Failed to store item '<ID>.ics' in collection 'sph/reply_monitor': dtstart` in the system logs. Still it seems that the calendar entry is created in the appropriate calendar...

My server system:
python 3.5.3
Radicale 2.1.10
vobject 0.9.6.1
python_dateutil 2.7.3
pytz 2018.5
installed with pip3 on a Debian 9.5 system

My client system:
Thunderbird 52.9.1
Lightning 5.4
Reply Monitor 1.0.0
on a Mint 19 Cinnamon system

`radicale.log`:
```
2018-08-29 09:08:44,091 - [-48b51ec0] INFO: Starting Radicale
2018-08-29 09:08:44,093 - [-48b51ec0] INFO: Authentication type is 'radicale_dovecot_auth'
2018-08-29 09:08:44,093 - [-48b51ec0] INFO: Storage type is 'multifilesystem'
2018-08-29 09:08:44,093 - [-48b51ec0] INFO: Rights type is 'owner_only'
2018-08-29 09:08:44,093 - [-48b51ec0] INFO: Web type is 'internal'
2018-08-29 09:08:44,100 - [-48b51ec0] INFO: Listening to 'www.<server>' on port 5232 using SSL
2018-08-29 09:08:44,101 - [-48b51ec0] INFO: Radicale server ready
2018-08-29 09:09:09,799 - [-497774c0] INFO: PUT request for '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce@<server>.ics' received from <remote_address> using 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.9.1 Lightning/5.4'
2018-08-29 09:09:09,800 - [-497774c0] DEBUG: Request headers:
{'CONTENT_LENGTH': '610',
 'CONTENT_TYPE': 'text/calendar; charset=utf-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_CHARSET': 'utf-8,*;q=0.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'mail.<server>:5232',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 '
                    'Thunderbird/52.9.1 Lightning/5.4',
 'PATH_INFO': '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce@<server>.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '<remote_address>',
 'REMOTE_CERTIFICATE': None,
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'www.<server>',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0xb68cb344>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2018-08-29 09:09:09,800 - [-497774c0] DEBUG: Sanitized script name: ''
2018-08-29 09:09:09,800 - [-497774c0] DEBUG: Sanitized path: '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce@<server>.ics'
2018-08-29 09:09:09,852 - [-497774c0] INFO: Successful login: '<user>'
2018-08-29 09:09:09,853 - [-497774c0] DEBUG: Request content:
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
LAST-MODIFIED:20180829T080909Z
DTSTAMP:20180829T080909Z
UID:f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce@<server>
SUMMARY:"Radicale 3" is expecting replies from:<mailaddress> by 30/08/
 2018
DTSTART;VALUE=DATE:20180830
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but co
 uld not find a property name or component begin tag: DURATION=PT1D
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT1M
DESCRIPTION:Default Mozilla Description
END:VALARM
END:VEVENT
END:VCALENDAR

2018-08-29 09:09:09,890 - [-497774c0] INFO: PUT response status for '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce@<server>.ics' in 0.091 seconds: 201 Created
2018-08-29 09:09:09,941 - [-497774c0] INFO: REPORT request for '/<user>/reply_monitor/' with depth '1' received from <remote_address> using 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.9.1 Lightning/5.4'
2018-08-29 09:09:09,942 - [-497774c0] DEBUG: Request headers:
{'CONTENT_LENGTH': '276',
 'CONTENT_TYPE': 'text/xml; charset=utf-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_CHARSET': 'utf-8,*;q=0.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'mail.<server>:5232',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 '
                    'Thunderbird/52.9.1 Lightning/5.4',
 'PATH_INFO': '/<user>/reply_monitor/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '<remote_address>',
 'REMOTE_CERTIFICATE': None,
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'REPORT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'www.<server>',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0xb68cb344>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2018-08-29 09:09:09,943 - [-497774c0] DEBUG: Sanitized script name: ''
2018-08-29 09:09:09,943 - [-497774c0] DEBUG: Sanitized path: '/<user>/reply_monitor/'
2018-08-29 09:09:09,946 - [-497774c0] INFO: Successful login: '<user>'
2018-08-29 09:09:09,947 - [-497774c0] DEBUG: Request content:
<?xml version="1.0"?>
<C:calendar-multiget xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <prop>
    <getetag />
    <C:calendar-data />
  </prop>
  <href>/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%2540<server>.ics</href>
</C:calendar-multiget>

2018-08-29 09:09:09,949 - [-497774c0] DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <response>
    <href>/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%2540<server>.ics</href>
    <status>HTTP/1.1 404 Not Found</status>
  </response>
</multistatus>

2018-08-29 09:09:09,949 - [-497774c0] INFO: REPORT response status for '/<user>/reply_monitor/' with depth '1' in 0.008 seconds: 207 Multi-Status
2018-08-29 09:09:10,932 - [-497774c0] INFO: PUT request for '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%40<server>.ics' received from <remote_address> using 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.9.1 Lightning/5.4'
2018-08-29 09:09:10,933 - [-497774c0] DEBUG: Request headers:
{'CONTENT_LENGTH': '584',
 'CONTENT_TYPE': 'text/calendar; charset=utf-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_CHARSET': 'utf-8,*;q=0.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'mail.<server>:5232',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 '
                    'Thunderbird/52.9.1 Lightning/5.4',
 'PATH_INFO': '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%40<server>.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '<remote_address>',
 'REMOTE_CERTIFICATE': None,
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'www.<server>',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0xb72632b4>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2018-08-29 09:09:10,933 - [-497774c0] DEBUG: Sanitized script name: ''
2018-08-29 09:09:10,933 - [-497774c0] DEBUG: Sanitized path: '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%40<server>.ics'
2018-08-29 09:09:10,937 - [-497774c0] INFO: Successful login: '<user>'
2018-08-29 09:09:10,937 - [-497774c0] DEBUG: Request content:
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
LAST-MODIFIED:20180829T080910Z
DTSTAMP:20180829T080910Z
UID:f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce@<server>
SUMMARY:"Radicale 3" : is expecting replies from: <mailaddress> by 30/
 08/2018
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but co
 uld not find a property name or component begin tag: DURATION=PT1D
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT1M
DESCRIPTION:Default Mozilla Description
END:VALARM
END:VEVENT
END:VCALENDAR

2018-08-29 09:09:10,944 - [-497774c0] WARNING: Bad PUT request on '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%40<server>.ics': Failed to store item 'f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%40<server>.ics' in collection '<user>/reply_monitor': dtstart
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/vobject/base.py", line 529, in __getattr__
    return self.contents[toVName(name)][0]
KeyError: 'dtstart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1484, in upload
    self._store_item_cache(href, vobject_item)
  File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1304, in _store_item_cache
    content = self._item_cache_content(vobject_item, cache_hash)
  File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1298, in _item_cache_content
    tag, start, end = xmlutils.find_tag_and_time_range(vobject_item)
  File "/usr/local/lib/python3.5/dist-packages/radicale/xmlutils.py", line 688, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/usr/local/lib/python3.5/dist-packages/radicale/xmlutils.py", line 340, in _visit_time_ranges
    dtstart = child.dtstart.value
  File "/usr/local/lib/python3.5/dist-packages/vobject/base.py", line 531, in __getattr__
    raise AttributeError(name)
AttributeError: dtstart

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/radicale/__init__.py", line 954, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "/usr/local/lib/python3.5/dist-packages/radicale/storage.py", line 1487, in upload
    (href, self.path, e)) from e
ValueError: Failed to store item 'f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%40<server>.ics' in collection '<user>/reply_monitor': dtstart
2018-08-29 09:09:10,947 - [-497774c0] DEBUG: Response content:
Bad Request
2018-08-29 09:09:10,948 - [-497774c0] INFO: PUT response status for '/<user>/reply_monitor/f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce%40<server>.ics' in 0.016 seconds: 400 Bad Request
2018-08-29 09:10:02,444 - [-48b51ec0] INFO: Stopping Radicale
```

**Comment by jonassmedegaard** [comment]
Reply Monitor don't work with Thunderbird 31 or newer.

I guess this bug can be closed as obsolete...

**Comment by sphh** [comment]
IMHO if `DTSTART;VALUE=DATE:20180830` is a valid `VEVENT` entry, this should be resolved - regardless if Reply Monitor does work or does not work.

I tried to validate the offending entry:
```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
LAST-MODIFIED:20180829T080909Z
DTSTAMP:20180829T080909Z
UID:f5da4b0c-21eb-9cf3-286b-8b3e69ad93ce@<server>
SUMMARY:"Radicale 3" is expecting replies from:<mailaddress> by 30/08/
 2018
DTSTART;VALUE=DATE:20180830
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but co
 uld not find a property name or component begin tag: DURATION=PT1D
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT1M
DESCRIPTION:Default Mozilla Description
END:VALARM
END:VEVENT
END:VCALENDAR
```
with https://icalendar.org/validator.html and it is a valid entry.

**Comment by pbiering** [comment]
works with current versions
