### ISSUE TITLE
Setup Radicale to work with SSL - IOS12 

### ISSUE THREAD

**Issue by holian7** [Kozea/Radicale#879]
Dear Masters,

 When IOS12 update installed on Iphone not sync anymore the contacts, and can't configure Cardav account on IPhone (without SSL?).
I'm not sure but i get an idea from another topic to install reverse proxy...so i tried...but i stucked with http_x_remote_user.

Anyway i'm not sure if reverse proxy necessary for me.

What i done:

- installed new radicale,
- make config file (auth: htpasswd)
- configure SSL (make certs..etc..)

On localhost i can log in to the web interface... when i try to configure carddav on IPhone 

```
> server: myserver.com
> user: admin
> pass:admin
> SSL
> Port: external port of the router (DSN-NAT to intranet)
> URL: https://myserver.com:EXTPORT/admin/
```

On the router i see the packages, and on the command window (radicale run in debug mode) i see the following:

```
C:\Users\holian>py -m radicale --config "c:\radicale\config" --debug
[76f0] INFO: Starting Radicale
[76f0] INFO: Authentication type is 'htpasswd'
[76f0] INFO: Storage type is 'multifilesystem'
[76f0] INFO: Rights type is 'from_file'
[76f0] INFO: Web type is 'internal'
[76f0] INFO: Listening to '127.0.0.1' on port 5234 using SSL
[76f0] INFO: Authentication type is 'htpasswd'
[76f0] INFO: Storage type is 'multifilesystem'
[76f0] INFO: Rights type is 'from_file'
[76f0] INFO: Web type is 'internal'
[76f0] INFO: Listening to 'holian-note.JSSPEED.LOCAL' on port 5234 using SSL
[76f0] INFO: Radicale server ready

[3148] ERROR: An exception occurred during request: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)
Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 193, in process_request_thread
    request.do_handshake()
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 197, in process_request_thread
    raise RuntimeError("SSL handshake failed: %s" % e) from e
RuntimeError: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)
```
May i ask some help?
Thank you

**Comment by mbauhardt** [comment]
I could imagine that you have to use the correct SSL protocol version see #702

**Comment by Tntdruid** [comment]
The caldav is broken in iOS 12, tested over 5 other caldavs systems all fail too.

**Comment by Tntdruid** [comment]
My config

[server]
hosts = dav.mydomain.tld:5232
daemon = True
timeout = 10
ssl = True
certificate = /etc/letsencrypt/live/dav.mydomain.tld/fullchain.pem
key = /etc/letsencrypt/live/dav.mydomain.tld/privkey.pem

protocol = PROTOCOL_TLSv1_2

[encoding]
request = utf-8

stock = utf-8


[auth]
type = radicale_imap
imap_host = mydomain.tld

imap_secure = True

type = multifilesystem

filesystem_folder = /var/lib/radicale/collections

filesystem_fsync = True

max_sync_token_age = 2592000
[web]
type = internal

My radicale.service

[Unit]
Description=radicale - A simple CalDAV (calendar) and CardDAV (contact) server
After=syslog.target network.target
Requires=network.target
[Service]
Type=simple
ExecStart=/usr/bin/radicale -f
User=root
Group=root
UMask=0027
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
NoNewPrivileges=true
ReadWritePaths=/var/lib/radicale/collections

[Install]
WantedBy=multi-user.target

When you add a account on iOS use

Server: dav.mydomain.tld:5232/
username: mail@dav.mydomain.tld
pw: yourpasword

Get the radicale imap plugin
python3 -m pip install  radicale_imap

**Comment by holian7** [comment]
I'm totally confused...i'm not sure if i have to try to setup Radicale with SSL or i have to setup Radicale with Apache proxy, or i have to set it up with Apace Proxy + SSL....
Anyway:

Here is my full config: (windows environment, python updated, python SSL version is the same as the OPenssl version, Certs generated with Openssl)
```
[server]
hosts = 127.0.0.1:5234, 192.168.1.136:5234
#daemon = False
max_connections = 2000
max_content_length = 50000000000
timeout = 3600
SSL = True
certificate = c:/open/rserver_cert.pem
key = c:/open/rserver_key.pem
certificate_authority = c:/radicale/ssl/client_cert.pem
protocol = PROTOCOL_TLSv1_2
[auth]
type = htpasswd
htpasswd_filename = c:/radicale/htpasswd.txt 
htpasswd_encryption = plain
delay = 3600
[rights]
type = from_file
file = c:/radicale/rights.txt 
[storage]
type = multifilesystem
filesystem_folder = c:/radicale/data/collections 
filesystem_locking = false
filesystem_fsync = false
#max_sync_token_age = 2592000
[web]
type = internal

```
Run radicale with:
`py -m radicale --config "c:\radicale\config" --debug
`
When start i get:
```
[6414] INFO: Starting Radicale
[6414] INFO: Authentication type is 'htpasswd'
[6414] INFO: Storage type is 'multifilesystem'
[6414] INFO: Rights type is 'from_file'
[6414] INFO: Web type is 'internal'
[6414] INFO: Listening to '127.0.0.1' on port 5234 using SSL
[6414] INFO: Authentication type is 'htpasswd'
[6414] INFO: Storage type is 'multifilesystem'
[6414] INFO: Rights type is 'from_file'
[6414] INFO: Web type is 'internal'
[6414] INFO: Listening to 'holian-note.comp.local' on port 5234 using SSL
[6414] INFO: Radicale server ready
```
On Iphone i try with this:
```
Server:externaladdress.comp.com
admin/admin
In the advanced menu SSL is on
Port:External port of the router (on router i set a NAT to local comp which host the Radicale server)
URL:https://externaladdress.comp.com:52326/admin/

```
When i try to save my connection on iphone, i get the message "Can't conntect with SSL...." On the windows command window i see the following (so the request reach the radicale server)

```
[700] ERROR: An exception occurred during request: SSL handshake failed: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1045)
Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 193, in process_request_thread
    request.do_handshake()
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1045)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 197, in process_request_thread
    raise RuntimeError("SSL handshake failed: %s" % e) from e
RuntimeError: SSL handshake failed: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1045)
[6144] ERROR: An exception occurred during request: SSL handshake failed: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1045)
Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 193, in process_request_thread
    request.do_handshake()
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1045)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 197, in process_request_thread
    raise RuntimeError("SSL handshake failed: %s" % e) from e
RuntimeError: SSL handshake failed: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1045)
[5388] ERROR: An exception occurred during request: SSL handshake failed: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1045)
Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 193, in process_request_thread
    request.do_handshake()
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1045)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holian\AppData\Local\Programs\Python\Python37-32\lib\site-packages\radicale\__init__.py", line 197, in process_request_thread
    raise RuntimeError("SSL handshake failed: %s" % e) from e
RuntimeError: SSL handshake failed: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1045)

```
I have no more hair...i'm just pullin' out my eyelids...

**Comment by holian7** [comment]
I'm still stucked. Anyone who can help us?
Thank you

**Comment by Tntdruid** [comment]
Try
And remove certificate_authority = c:/radicale/ssl/client_cert.pem

**Comment by holian7** [comment]
> Looks like i got it working for iOS12
> 
> Added this to my dns.
> 
> _carddavs._tcp.. 3600 IN SRV 10 20 443 dav.example.org.
> 
> Radicale now works again in iOS12
> 
> Found the info here
> http://sabre.io/dav/service-discovery/
> 
> Try this protocol = PROTOCOL_TLSv1_2 for the ssl error

Dear TNT:

You set up your Radicale server with SSL,  htpasswd auth? Don't use reverse proxy, do you? 
Do you use in windows environment? If so, is there any chance to ZIP the hole environment?

**Comment by Tntdruid** [comment]
I use Centos 7 for my server

**Comment by holian7** [comment]
I can't find any words than: Thank you Tnt. Thank you! Thank you!

Did i mentioned? Thank you!
Remove the  "certificate_authority = c:/radicale/ssl/client_cert.pem" line did the trick! Works!!

You are a genius!

I will buy you a beer! (or milk...)

**Comment by Tntdruid** [comment]
Glad it works :D

**Comment by mbauhardt** [comment]
@holian7 
Awesome to hear you got it working.
Just to summarize...
* Do you configured radicale with or without ssl support?
* Do you configured apache webserver infront of radicale and the apache handles ssl?

Can you write a summary about the steps you did to make IOS12 and radicale working plz plz plz?
maybe with config files...

Thx
Marko

**Comment by holian7** [comment]
Dear mbbauhardt,

 - i configured with SSL and there is no reverse proxy need 
 - very important:
     - the python SSL version must be the same as the OPENSSL version which is used to generate the certs.
     - so install the latest Python, update it, check the SSL version in it and after this download the same OPENSSL version and generate CERT.
    - how to generate cert: https://radicale.org/proxy/
         
Here is my config with relevant part of config files: (windows environment, python updated, python SSL version is the same as the OPenssl version, Certs generated with Openssl)

```
[server]
hosts = 127.0.0.1:5234, 192.168.1.136:5234
#daemon = False
max_connections = 2000
max_content_length = 50000000000
timeout = 3600
SSL = True
certificate = c:/open/rserver_cert.pem
key = c:/open/rserver_key.pem
protocol = PROTOCOL_TLSv1_2
[auth]
type = htpasswd
htpasswd_filename = c:/radicale/htpasswd.txt 
htpasswd_encryption = plain
delay = 3600
[rights]
type = from_file
file = c:/radicale/rights.txt 
[storage]
type = multifilesystem
filesystem_folder = c:/radicale/data/collections 
filesystem_locking = false
filesystem_fsync = false
#max_sync_token_age = 2592000
[web]
type = internal
```

**Comment by holian7** [comment]
confirmed.

**Comment by mookie-** [comment]
@holian7 Can you please close this issue, so it doesn't appear as "open" anymore? :)
