### ISSUE TITLE
Evolution can't move recurring events to Radicale

### ISSUE THREAD

**Issue by msrd0** [Kozea/Radicale#930]
Hi,

I've just connected Evolution to my Radicale instance and tried to move some recurring events to Radicale calendar. Those events recur every week and have a fixed number of recurrences. However, Evolution always complains about getting a 400 error, and in the log I can see:

```
2019-02-27T23:07:19.651896470Z [7ff1d812aae8] WARNING: Unsupported REPORT method 'D:expand-property' on '/msrd0/' requested
2019-02-27T23:10:35.443051775Z [7ff1d812aae8] WARNING: Bad PUT request on '/msrd0/d16348bb-944e-6153-88eb-468224f25fe3/e7f67d7b8db215ade18041e3298009a479b1780f.ics': Failed to store item 'e7f67d7b8db215ade18041e3298009a479b1780f.ics' in collection 'msrd0/d16348bb-944e-6153-88eb-468224f25fe3': Overwritten recurrence with RRULESET
```

I can however move the events if I remove the recurrence from them and make them a single event.

How to fix this?

**Comment by zakkak** [comment]
I am facing the same issue:

```
WARNING: Bad REPORT request on '/asd@asd.net/5ead43d6f9380863414732394ff7229e8af09b0613424268d43cdcbbf30c2e84/': Failed to filter item '58609c4e67732270bf1bc91dbe0ed4d2f0c616dfd800c89795e0abc2b66bef8e.ics' from 'asd@asd.net/5ead43d6f9380863414732394ff7229e8af09b0613424268d43cdcbbf30c2e84': Overwritten recurrence with RRULESET
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 1270, in report
    if not all(match(item, filter_) for filter_ in filters):
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 1270, in <genexpr>
    if not all(match(item, filter_) for filter_ in filters):
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 1252, in match
    return _comp_match(item, filter_[0])
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 207, in _comp_match
    if not _comp_match(item, child, level=level + 1):
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 204, in _comp_match
    if not _time_range_match(item.item, filter_[0], tag):
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 279, in _time_range_match
    _visit_time_ranges(vobject_item, child_name, range_fn, infinity_fn)
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 337, in _visit_time_ranges
    for child, is_recurrence, recurrences in get_children(
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 325, in get_children
    raise ValueError("Overwritten recurrence with RRULESET")
ValueError: Overwritten recurrence with RRULESET

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/radicale/__init__.py", line 981, in do_REPORT
    status, xml_answer = xmlutils.report(
  File "/usr/lib/python3.8/site-packages/radicale/xmlutils.py", line 1273, in report
    raise ValueError("Failed to filter item %r from %r: %s" %
ValueError: Failed to filter item '58609c4e67732270bf1bc91dbe0ed4d2f0c616dfd800c89795e0abc2b66bef8e.ics' from 'asd@asd.net/5ead43d6f9380863414732394ff7229e8af09b0613424268d43cdcbbf30c2e84': Overwritten recurrence with RRULESE
```

**Comment by PeterNerlich** [comment]
Is someone able to give some insight into this? Apparently, working with recurring events from other clients (I tried [CalDavZAP](https://www.inf-it.com/open-source/clients/caldavzap/)) works without problems. So what is special about evolution? Is it something in the spec (or maybe outside of it and most implementations just happen understand it) and Radicale will never support it or has just no one gotten around to look into this?

For me, this is preventing me from switching to Radicale as I use Ubuntu Touch and their calendar is/uses evolution and ends up syncing forever and ultimately failing. So if this issue is considered relatively easy, I'm interested in trying to fix it myself, I just haven't tried to look into the structure of Radicale and the API and whatever it is supposed to do yet.

**Comment by msrd0** [comment]
Funnily enough I'm still using Radicale and Evolution and haven't run into this issue for a while now, although saving recurring events still takes forever (but works)

**Comment by Unrud** [comment]
It's a bug in Thunderbird. The master branch already contains a workaround for this.

**Comment by PeterNerlich** [comment]
In Thunderbird? Does Thunderbird use evolution internally, too?

**Comment by Unrud** [comment]
> In Thunderbird?

Of course not, I misread the question.

**Comment by Unrud** [comment]
Sorry for the late response.
I did a bit of testing with Evolution. It produces invalid iCalendar data when moving or changing recurring events in certain ways. I wasn't able to reproduce your exact problem but the error message indicates invalid iCalendar data.

**Comment by msrd0** [comment]
Well, like I said I am also unable to reproduce this error with my current installed version of Evolution. Looks like this was fixed in evolution.
