### ISSUE TITLE
UTF-8 encoding error with Task/Calendar

### ISSUE THREAD

**Issue by stonerl** [Kozea/Radicale#961]
When I try to sync Tasks with [CalenGoo](https://play.google.com/store/apps/details?id=com.calengoo.android) I get the following error:

`An exception occurred during PUT request on '/toni/xxxx-xxx-xxx-xx-xx/1561488317254.ics': unknown encoding: utf-8, text/calendar`

Radicale: 2.1.11

**Comment by Tntdruid** [comment]
Did you set

request = utf-8
stock = utf-8

In config?

**Comment by stonerl** [comment]
No. According to the [documentation](https://radicale.org/configuration/) utf-8 is the default. I set it manually to utf-8 now, but still the same error.

**Comment by stonerl** [comment]
According to the CalenGoo developer [1] this seems to be a Radicale bug

[1] [CalenGoo Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/calengoo-android-support/ly-vNk5RELY)

**Comment by stonerl** [comment]
Here is the debug output:

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/local/lib/python3.6/dist-packages/radicale/__init__.py", line 446, in _handle_request
    authorization.encode("ascii")), environ).split(":", 1)
  File "/usr/local/lib/python3.6/dist-packages/radicale/__init__.py", line 296, in decode
    return text.decode(charset)
LookupError: unknown encoding: utf-8, text/calendar
`

**Comment by stonerl** [comment]
Here a more detailed output:

`
[7f4bb00c2700] INFO: PUT request for '/toni/2b50409c-812a-4f9d-86bb-083358b7cd83/d1ffb4e2-124e-4e1a-99bf-eaee5ad0066f.ics' with depth '1' received from '178.63.171.161' (forwarded by 127.0.0.1) using 'CG-Android'
[7f4bb00c2700] DEBUG: Request headers:
{'CONTENT_LENGTH': '307',
 'CONTENT_TYPE': 'text/calendar; charset=utf-8, text/calendar; charset=utf-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'CG-Android',
 'HTTP_X_FORWARDED_FOR': '178.63.171.161',
 'HTTP_X_FORWARDED_HOST': 'radicale.domain.tld',
 'HTTP_X_FORWARDED_SERVER': 'radicale.domain.tld',
 'PATH_INFO': '/toni/2b50409c-812a-4f9d-86bb-083358b7cd83/d1ffb4e2-124e-4e1a-99bf-eaee5ad0066f.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7f4bb03204c8>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7f4bb00c2700] DEBUG: Sanitized script name: ''
[7f4bb00c2700] DEBUG: Sanitized path: '/toni/2b50409c-812a-4f9d-86bb-083358b7cd83/d1ffb4e2-124e-4e1a-99bf-eaee5ad0066f.ics'
[7f4bb00c2700] ERROR: An exception occurred during PUT request on '/toni/2b50409c-812a-4f9d-86bb-083358b7cd83/d1ffb4e2-124e-4e1a-99bf-eaee5ad0066f.ics': unknown encoding: utf-8, text/calendar
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/local/lib/python3.6/dist-packages/radicale/__init__.py", line 446, in _handle_request
    authorization.encode("ascii")), environ).split(":", 1)
  File "/usr/local/lib/python3.6/dist-packages/radicale/__init__.py", line 296, in decode
    return text.decode(charset)
LookupError: unknown encoding: utf-8, text/calendar
`

**Comment by stonerl** [comment]
The culprit seems to be this:

` 'CONTENT_TYPE': 'text/calendar; charset=utf-8, text/calendar; charset=utf-8',`

I guess Radicale expects:

` 'CONTENT_TYPE': 'text/calendar; charset=utf-8',`

**Comment by stonerl** [comment]
I use Apache as proxy. For some reason Apache changes the content type from

`'CONTENT_TYPE': 'text/calendar; charset=utf-8',`

to

`'CONTENT_TYPE': 'text/calendar; charset=utf-8, text/calendar; charset=utf-8',`

**Comment by stonerl** [comment]
This does seem to be a problem with CalenGoo. As a workaround  I added are write rule:
```
<If "req('Content-Type') == 'text/calendar; charset=utf-8, text/calendar; charset=utf-8'">
    RequestHeader set Content-Type "text/calendar; charset=utf-8"
</If>
```
