### ISSUE TITLE
Unable to get logging to work

### ISSUE THREAD

**Issue by jmfoleyjr** [Kozea/Radicale#974]
I installed radicale about a month ago (Slackware64 14.2, kernel 4.4.182), including Python3. I'm trying to get logging to work per the documentation: https://radicale.org/logging/. My config has
```
[logging]
config = /etc/radicale/logging
```
The /etc/radicale/logging file has:
```
[loggers]
keys = root

[handlers]
keys = file

[formatters]
keys = full

[logger_root]
# Change this to DEBUG or INFO for higher verbosity.
level = WARNING
handlers = file

[handler_file]
class = FileHandler
# args = ('/home/log/radicale/log',)
args = ('/home/radicale/log', 'midnight', 1, 7)
formatter = full

[formatter_full]
format = %(asctime)s - [%(thread)x] %(levelname)s: %(message)s
```
which is pretty much a clone of the documentation example except for where I located the log file and the args were taken from the reference "See: ..." link for rollover at midnight. When I run this I get the following error and radicale does not start:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/usr/lib64/python3.7/site-packages/radicale/__main__.py", line 186, in serve
    logger.info("Starting Radicale")
  File "/usr/lib64/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1131, in emit
    self.stream = self._open()
  File "/usr/lib64/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
TypeError: open() argument 4 must be str or None, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/radicale", line 11, in <module>
    load_entry_point('Radicale==2.1.11', 'console_scripts', 'radicale')()
  File "/usr/lib64/python3.7/site-packages/radicale/__main__.py", line 141, in run
    exc_info=True)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1131, in emit
    self.stream = self._open()
  File "/usr/lib64/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
TypeError: open() argument 4 must be str or None, not int
```
Can someone advise I what I need to do to fix this? These seem like errors deeply embedded in Python.
Thanks

**Comment by jmfoleyjr** [comment]
I got the logger working by changing
```
[handler_file]
class = FileHandler
args = ('/home/radicale/log/log', 'midnight', 1, 7)

```to
[handler_file]
class = FileHandler
args = ('/home/log/radicale/log/log',)
Apparently the extra parameters " , 'midnight', 1, 7" are not supported by the Radicale implementation? This, despite the radicale documentation reference to https://docs.python.org/3/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler which shows that exact example. If that is the case, perhaps the documentation should be updated. If I've done something wrong in my config, please correct me.

Before leaving the logging topic, the radicale documentation lists three logging levels: DEBUG, INFO, and WARNING? Is that it? How about ERROR? Is there a list of these somewhere and their relative priority? I have level = WARNING, but I'm seeing INFO: and DEBUG: messages. Why? Again, am I doing something wrong?
